(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const lesson=window.LESSON;
const params=new URLSearchParams(location.search);
const role=(params.get('eleapRole')||params.get('role')||localStorage.getItem('e-leap-preview-role')||'teacher').toLowerCase();
const isTeacher=role==='teacher'||role==='admin'||params.get('eleapMode')==='presentation';
let index=0,selectedChip=null,activeGroup=0;
const content=$('#content'),title=$('#title'),stageLabel=$('#stageLabel'),instruction=$('#instruction'),counter=$('#counter'),status=$('#status'),nav=$('#nav');
const parkImg='https://commons.wikimedia.org/wiki/Special:Redirect/file/Park-G%C3%BCell.jpg?width=1600';
const parkImg2='https://commons.wikimedia.org/wiki/Special:Redirect/file/Park_G%C3%BCell_Barcelona.jpg?width=1600';
const localParkVideo='/api/media?pathname=life-intermediate/u01/l03/assets/media/my-local-park.mp4';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=s=>String(s||'').trim().toLowerCase();

const instructions={
 s01:'Life A2–B1 · Unit 1 Lifestyle',
 s02:'By the end of the lesson, students will be able to:',
 s03:'Type a complete answer in the box and submit it. Your teacher can review your response before the class checks language together.',
 s04:'',
 s05:'Discuss the questions as a class. Then type one short response and submit it.',
 s06:'Look at the two forms. Type what each form is for, then submit your answers.',
 s07:'Drag and drop the headings into the right boxes and submit your answers.',
 s08:'Choose a group. Complete the meanings in the boxes, then submit your answers.',
 s09:'Watch the language-support video. Notice how speakers ask for and give personal information.',
 s10:'Drag each heading into a blank title box. Then add the information you think a new-student form should collect and submit your form.',
 s11:'',
 s12:'Study the photo and caption. Use the elicitation questions to prepare for the two discussion questions.',
 s13:'Drag each definition letter into the right box and submit your answers.',
 s14:'Watch the video. Number a–g in the order you see them. Submit your answers before the teacher reveals the sequence.',
 s15:'Watch again and complete the notes. Use Evidence only after you have made a choice. Submit before checking the model answers.',
 s16:'Work in pairs. Student A chooses one person from the video. Student B asks the two questions and guesses the person.',
 s17:'Think of a role model. Make notes first, then tell your partner about the person.',
 s18:'Use the checklist to review the lesson before you leave.',
 s19:'Write your own paragraph. Do not copy a pre-filled template. Submit by the deadline shown below.',
 s20:'Thank you for your work today.'
};

const formHeadings=['First Name','Middle Name','Surname','Title','Age','Date of Birth','Address','Postcode','Telephone Number','Gender','Email Address','First Language','Nationality','Interest','Emergency Contact'];
const matchHeadings=['Marital status','Current medications','No. of dependents','Country of origin','Place of birth','Contact details of person in case of emergency','Middle initial'];
const matchQuestions=['Are you married, single or divorced?','Do you take any pills or medicine?','How many children do you have?','What country were you born in?','What city/town were you born in?','Who can we call in your family if you need help?','What is the first letter of your middle name?'];
const vocabRows=[
 ['I like coming to the park no matter what the weather is like.','d'],
 ['Parents push their young children in prams.','b'],
 ["There’s a great view from the top of the hill.",'e'],
 ["We often come to the park when we’re in the area.",'a'],
 ["There’s a nice walkway round the park.",'f'],
 ['In spring, there is blossom on the trees.','c']
];
const vocabDefs={a:'a region or part of a town',b:'it has four wheels and you move babies or small children in it',c:'flowers that grow on trees',d:'it is not important and does not change my decision',e:'what you can see around you',f:'another word for a path or small road only for people'};
const orderRows=['A man is cycling.','A woman is walking with her dog.','A student is jogging.','There’s a large house near the park.','Two people are walking down a path.','A student is doing pull-ups.','A tractor is cutting the grass.'];
const orderAnswers=['2','1','5','3','4','6','7'];
const languageItems=[
 ['DOB','Date of Birth'],['No.','number'],['e.g.','for example'],['etc.','et cetera'],
 ['Mr','title used before a man’s name'],['Mrs','title used before a married woman’s name'],['Ms','title used before a woman’s name when marital status is unknown'],['Dr','Doctor'],
 ['CAPITAL LETTERS','uppercase letters'],['lower-case letters','small letters'],['middle initial','first letter of your middle name']
];
const noteRows=[
 ['Person 1','very often · every weekend after lunchtime','dogs for Jasmine · beautiful trees'],
 ['Person 2','every day · on sunny days at lunch break','high up · beautiful view'],
 ['Person 3','when in the area','family memories · different seasons'],
 ['Person 4','every day','walk through the park · spend time with friends'],
 ['Person 5','about twice a week','jogging · exercise · quiet park'],
 ['Person 6','quite often','wild flowers · blossom · plants']
];

function renderNav(){nav.innerHTML=lesson.activities.map((a,i)=>`<button data-nav="${i}" class="${i===index?'active':''}"><span>${String(i+1).padStart(2,'0')}</span>${esc(a.stage)}</button>`).join('');$$('[data-nav]',nav).forEach(b=>b.onclick=()=>go(Number(b.dataset.nav)));}
function go(i){if(i<0||i>=lesson.activities.length)return;index=i;activeGroup=0;selectedChip=null;render();}
function submitHTML(label='Submit answers'){return `<div class="submit-row"><button id="submit" class="submit" type="button">${label}</button><span class="inline-submit-status" aria-live="polite"></span></div>`;}
function responseHTML(id='response',rows=6,placeholder='Type your answer here...'){return `<div class="response-shell"><textarea id="${id}" class="long-response student-answer" rows="${rows}" placeholder="${esc(placeholder)}"></textarea><div class="hint">Your answer stays in this box. Teacher review and model-answer reveal do not create another answer box.</div>${submitHTML()}</div>`;}
function photo(url,caption,alt='Park photograph'){return `<div class="photo-card"><img src="${url}" alt="${esc(alt)}" onerror="this.src='https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1600&q=85'"><div class="photo-caption">${caption}</div></div>`;}
function video(src){return `<div class="video-frame"><video controls playsinline preload="metadata" src="${src}" data-local-park-video><p>Your browser cannot play this video.</p></video></div><div class="video-fallback">If the private classroom stream is still loading, use the same lesson video from the class media library.</div>`;}

function screenHTML(a){switch(a.id){
case's01':return `<div class="cover"><div class="cover-copy"><div class="big-unit">UNIT <span class="orange">1</span></div><p><span class="orange">1E</span> · PERSONAL INFORMATION<br><span class="orange">1F</span> · MY LOCAL PARK</p><div class="deadline">Life A2–B1</div></div>${photo(parkImg,'Unit 1 · Lifestyle · Life A2–B1','Real park landscape')}</div>`;
case's02':return `<div class="grid-3"><div class="card aim-card"><h3>Knowledge</h3><ul><li>Identify key personal-information vocabulary and collocations.</li><li>Summarise the main ideas of a text/video.</li><li>Complete a personal-information form accurately.</li></ul></div><div class="card aim-card"><h3>Skills</h3><ul><li>Fill in forms using appropriate language.</li><li>Use target language in speaking and writing.</li><li>Give a short self-introduction and describe a local park.</li></ul></div><div class="card aim-card"><h3>Attitudes</h3><ul><li>Participate actively in pair and group work.</li><li>Share personal views confidently and respectfully.</li></ul></div></div>`;
case's03':return `<div class="card"><h2>Previous lesson: health problems</h2><p class="question">Describe one health problem you have had or are suffering from. Include symptoms and what you did about it.</p>${responseHTML('healthResponse',7,'Type a full answer here...')}</div>`;
case's04':return `<div class="cover"><div class="cover-copy"><div class="unit-code">UNIT 1E</div><p>PERSONAL<br><span class="orange">INFORMATION</span></p></div>${photo('https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1600&q=85','Personal information · forms · accurate details','Professional paperwork and form image')}</div>`;
case's05':return `<div class="grid-2"><div class="card"><div class="question-list"><div class="question"><b>a.</b> What kinds of forms do you sometimes fill in?</div><div class="question"><b>b.</b> Think of a form you filled in. What information did you write?</div></div></div><div class="card discussion-box"><textarea id="formDiscussion" class="student-answer" placeholder="Type one short response here..."></textarea>${submitHTML()}</div></div>`;
case's06':return `<div class="forms-preview"><div class="mock-form"><h3>FORM A · CURRENT / MEDICAL INFORMATION</h3>${['Title','First name','Surname','Address','Gender','No. of dependents','Current medications','Past surgery / operations'].map(x=>`<div class="form-line">${x}</div>`).join('')}<div class="identify-row"><input data-answer-index="0" class="student-answer" placeholder="What is this form for?"></div></div><div class="mock-form visa"><h3>FORM B · PLEASE USE CAPITAL LETTERS</h3>${['Passport no.','Place of birth','Nationality','Marital status','Qualifications','Previous visits','Emergency contact'].map(x=>`<div class="form-line">${x}</div>`).join('')}<div class="identify-row"><input data-answer-index="1" class="student-answer" placeholder="What is this form for?"></div></div></div>${submitHTML()}`;
case's07':return dragMatchHTML(matchHeadings,matchQuestions,'heading');
case's08':return groupedLanguageHTML();
case's09':return `<div class="grid-2"><div class="video-frame"><iframe src="https://www.youtube.com/embed/_NMEWin4mU4?rel=0" title="Personal information questions" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><div class="card"><h3>Listen for useful questions</h3><div class="question-list"><div class="question">What’s your full name?</div><div class="question">Where were you born?</div><div class="question">What’s your nationality?</div><div class="question">Who can we contact in an emergency?</div></div><textarea id="videoNotes" class="long-response student-answer" style="min-height:130px;margin-top:12px" placeholder="Write 2 useful questions you hear..."></textarea>${submitHTML('Submit notes')}</div></div>`;
case's10':return formBuilderHTML();
case's11':return `<div class="park-cover"><div><div class="unit-code">UNIT 1F</div><h2>MY LOCAL PARK</h2><p style="font-size:22px;font-weight:800">Video · vocabulary · speaking</p></div>${photo(parkImg,'Park Güell · Barcelona · public park and architectural landmark','Park Güell in Barcelona')}</div>`;
case's12':return `<div class="grid-2">${photo(parkImg,'Park Güell, Barcelona · known for Gaudí’s architecture and public spaces','Park Güell in Barcelona')}<div class="card"><h3>Think first</h3><div class="elicitation"><button type="button">What can people do in a park like this?</button><button type="button">Who might you meet there?</button><button type="button">What makes a park pleasant or useful?</button></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="question-list"><div class="question"><b>1.</b> Where is your nearest park?</div><div class="question"><b>2.</b> Why do people like going there?</div></div>${responseHTML('parkLeadIn',4,'Write brief ideas here...')}</div></div>`;
case's13':return dragVocabHTML();
case's14':return videoOrderHTML();
case's15':return videoNotesHTML();
case's16':return `<div class="grid-2"><div class="role-card"><h3>Student A</h3><p>Choose one person from the video. Do not tell Student B.</p><p>Listen to Student B’s questions and answer using information from the video.</p><textarea id="roleA" class="student-answer" placeholder="Make notes for your chosen person..."></textarea></div><div class="role-card"><h3>Student B</h3><p>Ask:</p><div class="question">When do you come to the park?</div><div class="question">How often do you come?</div><p>Listen and guess which person Student A chose.</p><textarea id="roleB" class="student-answer" placeholder="Write your guess and reason..."></textarea></div></div>${submitHTML('Submit pair notes')}`;
case's17':return `<div class="card"><h3>Think of a role model in your life</h3><div class="question-list"><div class="question">1. Who is this person?</div><div class="question">2. Is the person in your family, in sport, at work or in public life?</div><div class="question">3. Why is he or she a role model for you?</div></div><textarea id="roleModel" class="long-response student-answer" placeholder="Make your own notes here..."></textarea>${submitHTML()}</div>`;
case's18':return `<div class="checklist"><div class="check-item"><b>Vocabulary</b><br>personal details · form language · park vocabulary</div><div class="check-item"><b>Questions</b><br>Wh- questions for personal information</div><div class="check-item"><b>Listening / video</b><br>identify sequence and specific details</div><div class="check-item"><b>Writing</b><br>fill in forms and give personal details</div><div class="check-item"><b>Speaking</b><br>talk about a park and a person</div><div class="check-item"><b>Reflection</b><br>What do you still want to practise?</div></div><textarea id="reflection" class="long-response student-answer" style="min-height:130px;margin-top:15px" placeholder="One thing I learned... One thing I still need to practise..."></textarea>${submitHTML('Submit reflection')}`;
case's19':return homeworkHTML();
case's20':return `<div class="end-screen"><div><h2>UNIT 1E & 1F<br>COMPLETE</h2><p>Personal Information · My Local Park</p></div>${photo(parkImg,'Life A2–B1 · Unit 1 Lifestyle','Professional park photograph')}</div>`;
default:return '<div class="card">Screen unavailable.</div>';}}

function dragMatchHTML(chips,questions){return `<div class="drag-layout"><div class="card"><h3>Heading bank</h3><div class="bank">${chips.map((x,i)=>`<button type="button" draggable="true" class="drag-chip" data-chip="${i}" data-value="${esc(slug(x))}">${esc(x)}</button>`).join('')}</div></div><div class="card"><div class="drop-list">${questions.map((q,i)=>`<div><div class="drop-row"><div class="drop-question"><b>${i+1}.</b> ${esc(q)}</div><div class="dropzone" data-drop="${i}"><input data-answer-index="${i}" class="student-answer" readonly aria-label="Answer ${i+1}"></div></div><div class="drop-help">Drop your answer here.</div></div>`).join('')}</div>${submitHTML()}</div></div>`;}
function groupedLanguageHTML(){const groups=[[0,4],[4,8],[8,11]],labels=['1–4','5–8','9–11'];return `<div class="card"><div class="group-tabs">${labels.map((x,i)=>`<button type="button" data-group="${i}" class="${i===activeGroup?'active':''}">${x}</button>`).join('')}</div><div class="form-language-list">${languageItems.slice(groups[activeGroup][0],groups[activeGroup][1]).map((x,j)=>{const n=groups[activeGroup][0]+j;return `<div class="form-language-row"><b>${n+1}</b><span>${esc(x[0])}</span><input data-language-index="${n}" data-answer-index="${j}" class="student-answer" placeholder="Type the meaning..."></div>`}).join('')}</div>${submitHTML()}</div>`;}
function formBuilderHTML(){return `<div class="form-builder"><div class="card label-bank"><h3>Drag the headings</h3><div class="bank">${formHeadings.map((x,i)=>`<button type="button" draggable="true" class="drag-chip" data-chip="${i}" data-value="${esc(x)}">${esc(x)}</button>`).join('')}</div><p class="drop-help" style="text-align:left;margin-top:12px">Choose the headings you think a new-student form needs. You do not have to use every heading.</p></div><div><div class="student-form">${Array.from({length:10},(_,i)=>`<div class="form-field"><div class="form-title-drop dropzone" data-drop="${i}"><input class="label-value student-answer" readonly aria-label="Form heading ${i+1}"></div><input class="student-answer" placeholder="Student enters information here..."></div>`).join('')}</div>${submitHTML('Submit your form')}</div></div>`;}
function dragVocabHTML(){return `<div class="drag-layout"><div class="card"><h3>Definitions</h3><div class="bank">${Object.entries(vocabDefs).map(([k,v])=>`<button type="button" draggable="true" class="drag-chip" data-chip="${k}" data-value="${k}"><b>${k}.</b> ${esc(v)}</button>`).join('')}</div></div><div class="card"><div class="drop-list">${vocabRows.map((r,i)=>`<div><div class="drop-row"><div class="drop-question"><b>${i+1}.</b> ${esc(r[0])}</div><div class="dropzone" data-drop="${i}"><input data-answer-index="${i}" class="student-answer" readonly></div></div><div class="drop-help">Drop your answer here.</div></div>`).join('')}</div>${submitHTML()}</div></div>`;}
function videoOrderHTML(){return `<div class="video-task"><div>${video(localParkVideo)}</div><div class="scroll-panel"><h3>Number a–g in the order you see them</h3>${orderRows.map((x,i)=>`<div class="order-row"><b>${String.fromCharCode(97+i)}.</b><span>${esc(x)}</span><input data-answer-index="${i}" class="student-answer" inputmode="numeric" maxlength="1" placeholder="1–7"></div>`).join('')}${submitHTML()}</div></div>`;}
function videoNotesHTML(){return `<div class="video-task"><div>${video(localParkVideo)}</div><div class="scroll-panel"><h3>Complete the notes</h3><p style="color:var(--muted);font-size:14px">Write short phrases. Evidence appears inside each row only when requested.</p><div class="notes-grid">${noteRows.map((r,i)=>`<div class="note-row" data-note="${i}"><b>${r[0]}</b><input class="student-answer" data-note-col="when" placeholder="When / how often"><input class="student-answer" data-note-col="why" placeholder="Why / detail"><button type="button" class="small-btn evidence-btn" data-evidence="${i}">Evidence</button><div class="evidence">Source notes: ${esc(r[1])} · ${esc(r[2])}</div></div>`).join('')}</div>${submitHTML()}</div></div>`;}
function homeworkHTML(){const deadline='8:00 p.m. · 12 Oct 2026';return `<div class="homework-shell"><div class="card"><div class="deadline">Deadline: ${deadline}</div><h3>Write a short paragraph about a person you admire.</h3><p>Choose the information that is relevant. Explain why you admire the person. There are no pre-filled “Title / First name / …” answers here: you decide what your paragraph needs.</p><textarea id="homeworkText" class="student-answer" placeholder="Write your paragraph here..."></textarea>${submitHTML('Submit homework')}<div id="homeworkApiStatus" class="status" style="text-align:left;margin-top:9px"></div></div><div class="rubric"><h3>Writing marking · 10 points</h3><div class="rubric-grid"><span>Task achievement</span><b>2</b><span>Organisation</span><b>2</b><span>Vocabulary</span><b>2</b><span>Grammar</span><b>2</b><span>Style</span><b>2</b></div><p style="font-size:13px;color:var(--muted)">Teacher saves the mark first. Students see the score and feedback only after feedback is released.</p>${isTeacher?`<div class="teacher-homework-actions"><button id="assignHomework" class="primary" type="button">Assign homework</button><button id="openSubmissions" type="button">Open submissions</button><button id="exportHomework" type="button">Export class CSV</button></div>`:''}</div></div>`;}

function wireDragDrop(){const chips=$$('.drag-chip',content),drops=$$('.dropzone',content);chips.forEach(ch=>{ch.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',ch.dataset.value||ch.textContent.trim());e.dataTransfer.setData('chip-id',ch.dataset.chip||'');});ch.onclick=()=>{chips.forEach(x=>x.classList.remove('selected'));selectedChip=ch;ch.classList.add('selected');status.textContent='Answer selected. Click the target box.';};});drops.forEach(d=>{d.addEventListener('dragover',e=>e.preventDefault());d.addEventListener('drop',e=>{e.preventDefault();place(d,e.dataTransfer.getData('text/plain'),e.dataTransfer.getData('chip-id'));});d.onclick=()=>{if(selectedChip)place(d,selectedChip.dataset.value||selectedChip.textContent.trim(),selectedChip.dataset.chip||'');};});function place(d,val,chipId){const input=$('input',d);if(!input)return;input.value=val;d.classList.add('filled');const chip=chips.find(x=>String(x.dataset.chip)===String(chipId));if(chip)chip.classList.add('used');selectedChip=null;status.textContent='';}}
function wireGroups(){$$('[data-group]',content).forEach(b=>b.onclick=()=>{activeGroup=Number(b.dataset.group);content.innerHTML=screenHTML(lesson.activities[index]);wireCurrent();});}
function collect(){return $$('.student-answer',content).map((el,i)=>({name:el.id||el.dataset.answerIndex||el.dataset.languageIndex||i,value:el.value}));}
function showInlineSubmit(msg,cls='success'){const el=$('.inline-submit-status',content);if(el){el.textContent=msg;el.className='inline-submit-status '+cls;}status.textContent=msg;}
function submitCurrent(){const a=lesson.activities[index],vals=collect();if(!vals.some(x=>String(x.value||'').trim())){showInlineSubmit('Add an answer before submitting.','error');return;}showInlineSubmit('Submitted ✓');if(a.id==='s19')submitHomeworkApi();}
function reveal(){const a=lesson.activities[index];if(!isTeacher){status.textContent='Show answer is available to Teacher / Presentation only.';return;}if(a.id==='s06'){const ins=$$('input[data-answer-index]',content);['medical form','visa application form'].forEach((v,i)=>{if(ins[i]){ins[i].value=v;ins[i].classList.add('note-answer');}});}else if(a.id==='s07'){const ins=$$('input[data-answer-index]',content);matchHeadings.forEach((v,i)=>{if(ins[i]){ins[i].value=slug(v);ins[i].closest('.dropzone')?.classList.add('filled');}});}else if(a.id==='s08'){const start=[0,4,8][activeGroup];$$('input[data-language-index]',content).forEach(inp=>{const i=Number(inp.dataset.languageIndex);inp.value=languageItems[i][1];inp.classList.add('note-answer');});}else if(a.id==='s13'){$$('input[data-answer-index]',content).forEach((inp,i)=>{inp.value=vocabRows[i][1];inp.closest('.dropzone')?.classList.add('filled');});}else if(a.id==='s14'){$$('input[data-answer-index]',content).forEach((inp,i)=>{inp.value=orderAnswers[i];inp.closest('.order-row')?.classList.add('answer');});}else if(a.id==='s15'){$$('.note-row',content).forEach((row,i)=>{const inputs=$$('input',row);if(inputs[0]){inputs[0].value=noteRows[i][1];inputs[0].classList.add('note-answer');}if(inputs[1]){inputs[1].value=noteRows[i][2];inputs[1].classList.add('note-answer');}});}else if(a.id==='s09'){const t=$('#videoNotes');if(t){t.value='Examples: What’s your full name? / Where were you born? / What’s your nationality?';t.classList.add('note-answer');}}else{status.textContent='This is an open-response activity. Review student responses before discussing a model.';return;}status.textContent='Answers revealed in place.';}
function reset(){content.innerHTML=screenHTML(lesson.activities[index]);status.textContent='';wireCurrent();}

async function assignHomework(){const classId=params.get('classId'),box=$('#homeworkApiStatus');if(!classId){box.textContent='Open this lesson from a Live Class so classId is available.';box.className='status error';return;}box.textContent='Creating assignment…';try{const r=await fetch('/api/research/assignments',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({classId,resourceId:lesson.resourceId,activityId:'s19',title:'Life Unit 1E–1F Homework',prompt:lesson.activities[18].prompt,rubricId:'writing-core-v1',deadline:lesson.deadline,attemptLimit:1,latePolicy:'allow-late',status:'active'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Assignment could not be created');box.textContent='Homework assigned ✓ · Deadline 8:00 p.m. 12 Oct 2026';box.className='status success';localStorage.setItem('life-u01-l03-assignment-id',d.assignment?.assignment_id||'');}catch(e){box.textContent=e.message;box.className='status error';}}
async function findHomeworkAssignment(){try{const r=await fetch('/api/research/assignments',{credentials:'same-origin'});if(!r.ok)return null;const d=await r.json();return (d.assignments||[]).find(x=>x.resource_id===lesson.resourceId&&x.activity_id==='s19'&&x.status==='active')||null;}catch{return null;}}
async function submitHomeworkApi(){if(role!=='student')return;const box=$('#homeworkApiStatus'),text=$('#homeworkText')?.value.trim();if(!text)return;const a=await findHomeworkAssignment();if(!a){if(box)box.textContent='Submitted to the live Responses Board. No active homework assignment is linked yet.';return;}try{const r=await fetch('/api/research/submissions',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({assignmentId:a.assignment_id,response:{text},researchConsent:false})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Homework submission failed');if(box){box.textContent='Homework submitted ✓ · Your teacher will release the mark and feedback after grading.';box.className='status success';}}catch(e){if(box){box.textContent=e.message;box.className='status error';}}}
function openSubmissions(){const code=params.get('joinCode')||params.get('code')||'';const u=new URL('/teacher-live.html',location.origin);if(params.get('classId'))u.searchParams.set('classId',params.get('classId'));u.searchParams.set('lesson',lesson.resourceId);if(code)u.searchParams.set('code',code);window.open(u,'_blank');}
function exportHomework(){const classId=params.get('classId');if(!classId){status.textContent='Open from a Live Class to export this class.';return;}location.href=`/api/research/export?kind=submissions&classId=${encodeURIComponent(classId)}&format=csv`;}

function wireCurrent(){wireDragDrop();wireGroups();$$('.evidence-btn',content).forEach(b=>b.onclick=()=>b.closest('.note-row')?.classList.toggle('evidence-on'));$('#submit',content)?.addEventListener('click',submitCurrent);$('#assignHomework',content)?.addEventListener('click',assignHomework);$('#openSubmissions',content)?.addEventListener('click',openSubmissions);$('#exportHomework',content)?.addEventListener('click',exportHomework);if(!isTeacher){$('#showAnswerBtn').hidden=true;$('#responsesBtn').hidden=true;}else{$('#showAnswerBtn').hidden=false;$('#responsesBtn').hidden=false;}}
function render(){const a=lesson.activities[index];document.body.dataset.screen=String(index+1);stageLabel.textContent=a.stage;title.textContent=a.title;instruction.textContent=instructions[a.id]||a.instruction||'';counter.textContent=`${index+1} / ${lesson.activities.length}`;content.innerHTML=screenHTML(a);$('#prev').disabled=index===0;$('#next').disabled=index===lesson.activities.length-1;status.textContent='';renderNav();wireCurrent();window.dispatchEvent(new CustomEvent('e-leap:screen-changed',{detail:{screen:index+1,activityId:a.id}}));}

$('#prev').onclick=()=>go(index-1);$('#next').onclick=()=>go(index+1);$('#showAnswerBtn').onclick=reveal;$('#resetBtn').onclick=reset;$('#responsesBtn').onclick=()=>openSubmissions();$('#roleBadge').textContent=isTeacher?(params.get('eleapMode')==='presentation'?'Presentation':'Teacher'):'Student';
window.addEventListener('message',e=>{if(e.origin!==location.origin)return;if(e.data?.type==='e-leap:runtime-context'&&e.data.context?.role){/* host role is already reflected in query; message retained for compatibility */}});
render();
})();
