(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const slides=$$('.slide'), total=slides.length; let current=1,lastAssessment=null;
function show(n){current=Math.max(1,Math.min(total,n));slides.forEach(s=>s.classList.toggle('active',+s.dataset.slide===current));$('#counter').textContent=`${current} / ${total}`;$('#bar').style.width=`${current/total*100}%`;$('#prev').disabled=current===1;$('#next').disabled=current===total;lastAssessment=null;window.scrollTo(0,0)}
$('#prev').onclick=()=>show(current-1);$('#next').onclick=()=>show(current+1);
function score(totalC,answered,correct){return{totalCount:totalC,answeredCount:answered,correctCount:correct,wrongCount:answered-correct,unansweredCount:totalC-answered,score:totalC?correct/totalC*100:null}}
function markButtonGroup(btns,answers){let a=0,c=0;btns.forEach(b=>{if(b.classList.contains('selected')){a++;const ok=answers.includes(b.dataset.v||b.textContent.trim());b.classList.toggle('is-correct',ok);b.classList.toggle('is-wrong',!ok);if(ok)c++}});return[a,c]}
$('#audienceChoices').onclick=e=>{if(e.target.tagName==='BUTTON')e.target.classList.toggle('selected')};
$$('.message-card .pick').forEach(b=>b.onclick=()=>{$$('.message-card .pick').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
$$('[data-cue]').forEach(x=>x.onclick=()=>x.classList.toggle('selected'));
$$('.analysis-grid button,.option-stack button,#diagnose button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));
$$('.classify-row').forEach(r=>r.onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('button',r).forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected');r.dataset.value=e.target.dataset.v});
$$('.mcq').forEach(r=>r.onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('button',r).forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected');r.dataset.value=e.target.dataset.v});
$$('#huntText [data-ok]').forEach(x=>x.onclick=()=>x.classList.toggle('selected'));
// structure order
const order=['Greeting','Opening','Body 1','Body 2','Closing','Ending'];let cur=['Body 1','Greeting','Closing','Opening','Ending','Body 2'];
function renderOrder(){const r=$('#structureOrder');r.innerHTML='';cur.forEach((t,i)=>{const d=document.createElement('div');d.className='reorder-item';d.dataset.value=t;d.innerHTML=`<span>${t}</span><span class="move"><button data-dir="-1">↑</button><button data-dir="1">↓</button></span>`;d.onclick=e=>{const dir=+e.target.dataset.dir;if(!dir)return;const j=i+dir;if(j<0||j>=cur.length)return;[cur[i],cur[j]]=[cur[j],cur[i]];renderOrder()};r.appendChild(d)})}renderOrder();
functionPanels();
function functionPanels(){const data={greeting:[['Hi Alex,',1],['Dear Sir or Madam,',0],['Hello Mary,',1]],opinion:[['I think…',1],['Personally, I think…',1],['It is hereby stated that…',0]],suggestion:[['Why not try…?',1],['What about visiting…?',1],['I strongly urge the implementation of…',0]],advice:[['If I were you, I’d…',1],['You could…',1],['It is recommended that you…',0]],closing:[['Hope to hear from you soon.',1],['Write back soon!',1],['I await your response at your earliest convenience.',0]]};let tab='greeting';const panel=$('#functionPanel');function draw(){panel.innerHTML=data[tab].map(([t,ok])=>`<label class="function-option" data-ok="${ok}"><input type="checkbox"> ${t}</label>`).join('');$$('.function-option',panel).forEach(x=>x.onclick=()=>x.classList.toggle('selected'))}draw();$('#functionTabs').onclick=e=>{if(e.target.tagName!=='BUTTON')return;tab=e.target.dataset.tab;$$('button',$('#functionTabs')).forEach(b=>b.classList.toggle('active',b===e.target));draw()}}
$('#ideaReason').onchange=$('#ideaDetail').onchange=()=>{if($('#ideaReason').value==='culture'&&$('#ideaDetail').value==='food')$('#builtIdea').textContent='You should definitely visit the Old Quarter because it’s a great place to experience local culture. You could also try some street food and visit the historical sites there.';else $('#builtIdea').textContent='Keep building: choose a reason and a detail that logically support the idea.'};
$$('.final-tabs button').forEach(b=>b.onclick=()=>{const id=b.dataset.final;$$('.final-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.final-panel').forEach(x=>x.classList.remove('active'));$('#final'+id[0].toUpperCase()+id.slice(1)).classList.add('active')});
$('#finalDraft').oninput=()=>{$('#wordCount').textContent=($('#finalDraft').value.trim().match(/\b[\w’'-]+\b/g)||[]).length};
function check(){const s=$(`.slide[data-slide="${current}"]`);let totalC=0,a=0,c=0;
 if(current===2){const btns=$$('button',$('#audienceChoices'));totalC=4;btns.forEach(b=>{const chosen=b.classList.contains('selected');const ok=['friend','cousin'].includes(b.dataset.v);if(chosen)a++;if(chosen&&ok)c++;b.classList.toggle('is-correct',chosen&&ok);b.classList.toggle('is-wrong',chosen&&!ok)});}
 else if(current===3){totalC=2;const pick=$('.message-card .pick.selected');if(pick){a++;if(pick.dataset.v==='A')c++;pick.classList.toggle('is-correct',pick.dataset.v==='A');pick.classList.toggle('is-wrong',pick.dataset.v!=='A')}const cues=$$('[data-cue].selected');if(cues.length){a++;c++;}$('#voiceFeedback').textContent=(pick?.dataset.v==='A'&&cues.length)?'Good: audience, contractions and conversational phrases all help create an informal tone.':''}
 else if([4,11,12,14].includes(current)){const rows=$$('.match-row',s);totalC=rows.length;rows.forEach(r=>{const v=$('select',r).value;if(v)a++;const ok=v===r.dataset.answer;if(ok)c++;r.classList.toggle('is-correct',ok&&!!v);r.classList.toggle('is-wrong',!!v&&!ok)})}
 else if(current===5){const bs=$$('.analysis-grid button');totalC=6;bs.forEach(b=>{if(b.classList.contains('selected')){a++;const ok=b.dataset.ok==='1';if(ok)c++;b.classList.toggle('is-correct',ok);b.classList.toggle('is-wrong',!ok)}})}
 else if(current===6){const bs=$$('#contentPoints button');totalC=4;bs.forEach(b=>{if(b.classList.contains('selected')){a++;const ok=b.dataset.ok==='1';if(ok)c++;b.classList.toggle('is-correct',ok);b.classList.toggle('is-wrong',!ok)}})}
 else if(current===7){const xs=$$('#huntText [data-ok]');totalC=xs.length;xs.forEach(x=>{if(x.classList.contains('selected')){a++;if(x.dataset.ok==='1')c++;x.classList.toggle('is-correct',x.dataset.ok==='1')}});$('#huntFeedback').textContent=c===totalC?'You found the key informal signals: personal greeting, contraction, apology and conversational linker.':''}
 else if(current===8){const rows=$$('.classify-row',s);totalC=rows.length;rows.forEach(r=>{const v=r.dataset.value||'';if(v)a++;const ok=v===r.dataset.answer;if(ok)c++;r.classList.toggle('is-correct',ok&&!!v);r.classList.toggle('is-wrong',!!v&&!ok)})}
 else if(current===9){const rows=$$('.mcq',s);totalC=rows.length;rows.forEach(r=>{const v=r.dataset.value||'';if(v)a++;const ok=v===r.dataset.answer;if(ok)c++;$$('button',r).forEach(b=>{b.classList.toggle('answer-correct',b.dataset.v===r.dataset.answer&&!!v);b.classList.toggle('answer-wrong',b.classList.contains('selected')&&!ok)})})}
 else if(current===10){totalC=6;a=6;c=cur.filter((x,i)=>x===order[i]).length;$$('.reorder-item').forEach((x,i)=>x.classList.toggle('is-correct',x.dataset.value===order[i]));if(c===6)$('#structureMap').classList.remove('hidden')}
 else if(current===13){totalC=2;const r=$('#ideaReason').value,d=$('#ideaDetail').value;if(r)a++;if(d)a++;if(r==='culture')c++;if(d==='food')c++;}
 else if(current===15){const opts=$$('.function-option',$('#functionPanel'));totalC=opts.length;opts.forEach(x=>{const chosen=x.classList.contains('selected');if(chosen)a++;if(chosen&&x.dataset.ok==='1')c++;x.classList.toggle('is-correct',chosen&&x.dataset.ok==='1');x.classList.toggle('is-wrong',chosen&&x.dataset.ok!=='1')})}
 else if(current===16){const sels=$$('select',s);totalC=sels.length;sels.forEach(x=>{if(x.value)a++;const ok=x.value===x.dataset.answer;if(ok)c++;x.classList.toggle('is-correct',ok&&!!x.value);x.classList.toggle('is-wrong',!!x.value&&!ok)})}
 else if(current===17){const bs=$$('#diagnose button');totalC=6;bs.forEach(b=>{if(b.classList.contains('selected')){a++;const ok=b.dataset.ok==='1';if(ok)c++;b.classList.toggle('is-correct',ok);b.classList.toggle('is-wrong',!ok)}})}
 else return false;lastAssessment=score(totalC,a,c);return true}
function reset(){const s=$(`.slide[data-slide="${current}"]`);$$('input',s).forEach(x=>{if(x.type==='checkbox'||x.type==='radio')x.checked=false;else x.value=''});$$('select',s).forEach(x=>x.value='');$$('textarea',s).forEach(x=>x.value='');$$('.selected,.is-correct,.is-wrong,.answer-correct,.answer-wrong,.answer',s).forEach(x=>x.classList.remove('selected','is-correct','is-wrong','answer-correct','answer-wrong','answer'));$$('[data-value]',s).forEach(x=>delete x.dataset.value);if(current===10){cur=['Body 1','Greeting','Closing','Opening','Ending','Body 2'];renderOrder();$('#structureMap').classList.add('hidden')}if(current===13)$('#builtIdea').textContent='';if(current===18){$('#repairModel').classList.remove('show');$('#repairModel').textContent=''}if(current===20){$('#wordCount').textContent='0'}lastAssessment=null;return true}
function reveal(){const s=$(`.slide[data-slide="${current}"]`);
 if(current===2){const b=$$('button',$('#audienceChoices')).find(x=>!x.dataset.rev&&['friend','cousin'].includes(x.dataset.v));if(!b)return false;b.classList.add('answer-correct');b.dataset.rev='1';return true}
 if(current===3){const p=$('.message-card .pick[data-v="A"]');if(!p.dataset.rev){p.classList.add('answer-correct');p.dataset.rev='1';return true}const c=$$('[data-cue]').find(x=>!x.dataset.rev);if(c){c.classList.add('answer');c.dataset.rev='1';return true}return false}
 if([4,11,12,14].includes(current)){const r=$$('.match-row',s).find(x=>!x.dataset.rev);if(!r)return false;$('select',r).value=r.dataset.answer;$('select',r).classList.add('answer-correct');r.dataset.rev='1';return true}
 if(current===5){const b=$$('.analysis-grid button').find(x=>x.dataset.ok==='1'&&!x.dataset.rev);if(!b)return false;b.classList.add('answer-correct');b.dataset.rev='1';return true}
 if(current===6){const b=$$('#contentPoints button').find(x=>x.dataset.ok==='1'&&!x.dataset.rev);if(!b)return false;b.classList.add('answer-correct');b.dataset.rev='1';return true}
 if(current===7){const x=$$('#huntText [data-ok]').find(x=>!x.dataset.rev);if(!x)return false;x.classList.add('answer');x.dataset.rev='1';return true}
 if(current===8){const r=$$('.classify-row',s).find(x=>!x.dataset.rev);if(!r)return false;const b=$$('button',r).find(x=>x.dataset.v===r.dataset.answer);b.classList.add('answer-correct');r.dataset.rev='1';return true}
 if(current===9){const r=$$('.mcq',s).find(x=>!x.dataset.rev);if(!r)return false;const b=$$('button',r).find(x=>x.dataset.v===r.dataset.answer);b.classList.add('answer-correct');r.dataset.rev='1';return true}
 if(current===10){cur=[...order];renderOrder();$('#structureMap').classList.remove('hidden');return true}
 if(current===13){if(!$('#ideaReason').value){$('#ideaReason').value='culture';return true}if(!$('#ideaDetail').value){$('#ideaDetail').value='food';$('#ideaDetail').onchange();return true}return false}
 if(current===15){const x=$$('.function-option',$('#functionPanel')).find(x=>x.dataset.ok==='1'&&!x.dataset.rev);if(!x)return false;x.classList.add('answer-correct');x.dataset.rev='1';return true}
 if(current===16){const x=$$('select',s).find(x=>!x.dataset.rev);if(!x)return false;x.value=x.dataset.answer;x.classList.add('answer-correct');x.dataset.rev='1';return true}
 if(current===17){const b=$$('#diagnose button').find(x=>x.dataset.ok==='1'&&!x.dataset.rev);if(!b)return false;b.classList.add('answer-correct');b.dataset.rev='1';return true}
 if(current===18){$('#repairModel').textContent='Suggested improvement: Why not visit the Old Quarter? It’s a great place to experience local culture, and you could try some street food and visit the historical sites there.';$('#repairModel').classList.add('show');return true}
 if(current===19){const fields=$$('[data-plan]',s);const suggestions={opening:'Great to hear you’re coming! I can’t wait to see you.',body1:'Old Quarter → local culture → street food / historical sites',body2:'light clothes + comfortable shoes → warm days / lots of walking; light jacket → cooler evenings',closing:'Hope to hear from you soon. Write back when you know your dates!'};const f=fields.find(x=>!x.dataset.rev);if(!f)return false;f.value=suggestions[f.dataset.plan];f.dataset.rev='1';return true}
 return false}
function snapshot(){const s=$(`.slide[data-slide="${current}"]`);return{slide:current,fields:$$('input,select,textarea',s).map((x,i)=>({name:x.name||x.id||x.dataset.plan||`f${i}`,value:(x.type==='checkbox'||x.type==='radio')?(x.checked?x.value:''):x.value})).filter(x=>x.value),selected:$$('.selected',s).map(x=>x.textContent.trim())}}
function submit(){const response=snapshot();if(!response.fields.length&&!response.selected.length&&current!==20)return false;const payload={type:'e-leap:learning-event',event:{eventId:`informal-l1-${Date.now()}`,eventType:'response.submitted',resourceId:'res-adv-writing-letter-email-writing-informal-l01',activityId:`informal-l1-s${String(current).padStart(2,'0')}`,occurredAt:new Date().toISOString(),context:{role:new URLSearchParams(location.search).get('eleapRole')||'student'},payload:{response,grading:lastAssessment}}};try{parent.postMessage(payload,location.origin)}catch(_){}return true}
function caps(){const assess=$(`.slide[data-slide="${current}"]`)?.dataset.assess==='true';return{check:assess,reset:true,reveal:[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19].includes(current),submit:[18,19,20].includes(current)||assess,score:assess,assessable:assess}}
$('#checkBtn').onclick=()=>check();$('#resetBtn').onclick=()=>reset();$('#revealBtn').onclick=()=>reveal();
window.ELEAP_LESSON_HOST_API={getMode(){return document.documentElement.dataset.eleapMode||'student'},setMode(m){document.documentElement.dataset.eleapMode=m;return true},getActivityState(){return{activityId:`informal-l1-s${String(current).padStart(2,'0')}`,response:snapshot(),assessment:lastAssessment,capabilities:caps()}},command(action){if(action==='check')return check();if(action==='reset')return reset();if(action==='reveal')return reveal();if(action==='submit')return submit();return false}};
const p=new URLSearchParams(location.search);if(p.get('eleapHosted')==='1'){document.documentElement.dataset.eleapHosted='1';document.documentElement.dataset.eleapRole=p.get('eleapRole')||'guest';document.documentElement.dataset.eleapMode=p.get('eleapMode')||'normal';try{parent.postMessage({type:'e-leap:request-runtime-context'},location.origin)}catch(_){}}window.addEventListener('message',e=>{if(e.origin!==location.origin)return;if(e.data?.type==='e-leap:runtime-context'){document.documentElement.dataset.eleapRole=e.data.context.role||'guest';document.documentElement.dataset.eleapMode=e.data.context.mode||'normal'}});show(1);
})();