const DATA_URL='../../../../../courses/life-intermediate/unit-01/lesson-03/lesson.json';
const screenEl=document.getElementById('screen'),counter=document.getElementById('counter'),bar=document.getElementById('bar'),prev=document.getElementById('prev'),next=document.getElementById('next');
let lesson=null,index=0,revealed=false,lastAssessment=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>String(v??'').trim().toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const mediaPath=p=>String(p||'').replace(/^PRIVATE_MEDIA\//,'/media-private/');
const acceptable=(given,answer)=>{const g=norm(given),a=norm(answer);if(!g)return false;if(g===a)return true;const alts=String(answer||'').split(/\s*\/\s*|\s*;\s*/).map(norm).filter(Boolean);return alts.some(x=>g===x||g.includes(x)||x.includes(g));};
function assessable(s){return ['quick-choice','challenge-cards','speaker-match'].includes(s?.type);}
function mediaHTML(s){if(s?.media?.audio)return `<div class="media-card"><audio controls preload="metadata" src="${esc(mediaPath(s.media.audio))}"></audio></div>`;if(s?.media?.video)return `<div class="media-card"><video controls playsinline preload="metadata" src="${esc(mediaPath(s.media.video))}"></video></div>`;return ''}
function answers(s){if(s.type==='quick-choice')return s.answer?[s.answer]:[];if(Array.isArray(s.items))return s.items.map(x=>x.answer);return []}
function render(){const s=lesson.screens[index];revealed=false;lastAssessment=null;document.body.dataset.screen=String(index+1);counter.textContent=`${index+1} / ${lesson.screens.length}`;bar.style.width=`${((index+1)/lesson.screens.length)*100}%`;prev.disabled=index===0;next.disabled=index===lesson.screens.length-1;screenEl.className='screen';screenEl.innerHTML=buildScreen(s);bindScreen(s);notifyContext();}
function buildScreen(s){const head=`<div class="stage">${esc(s.stage||'')}</div><h2>${esc(s.title||'')}</h2>${s.instruction?`<p class="instruction">${esc(s.instruction)}</p>`:''}`;if(s.type==='cover-modern')return `<div class="cover-card"><div class="stage">${esc(s.stage||'')}</div><h1>${esc(s.title)}</h1><p class="instruction">${esc(s.instruction||'')}</p><div class="cover-list">${(s.items||[]).map(x=>`<div>${esc(x)}</div>`).join('')}</div></div>`;if(s.type==='aims-horizontal')return `${head}<div class="aim-grid">${(s.groups||[]).map(g=>`<article class="aim-card"><h3>${esc(g.heading)}</h3><ul>${(g.items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('')}</div>`;if(s.type==='quick-choice')return `${head}${mediaHTML(s)}<div class="panel" style="padding:22px"><div class="card-q">${esc(s.question||'Choose one')}</div><div class="choice-grid">${(s.options||[]).map((o,i)=>`<button class="choice" type="button" data-choice="${i}" data-value="${esc(o)}">${esc(o)}</button>`).join('')}</div>${s.interactionPrompt?`<p class="mini-note">${esc(s.interactionPrompt)}</p>`:''}<div class="answer">Answer: ${esc(s.answer||'Open response')}</div><div class="feedback" id="feedback"></div></div>`;if(s.type==='challenge-cards')return `${head}${mediaHTML(s)}<div class="cards">${(s.items||[]).map((it,i)=>`<article class="card"><div class="card-q">${i+1}. ${esc(it.question)}</div><input class="short-input" data-response="${i}" autocomplete="off" aria-label="Answer ${i+1}"><div class="answer">${esc(it.answer)}</div></article>`).join('')}</div><div class="feedback" id="feedback"></div>`;if(s.type==='speaker-match')return `${head}${mediaHTML(s)}${s.example?`<div class="support-card"><b>Listening tip</b><p>${esc(s.example)}</p></div>`:''}<div class="cards" style="margin-top:16px">${(s.items||[]).map((it,i)=>`<article class="card"><div class="card-q">${esc(it.prompt)}</div><input class="short-input" data-response="${i}" autocomplete="off"><div class="answer">${esc(it.answer)}</div></article>`).join('')}</div><div class="feedback" id="feedback"></div>`;if(s.type==='questions')return `${head}<div class="question-list">${(s.questions||[]).map((q,i)=>`<div><b>${i+1}.</b> ${esc(q)}</div>`).join('')}</div>`;if(s.type==='speaking-prompt')return `${head}<div class="support-card"><ul>${(s.support||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;if(s.type==='assignment')return `${head}<div class="assignment"><span class="badge">${esc(s.label||'Homework')}</span><p>${esc(s.instruction||'')}</p>${s.footer?`<p class="mini-note">${esc(s.footer)}</p>`:''}</div>`;return `${head}<div class="panel" style="padding:20px">${esc(JSON.stringify(s))}</div>`}
function bindScreen(s){screenEl.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{screenEl.querySelectorAll('[data-choice]').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');lastAssessment=null;});screenEl.querySelectorAll('[data-response]').forEach(i=>i.addEventListener('input',()=>{i.classList.remove('correct','wrong');lastAssessment=null;}));}
function collectResponse(s){if(s.type==='quick-choice')return screenEl.querySelector('.choice.selected')?.dataset.value||'';if(['challenge-cards','speaker-match'].includes(s.type))return [...screenEl.querySelectorAll('[data-response]')].map(x=>x.value);return null}
function compute(s,{paint=false}={}){const key=answers(s);if(!key.length)return null;let correct=0,answered=0;const response=collectResponse(s);if(s.type==='quick-choice'){const chosen=String(response||'');if(chosen)answered=1;const ok=acceptable(chosen,key[0]);if(ok)correct=1;if(paint){const selected=screenEl.querySelector('.choice.selected');if(selected)selected.classList.add(ok?'correct':'wrong');}}else{const vals=Array.isArray(response)?response:[];vals.forEach((v,i)=>{if(String(v||'').trim())answered++;const ok=acceptable(v,key[i]);if(ok)correct++;if(paint){const inp=screenEl.querySelector(`[data-response="${i}"]`);if(inp&&String(v||'').trim())inp.style.borderColor=ok?'#2f7a55':'#bb635d';}})}const total=key.length,unanswered=Math.max(0,total-answered),score=total?correct/total:0;return {totalCount:total,correctCount:correct,answeredCount:answered,unansweredCount:unanswered,score};}
function check(){const s=lesson.screens[index];const a=compute(s,{paint:true});lastAssessment=a;const fb=document.getElementById('feedback');if(fb&&a){fb.className='feedback '+(a.correctCount===a.totalCount?'ok':'bad');fb.textContent=`${a.correctCount}/${a.totalCount} correct · ${a.unansweredCount} unanswered`; }return !!a}
function reset(){const s=lesson.screens[index];screenEl.classList.remove('show-answer');revealed=false;screenEl.querySelectorAll('[data-choice]').forEach(x=>x.classList.remove('selected','correct','wrong'));screenEl.querySelectorAll('[data-response]').forEach(x=>{x.value='';x.style.borderColor='';});const fb=document.getElementById('feedback');if(fb)fb.textContent='';lastAssessment=null;return assessable(s)}
function reveal(){const s=lesson.screens[index];if(!answers(s).length)return false;revealed=!revealed;screenEl.classList.toggle('show-answer',revealed);return true}
function submit(){const s=lesson.screens[index];const r=collectResponse(s);if(Array.isArray(r))return r.some(x=>String(x||'').trim());return Boolean(String(r||'').trim())}
function state(){const s=lesson?.screens?.[index];if(!s)return null;const can=assessable(s);const a=lastAssessment||compute(s);return {activityId:`life-u01-l03-${s.id}`,capabilities:{check:can,reset:can,reveal:answers(s).length>0,submit:can,score:can,assessable:can},assessment:can?a:null,response:collectResponse(s)} }
window.ELEAP_LESSON_HOST_API={command(action){if(action==='check')return check();if(action==='reset')return reset();if(action==='reveal')return reveal();if(action==='submit')return submit();return false},getActivityState(){return state()}};
function notifyContext(){try{parent.postMessage({type:'e-leap:lesson-screen',screenNumber:index+1,activityId:`life-u01-l03-${lesson.screens[index].id}`},location.origin)}catch(_){}}
prev.onclick=()=>{if(index>0){index--;render()}};next.onclick=()=>{if(index<lesson.screens.length-1){index++;render()}};window.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&index<lesson.screens.length-1){index++;render()}if(e.key==='ArrowLeft'&&index>0){index--;render()}});
fetch(DATA_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Lesson data unavailable (${r.status})`);return r.json()}).then(d=>{lesson=d;render()}).catch(e=>{screenEl.innerHTML=`<div class="panel" style="padding:24px"><h2>Lesson could not load</h2><p>${esc(e.message)}</p></div>`});