const DATA_URL='../../../../../courses/life-intermediate/unit-01/lesson-03/lesson.json';
const RESOURCE_ID='res-life-u01-l03';
const SIGN_ENDPOINT='https://xfisojqahojcsfrjjxab.supabase.co/functions/v1/get-media-url';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const screen=$('#screen'),counter=$('#counter'),bar=$('#bar'),prev=$('#prev'),next=$('#next');
let lesson=null,index=0,revealArmed=false,selectedChip=null,currentTab=0,formPlaced=new Map(),runtimeContext={};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>String(v??'').trim().toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const mediaKey=p=>String(p||'').replace(/^PRIVATE_MEDIA\//,'');
const localMedia=p=>'/media-private/'+mediaKey(p);
const query=new URLSearchParams(location.search);
const currentRole=()=>runtimeContext.role||query.get('eleapRole')||localStorage.getItem('e-leap-preview-role')||'guest';
const assignmentId=()=>runtimeContext.assignmentId||query.get('assignmentId')||null;
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
function post(type,payload={}){try{parent.postMessage({type,...payload},location.origin)}catch{}}
function eventContext(){return {role:currentRole(),participantId:runtimeContext.participantId||query.get('participantId')||null,sessionId:runtimeContext.sessionId||query.get('sessionId')||null,classId:runtimeContext.classId||query.get('classId')||null,studentId:runtimeContext.studentId||null,assignmentId:assignmentId()}}
function emitLearningEvent(eventType,s,response=null,extra={}){const evt={eventId:uid(),eventType,occurredAt:new Date().toISOString(),resourceId:RESOURCE_ID,activityId:s.id,context:eventContext(),payload:{response,...extra}};try{const k='e-leap-learning-events',rows=JSON.parse(localStorage.getItem(k)||'[]');rows.push(evt);localStorage.setItem(k,JSON.stringify(rows.slice(-600)))}catch{}post('e-leap:learning-event',{event:evt});return evt}
async function signedMedia(raw){try{const r=await fetch(SIGN_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:mediaKey(raw)})});if(!r.ok)return'';const d=await r.json();return d?.url||''}catch{return''}}
async function resolveMedia(raw){const local=localMedia(raw);try{const r=await fetch(local,{method:'GET',headers:{Range:'bytes=0-1'},cache:'no-store'});if(r.ok||r.status===206)return local}catch{}return await signedMedia(raw)}
function mediaCard(raw,kind,cls=''){if(!raw)return'';return `<div class="media-card ${cls}" data-media-kind="${kind}" data-media-raw="${esc(raw)}"><div class="media-slot"><div class="media-state">Loading ${kind}…</div></div></div>`}
async function hydrateMedia(){for(const card of $$('[data-media-raw]',screen)){const raw=card.dataset.mediaRaw,kind=card.dataset.mediaKind,slot=$('.media-slot',card);if(!slot)continue;slot.innerHTML=`<div class="media-state">Loading ${kind}…</div>`;const url=await resolveMedia(raw);if(!url){slot.innerHTML=`<div class="media-error"><b>${kind==='audio'?'Audio':'Video'} unavailable.</b><button type="button" class="retry-media">Retry</button></div>`;$('.retry-media',slot)?.addEventListener('click',hydrateMedia);continue}if(kind==='audio')slot.innerHTML=`<audio controls preload="metadata" src="${esc(url)}"></audio><div class="media-state">Audio ready</div>`;else slot.innerHTML=`<video controls playsinline preload="metadata" src="${esc(url)}"></video><div class="media-state">Video ready</div>`;const el=$(kind,slot);el?.addEventListener('error',async()=>{const fallback=await signedMedia(raw);if(fallback&&fallback!==el.src){el.src=fallback;el.load()}else $('.media-state',slot).textContent='Media could not play. Tap Retry or refresh Preview.'},{once:true})}}
function head(s){return `<div class="stage">${esc(s.stage||'')}</div><h2>${esc(s.title||'')}</h2>${s.instruction?`<p class="instruction">${esc(s.instruction)}</p>`:''}`}
function responseBox(i,placeholder='Type your answer here',cls=''){return `<div class="response-box ${cls}" data-response-box="${esc(i)}"><input class="response-input" data-response="${esc(i)}" placeholder="${esc(placeholder)}" autocomplete="off"><small class="response-hint">${placeholder==='Drop your answer here'?'Drop your answer here.':''}</small></div>`}
function submitBar(label='Submit your answers'){return `<div class="activity-submit"><button type="button" class="submit-btn">${esc(label)}</button><span class="submit-status"></span></div>`}
function inlineReveal(box,text){if(!box)return;box.classList.remove('wrong','right','reveal-ready');box.classList.add('answer-mode');box.innerHTML=`<div class="inline-correct">${esc(text)}</div>`}
function photo(url,caption='',cls=''){return `<figure class="park-photo ${cls}"><img src="${esc(url)}" alt="Park Güell in Barcelona" loading="eager">${caption?`<figcaption>${esc(caption)}</figcaption>`:''}</figure>`}
function sectionCover(s){const bg=s.visual==='park'&&s.photo?`style="--hero-photo:url('${esc(s.photo)}')"`:'';return `<div class="section-hero ${s.visual==='park'?'park-cover':'forms-cover'}" ${bg}><div class="hero-overlay"><div class="unit-mega">${esc(s.stage)}</div><h1>${esc(s.title)}</h1><p>${esc(s.subtitle||'')}</p>${s.caption?`<small>${esc(s.caption)}</small>`:''}</div></div>`}
function buildReview(s){return `${head(s)}<div class="review-grid">${s.items.map((x,i)=>`<article class="review-card"><div class="q">${i+1}. ${esc(x.prompt)}</div>${responseBox(i,'Type the advice here','long-response')}<span class="answer-source" hidden>${esc(x.answer)}</span></article>`).join('')}</div>${submitBar()}`}
function formIcon(type){const icons=['✈','✚','🎓','▣'];return `<div class="form-paper"><span class="form-icon">${icons[type]||'▤'}</span><i></i><i></i><i></i><i></i></div>`}
function buildGallery(s){return `${head(s)}<div class="form-gallery">${s.items.map((x,i)=>`<article class="form-sample">${formIcon(i)}<div class="form-clue"><b>${esc(x.prompt)}</b><span>${esc(x.hint)}</span></div>${responseBox(i,'Type the form name here')}<span class="answer-source" hidden>${esc(x.answer)}</span></article>`).join('')}</div><div class="discussion-card"><b>After checking:</b> Which of these forms have you filled in before? What was the occasion?</div>${submitBar()}`}
function buildMcq(s){return `${head(s)}<div class="mcq-stack">${s.items.map((x,i)=>`<article class="mcq-card" data-mcq="${i}"><div class="q">${i+1}. ${esc(x.prompt)}</div><div class="mcq-options">${x.options.map(o=>`<button type="button" data-value="${esc(o)}">${esc(o)}</button>`).join('')}</div></article>`).join('')}</div>${submitBar()}`}
function dragBank(bank){return `<div class="drag-bank">${bank.map(x=>{const key=typeof x==='string'?x:x.key,text=typeof x==='string'?x:x.text;return `<button type="button" draggable="true" class="drag-chip" data-chip="${esc(key)}"><b>${esc(key)}</b><span>${esc(text)}</span></button>`}).join('')}</div>`}
function dropTarget(attrs='',hint='Drop your answer here.'){return `<div class="drop-box response-box" ${attrs}><span class="drop-value"></span><small class="response-hint">${esc(hint)}</small></div>`}
function buildDragMatch(s){return `${head(s)}${dragBank(s.bank)}<div class="match-rows">${s.items.map((x,i)=>`<div class="match-row"><div class="match-prompt"><b>${i+1}.</b><span>${esc(x.prompt)}</span></div>${dropTarget(`data-drop="${i}" data-answer="${esc(x.answer)}" data-answer-text="${esc(x.answerText||x.answer)}"`)}</div>`).join('')}</div>${submitBar()}`}
function tabButtons(tabs){return `<div class="tabs">${tabs.map((t,i)=>`<button type="button" data-tab="${i}" class="${i===currentTab?'active':''}">${esc(t.label)}</button>`).join('')}</div>`}
function buildTabs(s){const tab=s.tabs[currentTab]||s.tabs[0];return `${head(s)}${s.media?.audio?mediaCard(s.media.audio,'audio'):''}${tabButtons(s.tabs)}<div class="tab-panel">${tab.items.map((x,i)=>`<article class="tab-question"><div class="q">${esc(x.prompt)}</div>${responseBox(i)}<span class="answer-source" hidden>${esc(x.answer)}</span></article>`).join('')}</div>${submitBar()}`}
function buildFormBuilder(s){const slots=8;return `${head(s)}${dragBank(s.bank.map((x,i)=>({key:String.fromCharCode(65+i),text:x})))}<div class="builder-form">${Array.from({length:slots},(_,i)=>`<div class="builder-field">${dropTarget(`data-form-slot="${i}" data-suggested="${esc(s.required?.[i]||'')}"`,'Drop a heading here.')}<input class="field-detail" data-detail="${i}" placeholder="Add sample information" disabled></div>`).join('')}</div><div class="partner-check">${s.checkQuestions.map(q=>`<span>${esc(q)}</span>`).join('')}</div>${submitBar('Submit form design')}`}
function parkLead(s){return `${head(s)}<div class="park-layout">${photo(s.photo,s.caption,'real-photo')}<div class="park-questions"><div class="elicit-box"><b>Warm-up from the photo</b>${(s.elicitation||[]).map(x=>`<span>• ${esc(x)}</span>`).join('')}</div>${s.questions.map((q,i)=>`<article><div class="q">${i+1}. ${esc(q)}</div>${responseBox(i)}</article>`).join('')}${submitBar()}</div></div>`}
function orderAnswerMap(s){const m={};s.answerOrder.forEach((key,pos)=>m[key]=String(pos+1));return m}
function buildVideoOrder(s){const amap=orderAnswerMap(s);return `${head(s)}<div class="video-split"><div class="video-left">${mediaCard(s.media.video,'video','big-video')}</div><div class="video-task-scroll"><div class="scene-list">${s.choices.map(x=>`<article class="scene-row"><div class="scene-copy"><b>${esc(x.key)}.</b><span>${esc(x.text)}</span></div>${responseBox(x.key,'Type 1–7','number-response')}<span class="answer-source" hidden>${esc(amap[x.key])}</span></article>`).join('')}</div>${submitBar()}</div></div>`}
function buildVideoNotes(s){return `${head(s)}<div class="video-split"><div class="video-left">${mediaCard(s.media.video,'video','big-video')}</div><div class="video-task-scroll notes-scroll">${s.rows.map((r,i)=>`<article class="visitor-row" data-row="${i}"><div class="visitor-head"><b>${esc(r.person)}</b><button type="button" class="evidence-btn" data-start="${r.start}" data-end="${r.end}">▶ Play evidence</button></div><label>Student A · When do you come to the park?${responseBox(`${i}-a`,'Type your notes here')}</label><span class="answer-source answer-a" hidden>${esc(r.a)}</span><label>Student B · Why do you like coming to the park?${responseBox(`${i}-b`,'Type your notes here')}</label><span class="answer-source answer-b" hidden>${esc(r.b)}</span></article>`).join('')}${submitBar()}</div></div>`}
function roleplay(s){return `${head(s)}<div class="role-grid"><div class="model-box"><h3>Model</h3>${s.model.map(x=>`<p>${esc(x)}</p>`).join('')}</div><div class="frames-box"><h3>Useful language</h3>${s.frames.map(x=>`<div>${esc(x)}</div>`).join('')}</div></div>`}
function shortCheck(s){return `${head(s)}<div class="check-grid">${s.items.map((x,i)=>`<article><div class="q">${i+1}. ${esc(x.prompt)}</div>${responseBox(i)}<span class="answer-source" hidden>${esc(x.answer)}</span></article>`).join('')}</div>${submitBar()}`}
function homework(s){const role=currentRole(),asId=assignmentId();return `${head(s)}<div class="deadline-banner" id="deadlineBanner">${esc(s.deadlineLabel)}</div><div class="blank-homework-form"><h3>NEW STUDENT INFORMATION FORM</h3><p>Write each heading yourself, then add sample information. The form starts completely blank.</p>${Array.from({length:8},(_,i)=>`<div class="blank-form-row"><input data-hw-heading="${i}" placeholder="Information heading"><input data-hw-value="${i}" placeholder="Sample information"></div>`).join('')}</div><div class="homework-actions">${role==='student'?`<button type="button" class="submit-btn" data-save-homework>${asId?'Submit Homework':'Save practice response'}</button>`:''}${['teacher','admin'].includes(role)?'<button type="button" class="assign-btn" data-assign-homework>Assign Homework</button>':''}<span class="submit-status"></span></div><div class="workflow-note"><b>Homework flow:</b> Teacher chooses class + deadline → students receive it in Assignments → submissions are grouped by assignment/class → Teacher marks in Submissions/Marking Center → feedback/score is released back to each student.</div>`}
function thank(s){return `<div class="thank-card" style="--thank-photo:url('${esc(s.photo||'')}')"><div class="thank-overlay"><div class="stage">${esc(s.stage)}</div><h1>${esc(s.title)}</h1><p>${esc(s.subtitle)}</p></div></div>`}
function build(s){if(s.type==='cover')return `<div class="main-cover"><div><div class="stage">${esc(s.stage)}</div><h1>${esc(s.title)}</h1><p>${esc(s.subtitle)}</p></div></div>`;if(s.type==='aims')return `${head(s)}<div class="aim-grid">${s.groups.map(g=>`<article><h3>${esc(g.heading)}</h3>${g.items.map(x=>`<p>✓ ${esc(x)}</p>`).join('')}</article>`).join('')}</div>`;if(s.type==='review-match')return buildReview(s);if(s.type==='section-cover')return sectionCover(s);if(s.type==='form-gallery')return buildGallery(s);if(s.type==='mcq-set')return buildMcq(s);if(s.type==='drag-match')return buildDragMatch(s);if(s.type==='tab-questions'||s.type==='listening-tabs')return buildTabs(s);if(s.type==='form-builder')return buildFormBuilder(s);if(s.type==='park-leadin')return parkLead(s);if(s.type==='video-order')return buildVideoOrder(s);if(s.type==='video-notes')return buildVideoNotes(s);if(s.type==='roleplay')return roleplay(s);if(s.type==='short-check')return shortCheck(s);if(s.type==='reflection')return `${head(s)}<div class="reflection-grid">${s.items.map(x=>`<button type="button">✓ ${esc(x)}</button>`).join('')}</div>`;if(s.type==='homework-form')return homework(s);if(s.type==='thank-you')return thank(s);return `${head(s)}`}
function pickChip(chip){$$('.drag-chip').forEach(c=>c.classList.remove('picked'));chip.classList.add('picked');selectedChip={key:chip.dataset.chip,text:$('span',chip)?.textContent||chip.dataset.chip}}
function placeInDrop(drop,key,text){drop.dataset.value=key;drop.classList.add('filled');$('.drop-value',drop).textContent=`${key} · ${text}`;$('.response-hint',drop)?.setAttribute('hidden','')}
function placeChip(d,key,text){if(d.hasAttribute('data-form-slot')){d.dataset.value=text;d.dataset.key=key;d.classList.add('filled');$('.drop-value',d).textContent=text;$('.response-hint',d)?.setAttribute('hidden','');d.parentElement.querySelector('.field-detail').disabled=false;formPlaced.set(Number(d.dataset.formSlot),text)}else placeInDrop(d,key,text)}
function bindDnD(){$$('.drag-chip').forEach(ch=>{ch.addEventListener('click',()=>pickChip(ch));ch.addEventListener('dragstart',e=>{pickChip(ch);e.dataTransfer.setData('text/plain',ch.dataset.chip)})});$$('[data-drop],[data-form-slot]').forEach(d=>{d.addEventListener('dragover',e=>e.preventDefault());d.addEventListener('drop',e=>{e.preventDefault();const key=e.dataTransfer.getData('text/plain');const ch=$(`.drag-chip[data-chip="${CSS.escape(key)}"]`);if(ch)placeChip(d,key,$('span',ch)?.textContent||key)});d.addEventListener('click',()=>{if(selectedChip&&!revealArmed)placeChip(d,selectedChip.key,selectedChip.text)})})}
function collect(s){if(s.type==='mcq-set')return $$('.mcq-card').map(c=>$('.mcq-options button.selected',c)?.dataset.value||'');if(s.type==='drag-match')return $$('[data-drop]').map(d=>d.dataset.value||'');if(s.type==='video-order')return s.choices.map(x=>$(`[data-response="${x.key}"]`)?.value||'');if(s.type==='form-builder')return $$('[data-form-slot]').map((d,i)=>({heading:d.dataset.value||'',value:$(`[data-detail="${i}"]`)?.value||''}));if(s.type==='video-notes')return s.rows.flatMap((r,i)=>[{id:`${i}-a`,value:$(`[data-response="${i}-a"]`)?.value||''},{id:`${i}-b`,value:$(`[data-response="${i}-b"]`)?.value||''}]);if(s.type==='homework-form')return Array.from({length:8},(_,i)=>({heading:$(`[data-hw-heading="${i}"]`)?.value||'',value:$(`[data-hw-value="${i}"]`)?.value||''}));return $$('[data-response]').map(i=>i.value)}
function answerKeys(s){if(s.type==='mcq-set')return s.items.map(x=>x.answer);if(s.type==='drag-match')return s.items.map(x=>x.answer);if(s.type==='video-order'){const m=orderAnswerMap(s);return s.choices.map(x=>m[x.key])}if(s.type==='review-match'||s.type==='form-gallery'||s.type==='short-check')return s.items.map(x=>x.answer);if(s.type==='tab-questions'||s.type==='listening-tabs')return (s.tabs[currentTab]?.items||[]).map(x=>x.answer);if(s.type==='video-notes')return s.rows.flatMap(r=>[r.a,r.b]);return[]}
function assessment(s){const keys=answerKeys(s),responses=collect(s);if(!keys.length)return {assessable:false,totalCount:0,correctCount:0,answeredCount:0,unansweredCount:0,score:null};let correct=0,answered=0;keys.forEach((k,i)=>{const v=typeof responses[i]==='object'?responses[i]?.value:responses[i];if(String(v||'').trim())answered++;const alts=String(k||'').split(/\s*\/\s*|\s*;\s*/).map(norm).filter(Boolean);const nv=norm(v);if(nv&&alts.some(a=>nv===a||nv.includes(a)||a.includes(nv)))correct++});return {assessable:true,totalCount:keys.length,correctCount:correct,answeredCount:answered,unansweredCount:keys.length-answered,score:keys.length?correct/keys.length:0}}
function paintCheck(s){const keys=answerKeys(s);if(!keys.length)return;$$('.response-box').forEach((box,i)=>{const v=$('.response-input',box)?.value??box.dataset.value??'',k=keys[i];if(k==null)return;const nv=norm(v),ok=nv&&String(k).split(/\s*\/\s*|\s*;\s*/).map(norm).some(a=>nv===a||nv.includes(a)||a.includes(nv));box.classList.remove('right','wrong');if(String(v).trim())box.classList.add(ok?'right':'wrong')});if(s.type==='mcq-set'){$$('.mcq-card').forEach((card,i)=>{const selected=$('.mcq-options button.selected',card);if(selected)selected.classList.add(norm(selected.dataset.value)===norm(keys[i])?'right':'wrong')})}}
async function doSubmit(s){const response=collect(s),g=assessment(s);emitLearningEvent('response.submitted',s,response,{grading:g,tab:currentTab});const st=$('.submit-status');if(st){st.textContent='Submitted ✓ · Teacher can review this in Responses';setTimeout(()=>st.textContent='',2200)}const asId=assignmentId();if(s.type==='homework-form'&&currentRole()==='student'&&asId){try{const r=await fetch('/api/research/submissions',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({assignmentId:asId,response:{form:response}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Homework submission failed');if(st)st.textContent='Homework submitted ✓'}catch(e){if(st)st.textContent=e.message}}return true}
function revealCurrent(s){revealArmed=true;document.body.classList.add('reveal-armed');if(s.type==='mcq-set'){$$('.mcq-card').forEach((c,i)=>$$('.mcq-options button',c).forEach(b=>{if(norm(b.dataset.value)===norm(s.items[i].answer))b.classList.add('correct')}));return true}$$('.response-box,[data-drop],[data-form-slot]').forEach(b=>b.classList.add('reveal-ready'));return true}
function revealTarget(el,s){if(!revealArmed)return false;if(el.matches('[data-drop]')){const i=Number(el.dataset.drop),it=s.items[i];inlineReveal(el,`${it.answer} · ${it.answerText||it.answer}`);return true}if(el.matches('[data-form-slot]')){const suggested=el.dataset.suggested||'Possible heading';inlineReveal(el,suggested?`Suggested: ${suggested}`:'Choose a clear information heading');return true}if(s.type==='video-order'){const card=el.closest('.scene-row');const src=card?.querySelector('.answer-source');if(src){inlineReveal(el,src.textContent);return true}}if(s.type==='video-notes'){const key=el.dataset.responseBox,row=el.closest('.visitor-row'),src=key?.endsWith('-a')?$('.answer-a',row):$('.answer-b',row);if(src){inlineReveal(el,src.textContent);return true}}const parent=el.closest('article,.review-card,.form-sample,.tab-question'),src=parent?.querySelector('.answer-source');if(src){inlineReveal(el,src.textContent);return true}return false}
function bind(s){$$('.mcq-options button').forEach(b=>b.onclick=()=>{const p=b.closest('.mcq-options');$$('button',p).forEach(x=>x.classList.remove('selected','right','wrong'));b.classList.add('selected')});$$('[data-tab]').forEach(b=>b.onclick=()=>{currentTab=Number(b.dataset.tab);const keep=currentTab;screen.innerHTML=build(s);currentTab=keep;bind(s);hydrateMedia()});bindDnD();$$('.response-box').forEach(b=>b.addEventListener('click',e=>{if(e.target.matches('input')&&!revealArmed)return;revealTarget(b,s)}));$$('.submit-btn:not([data-save-homework])').forEach(b=>b.onclick=()=>doSubmit(s));$$('.reflection-grid button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));$$('.evidence-btn').forEach(b=>b.onclick=()=>{const v=$('video',screen);if(!v||!v.src){b.textContent='Video not ready';return}const start=Number(b.dataset.start||0),end=Number(b.dataset.end||0);try{v.currentTime=start;v.play();b.textContent='Playing…';const stop=()=>{if(v.currentTime>=end||v.paused){if(v.currentTime>=end)v.pause();v.removeEventListener('timeupdate',stop);b.textContent='▶ Play evidence'}};v.addEventListener('timeupdate',stop)}catch{b.textContent='Try again'}});$('[data-save-homework]')?.addEventListener('click',()=>doSubmit(s));$('[data-assign-homework]')?.addEventListener('click',()=>assignHomework(s))}
async function assignHomework(s){if(!['teacher','admin'].includes(currentRole()))return;let data;try{data=await fetch('/api/research/classes',{credentials:'same-origin'}).then(r=>r.json())}catch{}const classes=(data?.classes||[]).filter(c=>c.status!=='archived');if(!classes.length){alert('Create a class first.');return}const modal=document.createElement('div');modal.className='assignment-modal';modal.innerHTML=`<div class="assignment-dialog"><h3>Assign Homework</h3><p>No class is preselected. Choose the class for this assignment.</p><label>Class<select id="ahClass"><option value="">Choose a class…</option>${classes.map(c=>`<option value="${esc(c.class_id)}">${esc(c.class_name)}</option>`).join('')}</select></label><label>Deadline<input id="ahDeadline" type="datetime-local" value="2026-10-12T20:00"></label><label>Attempt limit<input id="ahLimit" type="number" min="1" value="1"></label><div><button data-cancel>Cancel</button><button class="submit-btn" data-create>Assign</button></div><p class="assign-status"></p></div>`;document.body.append(modal);$('[data-cancel]',modal).onclick=()=>modal.remove();$('[data-create]',modal).onclick=async()=>{const classId=$('#ahClass',modal).value;if(!classId){$('.assign-status',modal).textContent='Choose a class.';return}const deadline=new Date($('#ahDeadline',modal).value);if(Number.isNaN(deadline.getTime())){$('.assign-status',modal).textContent='Choose a valid deadline.';return}const payload={classId,resourceId:RESOURCE_ID,activityId:'s19',title:s.assignment.title,prompt:s.instruction,rubricId:s.assignment.rubricId,deadline:deadline.toISOString(),attemptLimit:Number($('#ahLimit',modal).value||1),latePolicy:s.assignment.latePolicy,status:'active'};const r=await fetch('/api/research/assignments',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok){$('.assign-status',modal).textContent=d.error||'Could not assign homework.';return}$('.assign-status',modal).textContent='Homework assigned ✓ · It is now in the selected class Assignments.';setTimeout(()=>modal.remove(),1400)}}
function activityCaps(s){const interactive=!['cover','section-cover','aims','roleplay','reflection','thank-you'].includes(s.type);return {check:interactive,reset:interactive||s.type==='reflection',reveal:['teacher','admin'].includes(currentRole())&&interactive,submit:currentRole()==='student'&&interactive,score:answerKeys(s).length>0,assessable:answerKeys(s).length>0}}
function getActivityState(){const s=lesson?.screens?.[index];if(!s)return null;return {activityId:s.id,response:collect(s),assessment:assessment(s),capabilities:activityCaps(s)}}
function resetCurrent(){render();return true}
function checkCurrent(){const s=lesson.screens[index],g=assessment(s);paintCheck(s);emitLearningEvent('attempt.checked',s,collect(s),{grading:g});return true}
function command(name,payload={}){const s=lesson?.screens?.[index];if(!s)return false;switch(name){case'reveal':case'show-answer':case'showAnswer':return revealCurrent(s);case'reset':return resetCurrent();case'check':return checkCurrent();case'submit':doSubmit(s);return true;case'next':if(index<lesson.screens.length-1){index++;render();return true}return false;case'prev':if(index>0){index--;render();return true}return false;case'go-to-slide':{const n=Number(payload.index??payload.slide??payload.screenNumber)-1;if(Number.isInteger(n)&&n>=0&&n<lesson.screens.length){index=n;render();return true}return false}default:return false}}
window.ELEAP_LESSON_HOST_API={command,getActivityState};
function render(){const s=lesson.screens[index];currentTab=0;selectedChip=null;formPlaced=new Map();revealArmed=false;document.body.classList.remove('reveal-armed');screen.innerHTML=build(s);counter.textContent=`${index+1} / ${lesson.screens.length}`;bar.style.width=`${((index+1)/lesson.screens.length)*100}%`;prev.disabled=index===0;next.disabled=index===lesson.screens.length-1;bind(s);hydrateMedia();emitLearningEvent('activity.viewed',s,null,{screenNumber:index+1,totalScreens:lesson.screens.length})}
window.addEventListener('message',e=>{if(e.origin!==location.origin)return;const d=e.data||{};if(d.type==='e-leap:runtime-context'){runtimeContext=d.context||{};if(lesson&&lesson.screens[index]?.type==='homework-form')render();return}if(d.type==='eleap:command')command(d.command||d.name,d.payload||d)});
prev.onclick=()=>command('prev');next.onclick=()=>command('next');post('e-leap:request-runtime-context');
fetch(DATA_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Lesson data ${r.status}`);return r.json()}).then(d=>{lesson=d;render()}).catch(e=>{screen.innerHTML=`<div class="fatal">Could not load lesson: ${esc(e.message)}</div>`});