const DATA_URL='../../../../../courses/life-intermediate/unit-01/lesson-03/lesson.json';
const MEDIA_SIGN_ENDPOINT='https://xfisojqahojcsfrjjxab.supabase.co/functions/v1/get-media-url';
const screenEl=document.getElementById('screen'),counter=document.getElementById('counter'),bar=document.getElementById('bar'),prev=document.getElementById('prev'),next=document.getElementById('next');
let lesson=null,index=0,lastAssessment=null,revealArmed=false,activeTab=0,activePerson=0,formBuilder=new Set();
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>String(v??'').trim().toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const acceptable=(g,a)=>{g=norm(g);a=norm(a);if(!g)return false;if(g===a)return true;return String(a||'').split(/\s*\/\s*|\s*;\s*/).map(norm).filter(Boolean).some(x=>g===x||g.includes(x)||x.includes(g))};
const mediaKey=p=>String(p||'').replace(/^PRIVATE_MEDIA\//,'');
const localMedia=p=>'/media-private/'+mediaKey(p);
async function signedMedia(raw){try{const r=await fetch(MEDIA_SIGN_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:mediaKey(raw)})});if(!r.ok)return'';const d=await r.json();return d?.url||''}catch{return''}}
async function resolveMedia(raw){const local=localMedia(raw);try{const r=await fetch(local,{method:'HEAD',cache:'no-store'});if(r.ok)return local}catch{}return await signedMedia(raw)}
function mediaHTML(s){const raw=s?.media?.audio||s?.media?.video;if(!raw)return'';const kind=s.media.audio?'audio':'video';return `<div class="media-card" data-media-kind="${kind}" data-media-raw="${esc(raw)}"><div class="media-title">${kind==='audio'?'🎧 Audio':'▶ Video'}</div><div class="media-slot"><div class="media-status">Loading media…</div></div></div>`}
async function hydrateMedia(){for(const card of screenEl.querySelectorAll('[data-media-raw]')){const raw=card.dataset.mediaRaw,kind=card.dataset.mediaKind,slot=card.querySelector('.media-slot'),url=await resolveMedia(raw);if(!url){slot.innerHTML='<div class="media-status">Media unavailable. <button type="button" class="retry-media">Retry</button></div>';slot.querySelector('.retry-media')?.addEventListener('click',hydrateMedia);continue}slot.innerHTML=kind==='audio'?`<audio controls preload="metadata" src="${esc(url)}"></audio><div class="media-status">Audio ready</div>`:`<video controls playsinline preload="metadata" src="${esc(url)}"></video><div class="media-status">Video ready</div>`;const el=slot.querySelector(kind);el?.addEventListener('error',async()=>{const signed=await signedMedia(raw);if(signed){el.src=signed;el.load()}},{once:true})}}
function head(s){return `<div class="stage">${esc(s.bookActivity||s.stage||'')}</div><h2>${esc(s.title||'')}</h2>${s.subtitle?`<div class="subtitle">${esc(s.subtitle)}</div>`:''}${s.instruction?`<p class="instruction">${esc(s.instruction)}</p>`:''}`}
function sectionCover(s){const visual=s.visual==='park'?`<div class="section-visual park-visual"><div class="sun">☀️</div><div class="trees">🌳🌲🌳</div><div class="path"></div><div class="flowers">🌸🌼🌷🌺</div></div>`:`<div class="section-visual forms-visual">${[1,2,3,4].map(()=>`<div class="mini-form"><i></i><i></i><i></i><i></i><i></i></div>`).join('')}</div>`;return `<div class="section-cover"><div class="section-copy"><div class="stage">${esc(s.stage)}</div><h1>${esc(s.title)}</h1><div class="subtitle">${esc(s.subtitle||'')}</div></div>${visual}</div>`}
function buildCover(s){return `<div class="cover-card"><div class="stage">${esc(s.stage)}</div><h1>${esc(s.title)}</h1><div class="subtitle">${esc(s.subtitle||'')}</div><div class="cover-list">${(s.items||[]).map(x=>`<div>${esc(x)}</div>`).join('')}</div></div>`}
function buildAims(s){return `${head(s)}<div class="aim-grid">${s.groups.map(g=>`<article class="aim-card"><h3>${esc(g.heading)}</h3><ul>${g.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('')}</div>`}
function buildMatchPairs(s){const shuffled=[...s.items].sort(()=>Math.random()-.5);return `${head(s)}<div class="headings-bank">${shuffled.map((x,i)=>`<div class="heading-chip">${String.fromCharCode(65+i)} · ${esc(x.answer)}</div>`).join('')}</div><div class="match-rows">${s.items.map((x,i)=>`<div class="prompt-row reveal-target" data-answer="${esc(x.answer)}"><div class="q">${i+1}. ${esc(x.question)}</div><div class="answer-slot"><input class="letter-input" data-response="${i}" placeholder="Type advice"></div><div class="answer-inline">${esc(x.answer)}</div></div>`).join('')}</div><div class="model-box"><h3>Speaking frame</h3>${(s.speakingFrame||[]).map(x=>`<div class="model-line">${esc(x)}</div>`).join('')}</div><div id="feedback" class="feedback"></div>`}
function buildFormGallery(s){return `${head(s)}<div class="form-gallery">${s.forms.map((f,i)=>`<article class="form-card reveal-target"><div class="form-icon">${f.icon}</div><div class="form-hint">${esc(f.hint)}</div><input data-response="${i}" placeholder="What form is this?"><div class="answer">${esc(f.label)}</div></article>`).join('')}</div><div class="discussion-box"><ul>${s.discussion.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div id="feedback" class="feedback"></div>`}
function buildMcq(s){return `${head(s)}<div class="cards">${s.items.map((it,i)=>`<article class="card mcq-card" data-mcq="${i}" data-answer="${esc(it.answer)}"><div class="card-q">${i+1}. ${esc(it.question)}</div><div class="choice-grid">${it.choices.map(c=>`<button class="choice" data-choice-item="${i}" data-value="${esc(c)}" type="button">${esc(c)}</button>`).join('')}</div></article>`).join('')}</div><div id="feedback" class="feedback"></div>`}
function buildLetterMatch(s){return `${head(s)}<div class="headings-bank">${s.headings.map(h=>`<div class="heading-chip"><b>${h.letter}</b> · ${esc(h.text)}</div>`).join('')}</div><div class="match-rows">${s.items.map((it,i)=>`<div class="prompt-row reveal-target"><div class="q">${i+1}. ${esc(it.question)}</div><div class="answer-slot"><input class="letter-input" maxlength="1" data-response="${i}" placeholder="e.g. A"></div><div class="answer-inline">${esc(it.answer)} · ${esc(s.headings.find(h=>h.letter===it.answer)?.text||'')}</div></div>`).join('')}</div><div id="feedback" class="feedback"></div>`}
function buildShortReveal(s){return `${head(s)}<div class="cards compact-2">${s.items.map((it,i)=>`<article class="card reveal-target"><div class="card-q">${i+1}. ${esc(it.question)}</div><input class="short-input" data-response="${i}" placeholder="Type your answer"><div class="answer">${esc(it.answer)}</div></article>`).join('')}</div><div id="feedback" class="feedback"></div>`}
function buildListeningTabs(s){const tab=s.tabs[activeTab];return `${head(s)}${mediaHTML(s)}<div class="tab-bar">${s.tabs.map((t,i)=>`<button class="tab-btn ${i===activeTab?'active':''}" data-tab="${i}" type="button">${esc(t.label)}</button>`).join('')}</div><div class="cards">${tab.items.map((it,i)=>`<article class="card reveal-target"><div class="card-q">${esc(it.prompt)}</div><input class="short-input" data-tab-response="${activeTab}-${i}" placeholder="Type your answer"><div class="answer">${esc(it.answer)}</div></article>`).join('')}</div><div id="feedback" class="feedback"></div>`}
function buildFormBuilder(s){if(!formBuilder.size)s.fieldBank.slice(0,s.minimumFields).forEach(x=>formBuilder.add(x));return `${head(s)}<div class="builder"><div class="field-bank">${s.fieldBank.map(x=>`<button class="field-chip ${formBuilder.has(x)?'selected':''}" data-field="${esc(x)}" type="button">${esc(x)}</button>`).join('')}</div><div class="form-canvas">${[...formBuilder].map(x=>`<div class="canvas-field"><b>${esc(x)}</b><input placeholder="________________"></div>`).join('')}</div></div>`}
function buildParkLead(s){return `${head(s)}<div class="park-scene"><div class="park-visual"><div class="sun">☀️</div><div class="trees">🌳🌲🌳</div><div class="path"></div><div class="flowers">🌸🌼🌷🌺</div></div></div><div class="question-stack">${s.questions.map((it,i)=>`<div class="question-card reveal-target"><div class="q">${i+1}. ${esc(it.question)}</div><input class="short-input" data-response="${i}" placeholder="Type a short answer"><div class="answer">${esc(it.model)}</div></div>`).join('')}</div>`}
function buildVideoOrder(s){return `${head(s)}${mediaHTML(s)}<div class="video-order-layout"><div class="letter-bank">${s.choices.map(c=>`<div class="letter-row"><b>${c.letter}</b> · ${esc(c.text)}</div>`).join('')}</div><div><div class="sequence-grid">${s.sequence.map((a,i)=>`<div class="sequence-box reveal-target"><b>${i+1}.</b><input class="letter-input" maxlength="1" data-response="${i}" placeholder="a–g"><div class="answer-inline">${esc(a)} · ${esc(s.choices.find(c=>c.letter===a)?.text||'')}</div></div>`).join('')}</div><div id="feedback" class="feedback"></div></div></div>`}
function buildEvidence(s){const p=s.people[activePerson];return `${head(s)}${mediaHTML(s)}<div class="person-tabs">${s.people.map((x,i)=>`<button class="person-btn ${i===activePerson?'active':''}" data-person="${i}" type="button">${esc(x.name)}</button>`).join('')}</div><div class="evidence-layout"><div class="evidence-card reveal-target"><div class="evidence-question">Student A · ${esc(p.aPrompt)}</div><input class="short-input" data-response="0" placeholder="Type notes"><div class="answer">${esc(p.aAnswer)}</div></div><div class="evidence-card reveal-target"><div class="evidence-question">Student B · ${esc(p.bPrompt)}</div><input class="short-input" data-response="1" placeholder="Type notes"><div class="answer">${esc(p.bAnswer)}</div><button class="segment-btn" type="button" data-segment="${activePerson}">▶ Play evidence for ${esc(p.name)}</button></div></div>`}
function buildPartner(s){return `${head(s)}<div class="model-box"><h3>Partner check</h3>${s.checklist.map((x,i)=>`<div class="model-line">${i+1}. ${esc(x)}</div>`).join('')}</div>`}
function buildSpeaking(s){return `${head(s)}<div class="model-box"><h3>Questions from the book</h3>${s.questions.map(x=>`<div class="model-line">• ${esc(x)}</div>`).join('')}</div><div class="model-box" style="margin-top:18px"><h3>Model</h3>${s.model.map(x=>`<div class="model-line">${esc(x)}</div>`).join('')}</div>`}
function buildHomework(s){return `${head(s)}<div class="homework-form"><div class="homework-grid">${s.fields.map(f=>`<div class="hw-field"><label>${esc(f)}</label><input class="homework-field" data-hw-field="${esc(f)}" placeholder="________________"></div>`).join('')}</div><div class="assignment-bridge"><b>E-LEAP Homework</b><p>This task is designed to be assigned through the class Assignments shell so student submissions stay grouped by assignment and class.</p><button id="openAssignments" type="button">Open Assignments</button></div></div>`}
function buildThank(s){return `<div class="thank-you"><div class="thank-you-card"><div class="stage">${esc(s.stage)}</div><h1>Thank you</h1><p>${esc(s.subtitle||'')}</p><div style="font-size:64px">🌿✨📘</div></div></div>`}
function buildScreen(s){switch(s.type){case'cover-modern':return buildCover(s);case'aims-horizontal':return buildAims(s);case'match-pairs':return buildMatchPairs(s);case'section-cover':return sectionCover(s);case'form-gallery':return buildFormGallery(s);case'mcq-cards':return buildMcq(s);case'letter-match':return buildLetterMatch(s);case'short-answer-reveal':return buildShortReveal(s);case'listening-tabs':return buildListeningTabs(s);case'form-builder':return buildFormBuilder(s);case'park-lead-in':return buildParkLead(s);case'video-order-letters':return buildVideoOrder(s);case'video-evidence-notes':return buildEvidence(s);case'partner-check':return buildPartner(s);case'speaking-model':return buildSpeaking(s);case'homework-form':return buildHomework(s);case'thank-you':return buildThank(s);default:return head(s)}}
function render(){const s=lesson.screens[index];lastAssessment=null;revealArmed=false;document.body.classList.remove('platform-reveal-armed');document.body.dataset.screen=String(index+1);document.body.dataset.presentation=new URLSearchParams(location.search).get('eleapMode')==='presentation'?'1':'0';counter.textContent=`${index+1} / ${lesson.screens.length}`;bar.style.width=`${((index+1)/lesson.screens.length)*100}%`;prev.disabled=index===0;next.disabled=index===lesson.screens.length-1;screenEl.innerHTML=buildScreen(s);bindScreen(s);hydrateMedia();notifyContext()}
function bindScreen(s){screenEl.querySelectorAll('[data-choice-item]').forEach(b=>b.onclick=()=>{const i=b.dataset.choiceItem;screenEl.querySelectorAll(`[data-choice-item="${i}"]`).forEach(x=>x.classList.remove('selected','wrong','answer-highlight'));b.classList.add('selected');lastAssessment=null});screenEl.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>lastAssessment=null));screenEl.querySelectorAll('.reveal-target').forEach(el=>{const reveal=()=>{if(!revealArmed)return;el.classList.add('is-revealed')};el.addEventListener('click',e=>{if(e.target.matches('input,button'))return;reveal()});el.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&revealArmed)reveal()})});screenEl.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=Number(b.dataset.tab);render()});screenEl.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{activePerson=Number(b.dataset.person);render()});screenEl.querySelectorAll('[data-field]').forEach(b=>b.onclick=()=>{const f=b.dataset.field;formBuilder.has(f)?formBuilder.delete(f):formBuilder.add(f);render()});screenEl.querySelector('[data-segment]')?.addEventListener('click',playEvidence);screenEl.querySelector('#openAssignments')?.addEventListener('click',()=>{const s=lesson.screens[index];try{localStorage.setItem('e-leap-assignment-draft',JSON.stringify(s.assignmentBridge||{}))}catch{};window.top.location.href='../../../../../index.html'})}
function responseValues(){return [...screenEl.querySelectorAll('[data-response]')].map(x=>x.value)}
function keysFor(s){if(s.type==='form-gallery')return s.forms.map(x=>x.label);if(s.type==='mcq-cards')return s.items.map(x=>x.answer);if(['letter-match','short-answer-reveal'].includes(s.type))return s.items.map(x=>x.answer);if(s.type==='listening-tabs')return s.tabs[activeTab].items.map(x=>x.answer);if(s.type==='video-order-letters')return s.sequence;if(s.type==='video-evidence-notes'){const p=s.people[activePerson];return[p.aAnswer,p.bAnswer]}if(s.type==='match-pairs')return s.items.map(x=>x.answer);return[]}
function assessable(s){return ['form-gallery','mcq-cards','letter-match','short-answer-reveal','listening-tabs','video-order-letters','video-evidence-notes','match-pairs'].includes(s.type)}
function compute(s,{paint=false}={}){const keys=keysFor(s);if(!keys.length)return null;let vals=[];if(s.type==='mcq-cards'){vals=s.items.map((_,i)=>screenEl.querySelector(`[data-choice-item="${i}"].selected`)?.dataset.value||'')}else vals=responseValues();let correct=0,answered=0;keys.forEach((k,i)=>{const v=vals[i]||'';if(String(v).trim())answered++;if(acceptable(v,k))correct++;if(paint&&s.type==='mcq-cards'){const selected=screenEl.querySelector(`[data-choice-item="${i}"].selected`);if(selected)selected.classList.add(acceptable(v,k)?'correct':'wrong')}});return{totalCount:keys.length,correctCount:correct,answeredCount:answered,unansweredCount:Math.max(0,keys.length-answered),score:keys.length?correct/keys.length:0}}
function check(){const s=lesson.screens[index],a=compute(s,{paint:true});lastAssessment=a;const fb=screenEl.querySelector('#feedback');if(fb&&a){fb.className='feedback '+(a.correctCount===a.totalCount?'ok':'bad');fb.textContent=`${a.correctCount}/${a.totalCount} correct · ${a.unansweredCount} unanswered`}return!!a}
function reset(){screenEl.querySelectorAll('input').forEach(x=>x.value='');screenEl.querySelectorAll('.selected,.wrong,.correct,.answer-highlight,.is-revealed,.reveal-ready').forEach(x=>x.classList.remove('selected','wrong','correct','answer-highlight','is-revealed','reveal-ready'));const fb=screenEl.querySelector('#feedback');if(fb)fb.textContent='';revealArmed=false;document.body.classList.remove('platform-reveal-armed');lastAssessment=null;return assessable(lesson.screens[index])}
function reveal(){const s=lesson.screens[index];if(!assessable(s))return false;if(s.type==='mcq-cards'){s.items.forEach((it,i)=>{screenEl.querySelectorAll(`[data-choice-item="${i}"]`).forEach(b=>b.classList.toggle('answer-highlight',b.dataset.value===it.answer))});return true}revealArmed=!revealArmed;document.body.classList.toggle('platform-reveal-armed',revealArmed);screenEl.querySelectorAll('.reveal-target').forEach(x=>x.classList.toggle('reveal-ready',revealArmed));return true}
function submit(){if(!assessable(lesson.screens[index]))return false;return responseValues().some(x=>String(x||'').trim())||!!screenEl.querySelector('.choice.selected')}
function state(){const s=lesson?.screens?.[index];if(!s)return null;const can=assessable(s),a=lastAssessment||compute(s);return{activityId:`life-u01-l03-${s.id}`,capabilities:{check:can,reset:can,reveal:can,submit:can,score:can,assessable:can},assessment:can?a:null,response:responseValues()}}
function playEvidence(e){const video=screenEl.querySelector('video');if(!video)return;const idx=Number(e.currentTarget.dataset.segment||0),n=lesson.screens[index].people.length;const go=()=>{const d=video.duration||0;if(!d)return;const start=Math.max(0,(d/n)*idx-2),end=Math.min(d,start+Math.max(10,d/n*.75));video.currentTime=start;video.play();const stop=()=>{if(video.currentTime>=end){video.pause();video.removeEventListener('timeupdate',stop)}};video.addEventListener('timeupdate',stop)};video.readyState>=1?go():video.addEventListener('loadedmetadata',go,{once:true})}
window.ELEAP_LESSON_HOST_API={command(action){if(action==='check')return check();if(action==='reset')return reset();if(action==='reveal')return reveal();if(action==='submit')return submit();return false},getActivityState(){return state()}};
function notifyContext(){try{parent.postMessage({type:'e-leap:lesson-screen',screenNumber:index+1,activityId:`life-u01-l03-${lesson.screens[index].id}`},location.origin)}catch{}}
prev.onclick=()=>{if(index>0){index--;activeTab=0;activePerson=0;render()}};next.onclick=()=>{if(index<lesson.screens.length-1){index++;activeTab=0;activePerson=0;render()}};window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight'&&index<lesson.screens.length-1){index++;render()}if(e.key==='ArrowLeft'&&index>0){index--;render()}});
fetch(DATA_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Lesson data unavailable (${r.status})`);return r.json()}).then(d=>{lesson=d;render()}).catch(e=>{screenEl.innerHTML=`<div class="panel"><h2>Lesson could not load</h2><p>${esc(e.message)}</p></div>`});