(()=>{
const D=window.ELEAP_U3;const $=s=>document.querySelector(s);const role=(new URLSearchParams(location.search).get('role')||'teacher').toLowerCase();let lessonIndex=+(new URLSearchParams(location.search).get('lesson')||0);if(!D.lessons[lessonIndex])lessonIndex=0;let slideIndex=0,partIndex=0,seqIndex=0,timerId=null,timerLeft=60,server=false;const lesson=()=>D.lessons[lessonIndex],slide=()=>lesson().slides[slideIndex];
const norm=s=>(s||'').toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim();
async function api(path,opts={}){try{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok)throw 0;server=true;return await r.json()}catch(e){server=false;return null}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function mediaAudio(src){return src?`<div class="audio"><span>▶ Audio</span><audio controls preload="metadata" src="${esc(src)}"></audio></div>`:''}
function imgCard(src,i,answer=''){return `<div class="card"><span class="num">${i+1}</span><div class="photo">${src?`<img src="${esc(src)}" alt="Visual ${i+1}" onerror="this.remove();this.parentElement.textContent='Visual ${i+1}';">`:`Visual ${i+1}`}</div><input class="answer" data-answer="${esc(answer)}" data-item="${i}" autocomplete="off" placeholder="Type your answer…"></div>`}
function inputRow(q,a,i){return `<div class="card"><div class="body"><strong>${esc(q)}</strong></div><input class="answer" data-answer="${esc(a||'')}" data-item="${i}" autocomplete="off" placeholder="Type your answer…"></div>`}
function render(){partIndex=0;seqIndex=0;const s=slide();$('#section').textContent=s.section||'';$('#title').textContent=s.title||'';$('#prompt').textContent=s.prompt||'';$('#roleBadge').textContent=role[0].toUpperCase()+role.slice(1);$('#lessonName').textContent=lesson().title;$('#progress').textContent=`${slideIndex+1} / ${lesson().slides.length}`;const b=$('#body');b.innerHTML='';if(s.type==='cover'){b.innerHTML=`<div class="cover"><div><div class="kicker">${esc(D.course)}</div><h1>${esc(s.title)}</h1><div class="prompt">${esc(s.prompt)}</div></div></div>`}
else if(s.type==='bullets'){b.innerHTML=`<div class="list">${(s.items||[]).map(x=>`<div class="pill">${esc(x)}</div>`).join('')}</div>`}
else if(s.type==='picture-input'){b.innerHTML=mediaAudio(s.audio)+`<div class="grid cards7">${s.answers.map((a,i)=>imgCard(s.images?.[i],i,a)).join('')}</div>`}
else if(s.type==='part-picture-input'){renderPartPicture(s,b)}
else if(s.type==='inputs'){b.innerHTML=mediaAudio(s.audio)+`<div class="grid">${s.questions.map((q,i)=>inputRow(q,s.answers[i],i)).join('')}</div>`}
else if(s.type==='part-inputs'){renderPartInputs(s,b)}
else if(s.type==='sequence-input'||s.type==='sequence-repair'){renderSequence(s,b)}
else if(s.type==='rule'){b.innerHTML=`<div class="rule-panels">${(s.examples||[]).map((x,i)=>`<div class="rule-panel ${i?'now':''}"><div class="body"><strong>${esc(x)}</strong></div><textarea class="answer" data-answer="${esc(s.answers?.[i]||'')}" data-item="${i}" rows="3" placeholder="What rule do you notice?"></textarea></div>`).join('')}</div>`}
else if(s.type==='two-zone'){b.innerHTML=`<div class="rule-panels"><div class="rule-panel"><h2>${esc(s.leftTitle)}</h2>${s.left.map(x=>`<div class="pill">${esc(x)}</div>`).join('')}</div><div class="rule-panel now"><h2>${esc(s.rightTitle)}</h2>${s.right.map(x=>`<div class="pill">${esc(x)}</div>`).join('')}</div></div><div class="card" style="margin-top:16px"><textarea class="answer" data-item="0" rows="3" placeholder="Write one sentence about Sonia…"></textarea></div>`}
else if(s.type==='dialogue-gap'){b.innerHTML=mediaAudio(s.audio)+`<div class="parts"><span class="pill">Verb bank: ${(s.verbBank||[]).map(esc).join(' · ')}</span></div><div class="dialogue">${(s.dialogue||[]).map(x=>`<div class="bubble">${esc(x)}</div>`).join('')}</div>`}
else if(s.type==='match'){b.innerHTML=`<div class="grid">${s.pairs.map((p,i)=>`<div class="card"><div class="body">${esc(p[0])}</div><input class="answer" data-answer="${esc(p[1])}" data-item="${i}" placeholder="Match / type the short answer…"></div>`).join('')}</div>`}
else if(s.type==='groups-order'){b.innerHTML=mediaAudio(s.audio)+`<div class="grid cards4">${s.groups.map((g,gi)=>`<div class="card"><span class="num">${gi+1}</span>${g.words.map((w,i)=>`<div class="pill">${esc(w)} <input class="answer" style="width:72px;display:inline-block;margin-left:8px" data-answer="${g.answer[i]}" data-item="${gi}-${i}" inputmode="numeric" placeholder="#"></div>`).join('')}</div>`).join('')}</div>`}
else if(s.type==='listen-repeat'){b.innerHTML=mediaAudio(s.audio)+`<div class="rule-panel now"><div class="prompt">Listen → Repeat → Replay</div><div class="body">${esc(s.prompt)}</div></div>`}
else if(s.type==='sort-open'){b.innerHTML=`<div class="rule-panels"><div class="rule-panel"><h2>/æ/</h2></div><div class="rule-panel now"><h2>/ɑː/ · /ʌ/</h2></div></div><div class="list" style="margin-top:16px">${s.items.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div><textarea class="answer" data-item="0" rows="3" placeholder="Write your grouping…"></textarea>`}
else if(s.type==='mcq-sequence'){renderMCQ(s,b)}
else {b.innerHTML=`<div class="card"><textarea class="answer" data-item="0" rows="6" placeholder="Type your response…"></textarea>${s.model?`<div class="small" data-model="1" hidden><strong>Model:</strong> ${esc(s.model)}</div>`:''}</div>`}
applyRole();postTeacherState();}
function renderPartPicture(s,b){const p=s.parts[partIndex];b.innerHTML=`<div class="parts">${s.parts.map((x,i)=>`<button class="part ${i===partIndex?'active':''}" data-part="${i}">${esc(x.name)}</button>`).join('')}</div><div class="grid ${p.indices.length===4?'cards4':'cards3'}">${p.indices.map(i=>imgCard(s.images?.[i],i,s.answers[i])).join('')}</div>`;b.querySelectorAll('[data-part]').forEach(x=>x.onclick=()=>{partIndex=+x.dataset.part;renderPartPicture(s,b)})}
function renderPartInputs(s,b){const p=s.parts[partIndex];b.innerHTML=mediaAudio(s.audio)+`<div class="parts">${s.parts.map((x,i)=>`<button class="part ${i===partIndex?'active':''}" data-part="${i}">${esc(x.name)}</button>`).join('')}</div><div class="grid">${p.indices.map(i=>inputRow(s.questions[i],s.answers[i],i)).join('')}</div>`;b.querySelectorAll('[data-part]').forEach(x=>x.onclick=()=>{partIndex=+x.dataset.part;renderPartInputs(s,b)})}
function renderSequence(s,b){const it=s.items[seqIndex];b.innerHTML=`<div class="parts"><button class="part" id="seqPrev">←</button><span class="pill">Item ${seqIndex+1} / ${s.items.length}</span><button class="part" id="seqNext">→</button></div><div class="card"><div class="prompt">${esc(it[0])}</div><input class="answer" data-answer="${esc(it[1])}" data-item="${seqIndex}" placeholder="Type your answer…"></div>`;$('#seqPrev').onclick=()=>{seqIndex=Math.max(0,seqIndex-1);renderSequence(s,b)};$('#seqNext').onclick=()=>{seqIndex=Math.min(s.items.length-1,seqIndex+1);renderSequence(s,b)}}
function renderMCQ(s,b){const it=s.items[seqIndex];b.innerHTML=`<div class="parts"><button class="part" id="seqPrev">←</button><span class="pill">Item ${seqIndex+1} / ${s.items.length}</span><button class="part" id="seqNext">→</button></div><div class="card"><div class="prompt">${esc(it.q)}</div>${it.options.map(o=>`<button class="option" data-option="${esc(o)}" data-answer="${esc(it.answer)}">${esc(o)}</button>`).join('')}</div>`;b.querySelectorAll('.option').forEach(o=>o.onclick=()=>{b.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));o.classList.add('selected')});$('#seqPrev').onclick=()=>{seqIndex=Math.max(0,seqIndex-1);renderMCQ(s,b)};$('#seqNext').onclick=()=>{seqIndex=Math.min(s.items.length-1,seqIndex+1);renderMCQ(s,b)}}
function getAnswers(){const inputs=[...document.querySelectorAll('.answer')].map(x=>({item:x.dataset.item||'',value:x.value||''}));const sel=$('.option.selected');if(sel)inputs.push({item:String(seqIndex),value:sel.dataset.option});return inputs}
function check(){let total=0,correct=0;document.querySelectorAll('.answer[data-answer]').forEach(x=>{if(!x.dataset.answer)return;total++;const ok=norm(x.value)===norm(x.dataset.answer);x.classList.toggle('correct',ok);x.classList.toggle('wrong',!ok);if(ok)correct++});const sel=$('.option.selected');if(sel){total++;const ok=norm(sel.dataset.option)===norm(sel.dataset.answer);sel.classList.toggle('correct',ok);sel.classList.toggle('wrong',!ok);if(ok)correct++}$('#status').textContent=total?`${correct}/${total} correct`:'Open response · teacher review';return{total,correct}}
function reset(){document.querySelectorAll('.answer').forEach(x=>{x.value='';x.classList.remove('correct','wrong','revealed')});document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected','correct','wrong'));document.querySelectorAll('[data-model]').forEach(x=>x.hidden=true);$('#status').textContent=''}
function showAnswer(){if(role==='student'||role==='guest')return;document.querySelectorAll('.answer[data-answer]').forEach(x=>{if(x.dataset.answer){x.value=x.dataset.answer;x.classList.add('revealed')}});const s=slide();if(s.type==='mcq-sequence'){document.querySelectorAll('.option').forEach(x=>{if(norm(x.dataset.option)===norm(x.dataset.answer))x.classList.add('correct')})}document.querySelectorAll('[data-model]').forEach(x=>x.hidden=false);$('#status').textContent='Answer revealed'}
async function submit(){const payload={name:localStorage.getItem('eleapName')||prompt('Your name')||'Student',lessonId:lesson().id,slideId:slide().id,answers:getAnswers(),ts:Date.now()};localStorage.setItem('eleapName',payload.name);const r=await api('/api/response',{method:'POST',body:JSON.stringify(payload)});if(!r){const all=JSON.parse(localStorage.getItem('eleapOfflineResponses')||'[]');all.push(payload);localStorage.setItem('eleapOfflineResponses',JSON.stringify(all))}$('#status').textContent='Submitted'}
async function postTeacherState(){if(role!=='teacher'&&role!=='admin')return;await api('/api/state',{method:'POST',body:JSON.stringify({lessonIndex,slideIndex,slideId:slide().id})})}
async function poll(){if(role==='student'){const st=await api('/api/state');if(st&&typeof st.slideIndex==='number'&&(st.slideIndex!==slideIndex||st.lessonIndex!==lessonIndex)){lessonIndex=st.lessonIndex||0;slideIndex=st.slideIndex;render()}}setTimeout(poll,900)}
async function openResponses(){const box=$('#responsesBox');box.classList.add('open');$('#panelTitle').textContent='Responses · '+slide().title;let rows=[];const r=await api('/api/responses?slideId='+encodeURIComponent(slide().id));if(r?.responses)rows=r.responses;else rows=(JSON.parse(localStorage.getItem('eleapOfflineResponses')||'[]')).filter(x=>x.slideId===slide().id);$('#panelBody').innerHTML=rows.length?rows.map(x=>`<div class="response-row"><strong>${esc(x.name||'Student')}</strong><div>${(x.answers||[]).map(a=>esc(a.value)).join(' · ')}</div></div>`).join(''):'<div class="small">No responses yet.</div>'}
async function live(){const box=$('#responsesBox');box.classList.add('open');$('#panelTitle').textContent='Live Class / QR';const st=await api('/api/state')||{};const base=(location.protocol.startsWith('http')?location.origin:'http://YOUR-LAN-IP:8765');const url=base+location.pathname+'?role=student&lesson='+lessonIndex;$('#panelBody').innerHTML=`<div class="live-box"><div class="body"><strong>Join code:</strong> ${esc(st.joinCode||'U3LIVE')}</div><p class="live-url">${esc(url)}</p><img src="/api/qr?text=${encodeURIComponent(url)}" alt="QR" style="max-width:220px;width:100%;background:white;border-radius:12px" onerror="this.style.display='none';this.nextElementSibling.hidden=false"><div class="small" hidden>QR generator unavailable. Students can use the join URL above.</div></div>`}
function timer(){if(timerId){clearInterval(timerId);timerId=null;$('#timer').textContent='Timer';return}timerLeft=60;$('#timer').textContent='60s';timerId=setInterval(()=>{timerLeft--;$('#timer').textContent=timerLeft+'s';if(timerLeft<=0){clearInterval(timerId);timerId=null;$('#timer').textContent='Time!'}},1000)}
function applyRole(){const teacher=role==='teacher'||role==='admin';$('#check').hidden=false;$('#reset').hidden=false;$('#show').hidden=!teacher;$('#present').hidden=!teacher;$('#timer').hidden=!teacher;$('#responses').hidden=!teacher;$('#live').hidden=!teacher;$('#submit').hidden=role!=='student';$('#score').hidden=!(role==='student'||role==='guest');$('#next').disabled=role==='student'&&server;$('#prev').disabled=role==='student'&&server}
function next(){if(slideIndex<lesson().slides.length-1){slideIndex++;render()}}
function prev(){if(slideIndex>0){slideIndex--;render()}}
$('#check').onclick=check;$('#reset').onclick=reset;$('#show').onclick=showAnswer;$('#submit').onclick=submit;$('#score').onclick=()=>{const x=check();$('#status').textContent=x.total?`${x.correct}/${x.total} · ${Math.round(x.correct/x.total*100)}%`:'Open response'};$('#responses').onclick=openResponses;$('#live').onclick=live;$('#timer').onclick=timer;$('#present').onclick=()=>{document.body.classList.toggle('presentation');$('#present').textContent=document.body.classList.contains('presentation')?'Exit Presentation':'Presentation'};$('#next').onclick=next;$('#prev').onclick=prev;$('#closePanel').onclick=()=>$('#responsesBox').classList.remove('open');document.addEventListener('keydown',e=>{if(role==='student'&&server)return;if(['ArrowRight','PageDown'].includes(e.key))next();if(['ArrowLeft','PageUp'].includes(e.key))prev();if(e.key==='Escape')document.body.classList.remove('presentation')});render();poll();
})();