window.ELEAP_U3 = {
  course: "Objectives B1 · Objective PET",
  unit: "Unit 3 · What's your job?",
  theme: {primary:"#1F5A45",accent:"#A8C83E",background:"#F7F4EA",surface:"#FFFDF7",text:"#26322C"},
  lessons: [
    {
      id:"obj-b1-u03-l01", title:"Lesson 3.1 · Jobs & Present Tenses",
      slides:[
        {id:"u31-s01",section:"UNIT 3",title:"What's your job?",type:"cover",prompt:"Jobs · Present simple · Present continuous"},
        {id:"u31-s02",section:"AIMS",title:"By the end of the lesson...",type:"bullets",items:["Use vocabulary for common jobs and workplace activities.","Distinguish routines from actions happening now.","Listen for gist and detail about jobs.","Use state verbs and short answers accurately."]},
        {id:"u31-s03",activityId:"obj-b1-u03-l01-intro-a01",section:"INTRODUCTION",title:"Listen & Match the Jobs",type:"picture-input",prompt:"Listen to seven people. Match each speaker to a numbered workplace picture.",labels:["1","2","3","4","5","6","7"],answers:["shop assistant","flight attendant","car salesman","website designer","hairdresser","mechanic","engineer"],images:["media/images/job-01-shop-assistant.jpg","media/images/job-02-flight-attendant.jpg","media/images/job-03-car-salesman.jpg","media/images/job-04-website-designer.jpg","media/images/job-05-hairdresser.jpg","media/images/job-06-mechanic.jpg","media/images/job-07-engineer.jpg"],audio:"media/audio/obj-b1-u03-intro-a01-audio.mp3"},
        {id:"u31-s04",activityId:"obj-b1-u03-l01-intro-a02",section:"INTRODUCTION",title:"Name the Jobs",type:"picture-input",prompt:"Use the visual clues. What does each person do?",labels:["1","2","3","4","5","6","7"],answers:["shop assistant","flight attendant","car salesman","website designer","hairdresser","mechanic","engineer"],images:["media/images/clue-01-shop.jpg","media/images/clue-02-aircraft.jpg","media/images/clue-03-showroom.jpg","media/images/clue-04-web.jpg","media/images/clue-05-salon.jpg","media/images/clue-06-garage.jpg","media/images/clue-07-plan.jpg"]},
        {id:"u31-s05",activityId:"obj-b1-u03-l01-intro-a03",section:"INTRODUCTION",title:"What Are They Doing?",type:"part-picture-input",prompt:"Describe what each person is doing now.",parts:[{name:"Part 1",indices:[0,1,2,3]},{name:"Part 2",indices:[4,5,6]}],answers:["The shop assistant is tidying some clothes.","The flight attendant is bringing the pilots some food.","The salesman is working at his computer.","The mechanic is having a break.","The website designer is plugging in her computer.","The hairdresser is holding a mirror.","The engineer is looking at a plan."],images:["media/images/action-01-shop.jpg","media/images/action-02-flight.jpg","media/images/action-03-salesman.jpg","media/images/action-04-mechanic.jpg","media/images/action-05-web-designer.jpg","media/images/action-06-hairdresser.jpg","media/images/action-07-engineer.jpg"]},
        {id:"u31-s06",activityId:"obj-b1-u03-l01-intro-a04",section:"SPEAKING",title:"Would You Like This Job?",type:"open",prompt:"Choose one job. Would you like to do it? Give one reason.",model:"I'd like to be a ... because ... / I wouldn't like to be a ... because ..."},
        {id:"u31-s07",activityId:"obj-b1-u03-l01-listening-a01",section:"LISTENING",title:"Who Works Here? · Clue Challenge",type:"open",prompt:"Study the shopping-mall scene. Infer one person's job and justify your choice with two visual clues.",model:"I think this person is a ... because ..."},
        {id:"u31-s08",activityId:"obj-b1-u03-l01-listening-a02",section:"LISTENING",title:"Listen for Gist",type:"inputs",prompt:"Listen. What is the man's job? Who is he talking to?",questions:["What is his job?","Who is he talking to?"],answers:["He is a security officer in a shopping mall.","He is talking to a police officer."],audio:"media/audio/obj-b1-u03-listening-a02-audio.mp3"},
        {id:"u31-s09",activityId:"obj-b1-u03-l01-listening-a03",section:"LISTENING",title:"Listen for Detail",type:"part-inputs",prompt:"Listen again. Write the five jobs in the order they are described.",parts:[{name:"Part 1",indices:[0,1,2]},{name:"Part 2",indices:[3,4]}],questions:["1","2","3","4","5"],answers:["artist","photographer","model","journalist","bank guard"],audio:"media/audio/obj-b1-u03-listening-a02-audio.mp3"},
        {id:"u31-s10",activityId:"obj-b1-u03-l01-language-a01",section:"LANGUAGE FOCUS",title:"Present Simple or Present Continuous?",type:"sequence-input",prompt:"Complete one sentence at a time. Then decide: USUAL or NOW?",items:[["The security officer ___ to a police officer.","is talking"],["The model ___ by a fountain.","is standing"],["The photographer ___ his photographs to magazines.","sells"],["The thief ___ a shopping bag on wheels.","is pulling"],["The thief ___ things from shops.","steals"],["The bank guard ___ at the thief.","isn't looking"],["The bank guard never ___ anything, because he's lazy.","does"],["The photographer ___ a photograph of the model.","is taking"],["The artist ___ her pictures to the children's parents.","sells"],["The thief ___ anything at the moment.","isn't stealing"],["The journalist ___ something in his notebook.","is writing"]]},
        {id:"u31-s11",activityId:"obj-b1-u03-l01-grammar-spot-01",section:"GRAMMAR SPOT",title:"Discover the Rule",type:"rule",prompt:"Compare the examples and infer the rule.",examples:["I design websites.","I'm plugging in my computer."],answers:["Use the present simple to talk about what we usually do.","Use the present continuous to talk about what we are doing now / around the present."]},
        {id:"u31-s12",activityId:"obj-b1-u03-l01-language-a02",section:"LANGUAGE FOCUS",title:"Sonia · Usually vs This Week",type:"two-zone",prompt:"Sort the activities, then make sentences about Sonia.",leftTitle:"USUALLY",rightTitle:"THIS WEEK",left:["cycle to school","do lessons all day","study at home in the evening","play volleyball after school","not wear her best skirt every day"],right:["not go to school","not do any homework","work in a hotel","have meals with her colleagues","speak French with hotel guests"]},
        {id:"u31-s13",activityId:"obj-b1-u03-l01-language-a03",section:"LANGUAGE FOCUS",title:"Sonia Calls Granny",type:"dialogue-gap",prompt:"Complete the telephone conversation. Then listen and check.",verbBank:["do","look forward to","work","not go","start","get up","like","help","not work","understand","prefer","stay"],dialogue:["Sonia: Hi, Granny. How are you?","Granny: Oh, not bad. How's school?","Sonia: I'm not going to school this week.","Granny: Why not? Are you ill?","Sonia: No, I am doing work experience. I am working in a hotel.","Granny: I hope you are not working in the kitchen. You're not good at cooking!","Sonia: No, I'm not in the kitchen. I am helping the receptionist and the manager.","Sonia: I like working with the manager, she's really friendly. But I prefer helping the receptionist because I can talk to the guests.","Sonia: Some French people are staying in the hotel. I understand almost everything they say.","Sonia: When I go to school, I get up at half past seven, but this week I am starting work at seven o'clock.","Sonia: Oh, yes. I am looking forward to it."],audio:"media/audio/obj-b1-u03-language-a03-audio.mp3"},
        {id:"u31-s14",activityId:"obj-b1-u03-l01-state-verbs",section:"GRAMMAR SPOT",title:"State Verbs · Repair the Sentence",type:"sequence-repair",prompt:"Correct one sentence at a time.",items:[["I'm not believing you can fly a plane.","I don't believe you can fly a plane."],["I'm liking them very much.","I like them very much."],["We're thinking this CD is very expensive.","We think this CD is very expensive."],["Are you wanting some coffee?","Do you want some coffee?"],["I'm not knowing your number.","I don't know your number."],["I'm not understanding what she's saying.","I don't understand what she's saying."],["I'm not liking it.","I don't like it."]]},
        {id:"u31-s15",activityId:"obj-b1-u03-l01-short-answers-match",section:"SHORT ANSWERS",title:"Match Questions & Short Answers",type:"match",prompt:"Match each question to its short-answer pattern.",pairs:[["Do I look OK?","Yes, you do. / No, you don't."],["Do you live near the school?","Yes, I do. / No, I don't."],["Does this school open on Sundays?","Yes, it does. / No, it doesn't."],["Do they like ice cream?","Yes, they do. / No, they don't."],["Am I sitting in the right place?","Yes, you are. / No, you aren't."],["Are you studying English?","Yes, I am. / No, I'm not."],["Is the sun shining?","Yes, it is. / No, it isn't."],["Are they working?","Yes, they are. / No, they aren't."]]},
        {id:"u31-s16",activityId:"obj-b1-u03-l01-short-answers-speaking",section:"SHORT ANSWERS",title:"Ask, Answer & Check",type:"open",prompt:"Ask a partner one present-tense question. Answer with a correct short answer.",model:"Do you play volleyball? — Yes, I do. / Are we speaking Italian? — No, we aren't."},
        {id:"u31-s17",activityId:"obj-b1-u03-l01-exit",section:"CONSOLIDATION",title:"Quick Exit Check",type:"open",prompt:"Give one example that shows what you learned about jobs, tenses, state verbs or short answers.",model:"Use one accurate sentence and explain your tense choice."}
      ]
    },
    {
      id:"obj-b1-u03-l02", title:"Lesson 3.2 · Pronunciation, Speaking & Exam Skills",
      slides:[
        {id:"u32-s01",section:"PRONUNCIATION",title:"Listen & Order",type:"groups-order",prompt:"Listen and number the words in the order you hear them.",groups:[{words:["cat","cart","cut"],answer:[3,2,1]},{words:["bag","bug"],answer:[1,2]},{words:["carry","curry"],answer:[2,1]},{words:["match","March","much"],answer:[1,3,2]}],audio:"media/audio/obj-b1-u03-pron-a01-audio.mp3"},
        {id:"u32-s02",section:"PRONUNCIATION",title:"Listen Again & Repeat",type:"listen-repeat",prompt:"Listen again and repeat each sentence. Use the source recording; no printed transcript is added.",audio:"media/audio/obj-b1-u03-pron-a02-audio.mp3"},
        {id:"u32-s03",section:"PRONUNCIATION",title:"Sound Sort",type:"sort-open",prompt:"Sort the words by vowel sound: /æ/ · /ɑː/ · /ʌ/.",items:["does","doesn't","can","can't","must","mustn't","are","aren't"]},
        {id:"u32-s04",section:"ACTIVITY",title:"Find the Differences",type:"sequence-input",prompt:"Describe one difference at a time using present continuous.",items:[["Difference 1","The model isn't standing by the fountain; she's talking to the journalist."],["Difference 2","The artist isn't painting a picture; she's showing a child the picture."],["Difference 3","The journalist isn't writing in his notebook; he's talking to the model."],["Difference 4","The bank guard isn't standing near the door of the bank; he's having a cup of coffee."],["Difference 5","The photographer isn't taking a photo of the model; he's taking a photo of the thief."],["Difference 6","The police officer isn't sitting in his car; he is running after the woman with the bag."]]},
        {id:"u32-s05",section:"LIVE GAME",title:"What's My Job?",type:"open",prompt:"Ask yes/no questions, then submit your final job guess.",model:"Are you making something? / Do you work indoors? / My guess: ..."},
        {id:"u32-s06",section:"SPEAKING PART 3",title:"Tom · Match Questions & Answers",type:"match",prompt:"Match the seven questions to the answers.",pairs:[["Where is he?","He's outside his house."],["What does he look like?","He's tall and he's got short fair hair."],["What is he wearing?","He's wearing white shorts and a red T-shirt."],["What kind of person is he?","He's a friendly person."],["What is he doing?","He's painting something."],["How do you feel about doing this kind of thing?","I wouldn't like to do this."],["Why?","Because I don't like the smell of paint."]]},
        {id:"u32-s07",section:"SPEAKING PART 3",title:"Describe the Young Woman",type:"open",prompt:"Use the seven-part speaking framework to describe the young woman.",model:"She's in an office. She's slim and she's got long, wavy hair. She's wearing a green dress. She's hard-working / untidy. She's reading an email and eating a sandwich. I wouldn't like to do this because I don't like office work."},
        {id:"u32-s08",section:"SPEAKING PART 3",title:"Memory Recall Challenge",type:"inputs",prompt:"Can you remember all seven questions?",questions:["1","2","3","4","5","6","7"],answers:["Where is he/she?","What does he/she look like?","What is he/she wearing?","What kind of person is he/she?","What is he/she doing?","How do you feel about doing this kind of thing?","Why?"]},
        {id:"u32-s09",section:"SPEAKING PART 3",title:"Photograph A / Photograph B",type:"open",prompt:"Student A describes Photograph A. Student B listens and checks the seven areas. Then swap.",model:"Checklist: Where · Appearance · Clothes · Personality · Current action · Feeling · Reason"},
        {id:"u32-s10",section:"READING PART 5",title:"Tom · Choose the Correct Word",type:"mcq-sequence",prompt:"Choose the correct word. If unsure, eliminate wrong options and explain why.",items:[{q:"Tom is ____.",options:["tall","long","high","great"],answer:"tall"},{q:"Tom ____ wearing a T-shirt.",options:["do","does","is","be"],answer:"is"},{q:"Tom ____ a tin of yellow paint.",options:["has","got","wants","uses"],answer:"wants"}]},
        {id:"u32-s11",section:"READING PART 5",title:"Irena · Choose the Correct Word",type:"mcq-sequence",prompt:"Choose the correct word and use elimination.",items:[{q:"Irena ____ got a tidy desk.",options:["isn't","hasn't","doesn't","aren't"],answer:"hasn't"},{q:"Irena usually ____ a sandwich for lunch.",options:["eats","eating","have","having"],answer:"eats"},{q:"Irena's a ____.",options:["hairdresser","shop assistant","nurse","secretary"],answer:"secretary"}]},
        {id:"u32-s12",section:"UNIT REVIEW",title:"Unit 3 Exit Challenge · Job City",type:"open",prompt:"Complete a mixed challenge using jobs, tenses, short answers, pronunciation, speaking and Reading Part 5 strategy.",model:"Teacher reveals one challenge at a time and reviews Responses before model answers."}
      ]
    }
  ]
};
