(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];let current=1,lastAssessment=null,edIndex=0;const total=21,slides=$$('.slide');
const norm=s=>String(s||'').trim().toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g,' ').replace(/[.!?]+$/,'');
function row(label,opts,ans,name,dark=false){return `<div class="row ${dark?'dark':''}" data-answer="${ans}"><span>${label}</span><select name="${name}"><option value="">Choose…</option>${opts.map(o=>`<option value="${o}">${o}</option>`).join('')}</select><div class="teacher-answer">Answer: ${ans}</div></div>`}
const tense=[['a · jogs','Present Simple'],['b · are gathering','Present Continuous'],['c · resets','Present Simple'],['d · are becoming','Present Continuous']];$('#tenseSort').innerHTML=tense.map((x,i)=>row(x[0],['Present Simple','Present Continuous'],x[1],`ts${i}`,true)).join('');
$('#ruleQuiz').innerHTML=[['Permanent / habitual / repeated','Present Simple'],['Temporary / changing / developing','Present Continuous']].map((x,i)=>row(x[0],['Present Simple','Present Continuous'],x[1],`rule${i}`,true)).join('');
const funcs=[['a','near-future arrangement'],['b','zero conditional'],['c','action happening now'],['d','time clause'],['e','general truth']];$('#functionMatch').innerHTML=funcs.map((x,i)=>row(x[0],funcs.map(y=>y[1]),x[1],`fn${i}`,true)).join('');
const errors=[
 ['Electronic books are becoming more and more popular.','Correct','Electronic books are becoming more and more popular.'],
 ['This week only, the shop sells all software at 20% off.','Incorrect','This week only, the shop is selling all software at 20% off.'],
 ["Don’t shut down the computer as I’m downloading a film.",'Correct',"Don’t shut down the computer as I’m downloading a film."],
 ['As soon as you are playing this game, you realise the graphics are tremendous.','Incorrect','As soon as you play this game, you realise the graphics are tremendous.'],
 ["My neighbour gives me access to his wifi this week but I’m planning to install my own on Monday.",'Incorrect',"My neighbour is giving me access to his wifi this week but I’m planning to install my own on Monday."],
 ['When you visit the website, you are getting a choice of free downloadable applications.','Incorrect','When you visit the website, you get a choice of free downloadable applications.'],
 ["Once I find a useful site, I’m bookmarking it for future reference.",'Incorrect','Once I find a useful site, I bookmark it for future reference.']
];
function renderED(){const e=errors[edIndex];$('#edCounter').textContent=`Sentence ${edIndex+1} / ${errors.length}`;$('#errorDetective').innerHTML=`<div class="round-card" data-answer="${e[1]}"><p>${e[0]}</p><div class="round-options"><button>Correct</button><button>Incorrect</button></div><input class="line-input" id="edCorrection" placeholder="If incorrect, type the corrected sentence"><div class="teacher-answer">${e[2]}</div></div>`;$$('.round-options button').forEach(b=>b.onclick=()=>{$$('.round-options button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')})}renderED();$('#edPrev').onclick=()=>{edIndex=Math.max(0,edIndex-1);renderED()};$('#edNext').onclick=()=>{edIndex=Math.min(errors.length-1,edIndex+1);renderED()};
const ex4a=[['a1 · finish','finish'],['a2 · get','get'],['b · improve','is improving'],['c · deal with','are dealing with'],['d1 · fly','flies'],['d2 · explode','explodes'],['d3 · hit','hit']];const ex4b=[['e · develop','is developing'],['f · take','take'],['g1 · log on','log on'],['g2 · require','requires'],['g3 · generate','generates'],['h1 · crash','crashes'],['h2 · lose','lose'],['h3 · work','are working'],['h4 · save','save']];
function textRows(arr,prefix){return arr.map((x,i)=>`<div class="row" data-answer="${x[1]}"><span>${x[0]}</span><input name="${prefix}${i}" placeholder="Type the verb form"><div class="teacher-answer">${x[1]}</div></div>`).join('')}$('#ex4a').innerHTML=textRows(ex4a,'a');$('#ex4b').innerHTML=textRows(ex4b,'b');
const gwAns={gw1:'is becoming',gw2:'are creating',gw3:'are updating',gw4:'means',gw5:'submits',gw6:'is adding',gw7:'sounds',gw8:'believes',gw9:'is encouraging',gw10:'is changing',gw11:'find out',gw12:'google',wf1:'accessible',wf2:'applications',wf3:'ability',wf4:'impressive',wf5:'electronically',wf6:'tricky'};
$('#gwRead').innerHTML=[['Why is googlewhacking becoming more difficult?','Because new and updated web pages create more Google entries.'],['What happens when someone submits a googlewhack to a website?','It creates/adds another entry.'],['Why does Gary Stock consider it meaningful?','It encourages people to surf the web and discover unusual things.']].map((x,i)=>`<div class="row"><span>${x[0]}</span><textarea class="response" data-open="read${i}"></textarea><div class="teacher-answer">${x[1]}</div></div>`).join('');
const sa=[['like','state'],['believe','state'],['taste','state'],['run','action'],['teach','action'],['take a photo','action'],['have','state'],['play','action']];$('#stateAction').innerHTML=sa.map(([w,a])=>`<div class="class-item" data-answer="${a}"><b>${w}</b><div class="class-actions"><button data-v="state">STATE</button><button data-v="action">ACTION</button></div><div class="teacher-answer">${a.toUpperCase()}</div></div>`).join('');
const meanings=[['BE','You are mean. / Why are you being so mean today?','state / action'],['HAVE','I have three kids. / I’m having a wonderful day.','state / action'],['SEE','Oh, I see. / Are you seeing anyone at the moment?','state / action'],['THINK','I think doing yoga is fun. / I’m thinking about doing a first-aid course.','state / action'],['TASTE','This chocolate tastes like strawberries. / They are tasting wedding cakes today.','state / action']];$('#meaningQuiz').innerHTML=meanings.map((x,i)=>`<div class="meaning-card"><h3>${x[0]}</h3><p>${x[1]}</p><select data-answer="state / action"><option value="">Choose…</option><option>state / action</option><option>action / state</option></select><div class="teacher-answer">First = state meaning; second = action meaning.</div></div>`).join('');
$('#wordFamily').innerHTML=[['true →','truth / true / truly'],['happy →','happiness / unhappy / happily'],['possible →','possibility / possible / impossible']].map((x,i)=>`<div class="row" data-answer="${x[1]}"><span>${x[0]}</span><input placeholder="Build the family"><div class="teacher-answer">${x[1]}</div></div>`).join('');
$('#adjectiveBuild').innerHTML=[['trick','tricky'],['mess','messy'],['mud','muddy'],['ice','icy']].map((x,i)=>`<div class="row" data-answer="${x[1]}"><span>${x[0]} →</span><input placeholder="adjective"><div class="teacher-answer">${x[1]}</div></div>`).join('');
const pn=[['accessible','positive'],['colourful','positive'],['dull','negative'],['excellent','positive'],['favourable','positive'],['hopeless','negative'],['impressive','positive'],['mindless','negative'],['sophisticated','positive'],['tricky','negative'],['unhelpful','negative']];$('#posNeg').innerHTML=pn.map(([w,a])=>`<div class="class-item" data-answer="${a}"><b>${w}</b><div class="class-actions"><button data-v="positive">POSITIVE</button><button data-v="negative">NEGATIVE</button></div><div class="teacher-answer">${a.toUpperCase()}</div></div>`).join('');
$('#exitQuiz').innerHTML=[['Games of this type ___ more complex now.',['become','are becoming'],'are becoming'],['I ___ this game is excellent.',['think','am thinking'],'think'],['We ___ a new computer next weekend.',['buy','are buying'],'are buying'],['mud →',['mudy','muddy'],'muddy'],['possible → negative form',['unpossible','impossible'],'impossible'],['This tablet is very ___.',['impress','impressive'],'impressive']].map((x,i)=>row(x[0],x[1],x[2],`exit${i}`,i%2===0)).join('');
$$('.class-actions').forEach(g=>g.onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('button',g).forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected');g.parentElement.dataset.value=e.target.dataset.v});$$('.choice-row').forEach(g=>g.onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('button',g).forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected');g.dataset.value=e.target.textContent.trim()});
$$('.tab').forEach(b=>b.onclick=()=>{const grp=b.dataset.tabgroup;$$(`.tab[data-tabgroup="${grp}"]`).forEach(x=>x.classList.toggle('active',x===b));$$(`[data-tabpane^="${grp}:"]`).forEach(x=>x.classList.toggle('active',x.dataset.tabpane===`${grp}:${b.dataset.tab}`))});

$$('video[data-playlist]').forEach(v=>{const parts=v.dataset.playlist.split('|');let i=0;v.addEventListener('ended',()=>{if(i<parts.length-1){i++;v.src=parts[i];v.play().catch(()=>{})}});});

function show(n){current=Math.max(1,Math.min(total,n));slides.forEach(s=>s.classList.toggle('active',+s.dataset.slide===current));$('#counter').textContent=`${current} / ${total}`;$('#bar').style.width=`${current/total*100}%`;$('#prev').disabled=current===1;$('#next').disabled=current===total;lastAssessment=null}$('#prev').onclick=()=>show(current-1);$('#next').onclick=()=>show(current+1);
function markRows(s){let totalC=0,answered=0,correct=0;$$('.row[data-answer]',s).forEach(x=>{totalC++;const el=$('select,input',x),v=el?.value||'';if(v)answered++;const ok=norm(v)===norm(x.dataset.answer);if(ok)correct++;x.classList.toggle('is-correct',ok&&!!v);x.classList.toggle('is-wrong',!!v&&!ok)});return {totalCount:totalC,answeredCount:answered,correctCount:correct,wrongCount:answered-correct,unansweredCount:totalC-answered,score:totalC?correct/totalC*100:null}}
function check(){const s=$(`.slide[data-slide="${current}"]`);let r={totalCount:0,answeredCount:0,correctCount:0,wrongCount:0,unansweredCount:0,score:null};if(current===4){const g=$('.choice-row',s),v=g.dataset.value||'';r.totalCount=1;r.answeredCount=v?1:0;r.correctCount=v===g.dataset.answer?1:0;r.wrongCount=r.answeredCount-r.correctCount;r.unansweredCount=1-r.answeredCount;r.score=r.correctCount*100;$$('button',g).forEach(b=>{b.classList.toggle('is-correct',b.textContent.trim()===g.dataset.answer&&!!v);b.classList.toggle('is-wrong',b.classList.contains('selected')&&b.textContent.trim()!==g.dataset.answer)})}else if(current===10){const card=$('.round-card'),sel=$('.round-options .selected')?.textContent||'',corr=$('#edCorrection').value;const ans=errors[edIndex];r.totalCount=1;r.answeredCount=sel?1:0;r.correctCount=sel===ans[1]&&(ans[1]==='Correct'||norm(corr)===norm(ans[2]))?1:0;r.wrongCount=r.answeredCount-r.correctCount;r.unansweredCount=1-r.answeredCount;r.score=r.correctCount*100;card.classList.toggle('is-correct',r.correctCount===1);card.classList.toggle('is-wrong',r.answeredCount===1&&r.correctCount===0)}else if([13,17].includes(current)){$$('.class-item',s).forEach(x=>{r.totalCount++;const v=x.dataset.value||'';if(v)r.answeredCount++;if(v===x.dataset.answer)r.correctCount++;x.classList.toggle('is-correct',v===x.dataset.answer&&!!v);x.classList.toggle('is-wrong',!!v&&v!==x.dataset.answer)});r.wrongCount=r.answeredCount-r.correctCount;r.unansweredCount=r.totalCount-r.answeredCount;r.score=r.totalCount?r.correctCount/r.totalCount*100:null}else if(current===14){$$('.meaning-card select',s).forEach(x=>{r.totalCount++;if(x.value)r.answeredCount++;if(x.value===x.dataset.answer)r.correctCount++});r.wrongCount=r.answeredCount-r.correctCount;r.unansweredCount=r.totalCount-r.answeredCount;r.score=r.correctCount/r.totalCount*100}else if([12,18].includes(current)){const inputs=$$('[data-gap]',s);inputs.forEach(x=>{r.totalCount++;if(x.value)r.answeredCount++;if(norm(x.value)===norm(gwAns[x.dataset.gap])){r.correctCount++;x.classList.add('is-correct')}else if(x.value)x.classList.add('is-wrong')});r.wrongCount=r.answeredCount-r.correctCount;r.unansweredCount=r.totalCount-r.answeredCount;r.score=r.correctCount/r.totalCount*100}else r=markRows(s);lastAssessment=r;return true}
function reset(){const s=$(`.slide[data-slide="${current}"]`);$$('input,textarea',s).forEach(x=>x.value='');$$('select',s).forEach(x=>x.value='');$$('.selected,.is-correct,.is-wrong,.revealed',s).forEach(x=>x.classList.remove('selected','is-correct','is-wrong','revealed'));$$('[data-value]',s).forEach(x=>delete x.dataset.value);lastAssessment=null;return true}
function reveal(){const s=$(`.slide[data-slide="${current}"]`);const next=$$('.teacher-answer',s).find(x=>!x.classList.contains('revealed'));if(next){next.classList.add('revealed');return true}if([12,18].includes(current)){const x=$$('[data-gap]',s).find(i=>!i.value);if(x){x.value=gwAns[x.dataset.gap];x.classList.add('is-correct');return true}}return false}
function snapshot(){const s=$(`.slide[data-slide="${current}"]`);return {slide:current,fields:$$('input,select,textarea',s).map((x,i)=>({name:x.name||x.dataset.gap||x.dataset.open||`field${i}`,value:x.value})).filter(x=>x.value),selected:$$('.selected',s).map(x=>x.textContent.trim())}}
function submit(){const response=snapshot();if(!response.fields.length&&!response.selected.length)return false;try{parent.postMessage({type:'e-leap:learning-event',event:{eventId:`u22-${Date.now()}`,eventType:'response.submitted',resourceId:'res-objective-first-b2-u02-l02',activityId:`u22-s${String(current).padStart(2,'0')}`,occurredAt:new Date().toISOString(),context:{role:new URLSearchParams(location.search).get('eleapRole')||'student'},payload:{response,grading:lastAssessment}}},location.origin)}catch(_){}return true}
function caps(){const auto=$(`.slide[data-slide="${current}"]`)?.dataset.auto==='true';return {check:auto,reset:true,reveal:auto,submit:auto||[3,6,9,20].includes(current),score:auto,assessable:auto}}
$('#localCheck').onclick=check;$('#localReset').onclick=reset;$('#localReveal').onclick=reveal;window.ELEAP_LESSON_HOST_API={getMode(){return document.documentElement.dataset.eleapMode||'student'},setMode(m){document.documentElement.dataset.eleapMode=m;return true},getActivityState(){return {activityId:`u22-s${String(current).padStart(2,'0')}`,response:snapshot(),assessment:lastAssessment,capabilities:caps()}},command(a){if(a==='check')return check();if(a==='reset')return reset();if(a==='reveal')return reveal();if(a==='submit')return submit();return false}};const p=new URLSearchParams(location.search);if(p.get('eleapHosted')==='1'){document.documentElement.dataset.eleapHosted='1';document.documentElement.dataset.eleapRole=p.get('eleapRole')||'guest';document.documentElement.dataset.eleapMode=p.get('eleapMode')||'normal'}show(1)})();
