(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let current=1,lastAssessment=null,edIndex=0,teacherPaceLocked=false; const total=21,slides=$$('.slide');
const norm=s=>String(s||'').trim().toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g,' ').replace(/[.!?]+$/,'');
const gapAnswers={gw1:'is becoming',gw2:'are creating',gw3:'are updating',gw4:'means',gw5:'submits',gw6:'is adding',gw7:'sounds',gw8:'believes',gw9:'is encouraging',gw10:'is changing',gw11:'find out',gw12:'google',wf1:'accessible',wf2:'applications',wf3:'ability',wf4:'impressive',wf5:'electronically',wf6:'tricky',ex4a1:'finish',ex4a2:'get',ex4b1:'is improving',ex4c1:'are dealing with',ex4d1:'flies',ex4d2:'explodes',ex4d3:'hit',ex4e1:'is developing',ex4f1:'take',ex4g1:'log on',ex4g2:'requires',ex4g3:'generates',ex4h1:'crashes',ex4h2:'lose',ex4h3:'are working',ex4h4:'save'};
function row(label,opts,ans,name){return `<div class="row" data-answer="${ans}"><span>${label}</span><select name="${name}"><option value="">Choose…</option>${opts.map(o=>`<option value="${o}">${o}</option>`).join('')}</select></div>`}
$('#tenseSort').innerHTML=[['a · jogs','Present Simple'],['b · are gathering','Present Continuous'],['c · resets','Present Simple'],['d · are becoming','Present Continuous']].map((x,i)=>row(x[0],['Present Simple','Present Continuous'],x[1],`ts${i}`)).join('');
$('#ruleQuiz').innerHTML=[['Permanent / habitual / repeated','Present Simple'],['Temporary / changing / developing','Present Continuous']].map((x,i)=>row(x[0],['Present Simple','Present Continuous'],x[1],`rule${i}`)).join('');
const funcs=[['a','near-future arrangement'],['b','zero conditional'],['c','action happening now'],['d','time clause'],['e','general truth']]; $('#functionMatch').innerHTML=funcs.map((x,i)=>row(x[0],funcs.map(y=>y[1]),x[1],`fn${i}`)).join('');
const errors=[
 ['Electronic books are becoming more and more popular.','Correct','Electronic books are becoming more and more popular.'],
 ['This week only, the shop sells all software at 20% off.','Incorrect','This week only, the shop is selling all software at 20% off.'],
 ["Don’t shut down the computer as I’m downloading a film.",'Correct',"Don’t shut down the computer as I’m downloading a film."],
 ['As soon as you are playing this game, you realise the graphics are tremendous.','Incorrect','As soon as you play this game, you realise the graphics are tremendous.'],
 ["My neighbour gives me access to his wifi this week but I’m planning to install my own on Monday.",'Incorrect',"My neighbour is giving me access to his wifi this week but I’m planning to install my own on Monday."],
 ['When you visit the website, you are getting a choice of free downloadable applications.','Incorrect','When you visit the website, you get a choice of free downloadable applications.'],
 ["Once I find a useful site, I’m bookmarking it for future reference.",'Incorrect','Once I find a useful site, I bookmark it for future reference.']
];
function renderED(){const e=errors[edIndex];$('#edCounter').textContent=`Sentence ${edIndex+1} / ${errors.length}`;$('#errorDetective').innerHTML=`<div class="round-card" data-answer="${e[1]}" data-correction="${e[2].replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"><p>${e[0]}</p><div class="round-options"><button data-v="Correct">Correct</button><button data-v="Incorrect">Incorrect</button></div><input class="line-input" id="edCorrection" placeholder="If incorrect, type the corrected sentence"></div>`;$$('.round-options button',$('#errorDetective')).forEach(b=>b.onclick=()=>{$$('.round-options button',$('#errorDetective')).forEach(x=>x.classList.remove('selected'));b.classList.add('selected')})}
renderED(); $('#edPrev').onclick=()=>{edIndex=Math.max(0,edIndex-1);renderED()}; $('#edNext').onclick=()=>{edIndex=Math.min(errors.length-1,edIndex+1);renderED()};
$('#gwRead').innerHTML=[['Why is googlewhacking becoming more difficult?','Because new and updated web pages create more Google entries.'],['What happens when someone submits a googlewhack to a website?','It creates or adds another entry.'],['Why does Gary Stock consider it meaningful?','It encourages people to surf the web and discover unusual things.']].map((x,i)=>`<div class="prompt-card"><b>${i+1}</b><span>${x[0]}</span></div><textarea class="response" data-open="read${i}"></textarea><div class="teacher-answer">${x[1]}</div>`).join('');
const sa=[['like','state'],['believe','state'],['taste','state'],['run','action'],['teach','action'],['take a photo','action'],['have','state'],['play','action']]; $('#stateAction').innerHTML=sa.map(([w,a])=>`<div class="class-item" data-answer="${a}"><b>${w}</b><div class="class-actions"><button data-v="state">STATE</button><button data-v="action">ACTION</button></div></div>`).join('');
const meanings=[['BE','You are mean. / Why are you being so mean today?'],['HAVE','I have three kids. / I’m having a wonderful day.'],['SEE','Oh, I see. / Are you seeing anyone at the moment?'],['THINK','I think doing yoga is fun. / I’m thinking about doing a first-aid course.'],['TASTE','This chocolate tastes like strawberries. / They are tasting wedding cakes today.']]; $('#meaningQuiz').innerHTML=meanings.map(x=>`<div class="meaning-card"><h3>${x[0]}</h3><p>${x[1]}</p><select data-answer="state / action"><option value="">Choose…</option><option>state / action</option><option>action / state</option></select></div>`).join('');
$('#wordFamily').innerHTML=[['true →','truth / true / truly'],['happy →','happiness / unhappy / happily'],['possible →','possibility / possible / impossible']].map(x=>`<div class="row" data-answer="${x[1]}"><span>${x[0]}</span><input placeholder="Build the family"></div>`).join('');
$('#adjectiveBuild').innerHTML=[['trick','tricky'],['mess','messy'],['mud','muddy'],['ice','icy']].map(x=>`<div class="row" data-answer="${x[1]}"><span>${x[0]} →</span><input placeholder="Type adjective"></div>`).join('');
const pn=[['accessible','positive'],['colourful','positive'],['dull','negative'],['excellent','positive'],['favourable','positive'],['hopeless','negative'],['impressive','positive'],['mindless','negative'],['sophisticated','positive'],['tricky','negative'],['unhelpful','negative']]; $('#posNeg').innerHTML=pn.map(([w,a])=>`<div class="class-item" data-answer="${a}"><b>${w}</b><div class="class-actions"><button data-v="positive">POSITIVE</button><button data-v="negative">NEGATIVE</button></div></div>`).join('');
$('#exitQuiz').innerHTML=[['Games of this type ___ more complex now.',['become','are becoming'],'are becoming'],['I ___ this game is excellent.',['think','am thinking'],'think'],['We ___ a new computer next weekend.',['buy','are buying'],'are buying'],['mud →',['mudy','muddy'],'muddy'],['possible → negative form',['unpossible','impossible'],'impossible'],['This tablet is very ___.',['impress','impressive'],'impressive']].map((x,i)=>row(x[0],x[1],x[2],`exit${i}`)).join('');
function bindChoices(root=document){$$('.class-actions',root).forEach(g=>g.onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('button',g).forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected');g.parentElement.dataset.value=e.target.dataset.v});$$('.choice-row',root).forEach(g=>g.onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('button',g).forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected');g.dataset.value=e.target.textContent.trim()})} bindChoices();
$$('.tab').forEach(b=>b.onclick=()=>{const grp=b.dataset.tabgroup;$$(`.tab[data-tabgroup="${grp}"]`).forEach(x=>x.classList.toggle('active',x===b));$$(`[data-tabpane^="${grp}:"]`).forEach(x=>x.classList.toggle('active',x.dataset.tabpane===`${grp}:${b.dataset.tab}`))});
const videoSets={
 gaming:['/u2.2/gaming-leadin.mp4'],
 present:['/u2.2/present-tenses/part-00.mp4','/u2.2/present-tenses/part-01.mp4','/u2.2/present-tenses/part-02.mp4','/u2.2/present-tenses/part-03.mp4'],
 state:['/u2.2/stative-action/part-00.mp4','/u2.2/stative-action/part-01.mp4','/u2.2/stative-action/part-02.mp4']
};
function mediaCandidates(path){const wrappers=['','/U2.2_UPLOAD_02_MEDIA','/U2.2_UPLOAD_03_MEDIA','/U2.2_UPLOAD_04A_MEDIA','/U2.2_UPLOAD_04B_MEDIA','/U2.2_UPLOAD_05_MEDIA','/U2.2_UPLOAD_06_MEDIA','/E-LEAP_U2.2_INTERACTIVE_READY_PATCH'];return wrappers.map(w=>`${w}${path}`)}
function initVideo(v){const key=v.dataset.videoKey,parts=videoSets[key]||[],status=$(`[data-video-status="${key}"]`),nav=$(`[data-segments="${key}"]`);let idx=0,candidate=0;function setStatus(t,error=false){if(!status)return;status.classList.toggle('error',error);status.textContent=t}function load(i,autoplay=false){if(!parts[i])return;idx=i;candidate=0;loadCandidate(autoplay)}function loadCandidate(autoplay=false){const list=mediaCandidates(parts[idx]);if(candidate>=list.length){setStatus(`Video media is missing for ${parts[idx]}. Upload the media folder to the repository root.`,true);return}const src=list[candidate];v.src=src;v.load();setStatus(parts.length>1?`Video ${idx+1}/${parts.length} · loading…`:'Video loading…');if(autoplay)v.play().catch(()=>{})}if(nav){nav.innerHTML=parts.map((_,i)=>`<button type="button">Part ${i+1}</button>`).join('');$$('button',nav).forEach((b,i)=>b.onclick=()=>load(i,false))}v.addEventListener('loadedmetadata',()=>{setStatus(parts.length>1?`Video ${idx+1} of ${parts.length} ready`:'Video ready');if(nav)$$('button',nav).forEach((b,j)=>b.classList.toggle('active',j===idx))});v.addEventListener('ended',()=>{if(idx<parts.length-1)load(idx+1,true)});v.addEventListener('error',()=>{candidate++;loadCandidate(false)});if(parts.length)load(0,false)} $$('video[data-video-key]').forEach(initVideo);
function show(n){current=Math.max(1,Math.min(total,n));slides.forEach(s=>s.classList.toggle('active',+s.dataset.slide===current));$('#counter').textContent=`${current} / ${total}`;$('#bar').style.width=`${current/total*100}%`;$('#prev').disabled=teacherPaceLocked||current===1;$('#next').disabled=teacherPaceLocked||current===total;lastAssessment=null;$$('video').forEach(v=>{if(!v.closest('.slide.active'))v.pause()})} $('#prev').onclick=()=>{if(!teacherPaceLocked)show(current-1)}; $('#next').onclick=()=>{if(!teacherPaceLocked)show(current+1)};
function markRows(s){let totalCount=0,answeredCount=0,correctCount=0;$$('.row[data-answer]',s).forEach(x=>{totalCount++;const el=$('select,input',x),v=el?.value||'',ok=norm(v)===norm(x.dataset.answer);if(v)answeredCount++;if(ok){correctCount++;x.classList.add('is-correct')}else{x.classList.remove('is-correct');if(v)x.classList.add('is-wrong');else x.classList.remove('is-wrong')}});return {totalCount,answeredCount,correctCount,wrongCount:answeredCount-correctCount,unansweredCount:totalCount-answeredCount,score:totalCount?correctCount/totalCount*100:null}}
function check(){const s=$(`.slide[data-slide="${current}"]`);let totalCount=0,answeredCount=0,correctCount=0;const add=(answered,correct)=>{totalCount++;if(answered)answeredCount++;if(correct)correctCount++};$$('.row[data-answer]',s).forEach(x=>{const el=$('select,input',x),v=el?.value||'',ok=!!v&&norm(v)===norm(x.dataset.answer);add(!!v,ok);x.classList.toggle('is-correct',ok);x.classList.toggle('is-wrong',!!v&&!ok)});$$('.choice-row[data-answer]',s).forEach(g=>{const v=g.dataset.value||'',ok=!!v&&norm(v)===norm(g.dataset.answer);add(!!v,ok);$$('button',g).forEach(b=>{b.classList.toggle('is-correct',norm(b.textContent)===norm(g.dataset.answer)&&!!v);b.classList.toggle('is-wrong',b.classList.contains('selected')&&!ok)})});$$('.class-item[data-answer]',s).forEach(x=>{const v=x.dataset.value||'',ok=!!v&&norm(v)===norm(x.dataset.answer);add(!!v,ok);x.classList.toggle('is-correct',ok);x.classList.toggle('is-wrong',!!v&&!ok)});$$('select[data-answer]',s).forEach(x=>{const v=x.value||'',ok=!!v&&norm(v)===norm(x.dataset.answer);add(!!v,ok);x.classList.toggle('is-correct',ok);x.classList.toggle('is-wrong',!!v&&!ok)});$$('input[data-gap]',s).forEach(x=>{const ans=gapAnswers[x.dataset.gap],v=x.value||'',ok=!!v&&norm(v)===norm(ans);add(!!v,ok);x.classList.toggle('is-correct',ok);x.classList.toggle('is-wrong',!!v&&!ok)});if(current===10){const card=$('.round-card',s),sel=$('.round-options .selected',card),v=sel?.dataset.v||sel?.textContent||'',ok=!!v&&norm(v)===norm(card.dataset.answer);add(!!v,ok);$$('.round-options button',card).forEach(b=>{const right=norm(b.dataset.v||b.textContent)===norm(card.dataset.answer);b.classList.toggle('answer-correct',right);b.classList.toggle('answer-wrong',b===sel&&!right)});const correction=$('#edCorrection',card);if(norm(card.dataset.answer)==='incorrect'&&correction?.value){correction.classList.toggle('is-correct',norm(correction.value)===norm(errors[edIndex][2]));correction.classList.toggle('is-wrong',norm(correction.value)!==norm(errors[edIndex][2]))}$('.teacher-answer',card)?.classList.add('revealed')}lastAssessment={totalCount,answeredCount,correctCount,wrongCount:answeredCount-correctCount,unansweredCount:totalCount-answeredCount,score:totalCount?correctCount/totalCount*100:null};return true}
function reset(){const s=$(`.slide[data-slide="${current}"]`);$$('input,textarea',s).forEach(x=>x.value='');$$('select',s).forEach(x=>x.value='');$$('.selected,.is-correct,.is-wrong,.revealed,.answer-filled,.answer-correct,.answer-wrong',s).forEach(x=>x.classList.remove('selected','is-correct','is-wrong','revealed','answer-filled','answer-correct','answer-wrong'));$$('.inline-answer',s).forEach(x=>x.remove());$$('[data-value]',s).forEach(x=>delete x.dataset.value);$$('[data-answer-revealed]',s).forEach(x=>delete x.dataset.answerRevealed);lastAssessment=null;return true}
function setDirectAnswer(el,ans){if(!el)return false;el.value=ans;el.classList.add('answer-filled');el.dataset.answerRevealed='1';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));return true}
function revealDirect(s){const gap=$$('input[data-gap]',s).find(x=>!x.dataset.answerRevealed);if(gap){const ans=gapAnswers[gap.dataset.gap];if(ans)return setDirectAnswer(gap,ans)}for(const x of $$('.row[data-answer]',s)){const el=$('select,input',x);if(el&&!el.dataset.answerRevealed)return setDirectAnswer(el,x.dataset.answer)}const sel=$$('select[data-answer]',s).find(x=>!x.dataset.answerRevealed);if(sel)return setDirectAnswer(sel,sel.dataset.answer);for(const x of $$('.class-item[data-answer]',s)){if(x.dataset.answerRevealed)continue;const btn=$$('.class-actions button',x).find(b=>norm(b.dataset.v||b.textContent)===norm(x.dataset.answer));if(btn){$$('.class-actions button',x).forEach(b=>b.classList.remove('selected','answer-correct'));btn.classList.add('selected','answer-correct');x.dataset.value=btn.dataset.v||btn.textContent.trim();x.dataset.answerRevealed='1';return true}}for(const g of $$('.choice-row[data-answer]',s)){if(g.dataset.answerRevealed)continue;const btn=$$('button',g).find(b=>norm(b.textContent)===norm(g.dataset.answer));if(btn){$$('button',g).forEach(b=>b.classList.remove('selected','answer-correct'));btn.classList.add('selected','answer-correct');g.dataset.value=btn.textContent.trim();g.dataset.answerRevealed='1';return true}}if(current===10){const card=$('.round-card',s);if(card&&!card.dataset.answerRevealed){const target=$$('.round-options button',card).find(b=>norm(b.dataset.v||b.textContent)===norm(card.dataset.answer));$$('.round-options button',card).forEach(b=>b.classList.remove('selected','answer-correct'));if(target)target.classList.add('selected','answer-correct');const inp=$('#edCorrection',card);if(inp){inp.value=card.dataset.correction||'';inp.classList.add('answer-filled')}card.dataset.answerRevealed='1';return true}}return false}
function reveal(){const s=$(`.slide[data-slide="${current}"]`);if(revealDirect(s))return true;const next=$$('.teacher-answer',s).find(x=>!x.classList.contains('revealed'));if(next){next.classList.add('revealed');return true}return false}
function snapshot(){const s=$(`.slide[data-slide="${current}"]`);return {slide:current,fields:$$('input,select,textarea',s).map((x,i)=>({name:x.name||x.dataset.gap||x.dataset.open||`field${i}`,value:x.value})).filter(x=>x.value),selected:$$('.selected',s).map(x=>x.textContent.trim())}}
function submit(){const response=snapshot();if(!response.fields.length&&!response.selected.length)return false;try{parent.postMessage({type:'e-leap:learning-event',event:{eventId:`u22-${Date.now()}`,eventType:'response.submitted',resourceId:'res-objective-first-b2-u02-l02',activityId:`u22-s${String(current).padStart(2,'0')}`,occurredAt:new Date().toISOString(),context:{role:new URLSearchParams(location.search).get('eleapRole')||'student'},payload:{response,grading:lastAssessment}}},location.origin)}catch(_){}return true}
function hasReveal(s){return !!($('.teacher-answer',s)||$('input[data-gap]',s)||$('.row[data-answer]',s)||$('.class-item[data-answer]',s)||$('.choice-row[data-answer]',s)||$('select[data-answer]',s)||current===10)} function isAssessable(s){return !!($('.row[data-answer]',s)||$('.choice-row[data-answer]',s)||$('.class-item[data-answer]',s)||$('select[data-answer]',s)||$('input[data-gap]',s)||current===10)}
function caps(){const s=$(`.slide[data-slide="${current}"]`),auto=isAssessable(s);return {check:auto,reset:true,reveal:hasReveal(s),submit:auto||!!$('textarea,input[data-open]',s),score:auto,assessable:auto}}
$('#localCheck').onclick=check;$('#localReset').onclick=reset;$('#localReveal').onclick=reveal;
window.ELEAP_LESSON_HOST_API={getMode(){return document.documentElement.dataset.eleapMode||'student'},setMode(m){document.documentElement.dataset.eleapMode=m;return true},getActivityState(){return {activityId:`u22-s${String(current).padStart(2,'0')}`,response:snapshot(),assessment:lastAssessment,capabilities:caps()}},goToActivity(activityId){const m=String(activityId||'').match(/u22-s(\d+)/);if(!m)return false;show(Number(m[1]));return true},setNavigationLocked(locked){teacherPaceLocked=!!locked;show(current);return true},command(a){const key=String(a||'').toLowerCase().replace(/[_\s]/g,'-');if(key==='check')return check();if(key==='reset')return reset();if(['reveal','show-answer','showanswer'].includes(key))return reveal();if(key==='submit')return submit();return false}};
const p=new URLSearchParams(location.search);if(p.get('eleapHosted')==='1'){document.documentElement.dataset.eleapHosted='1';document.documentElement.dataset.eleapRole=p.get('eleapRole')||'guest';document.documentElement.dataset.eleapMode=p.get('eleapMode')||'normal'}show(1);
})();
