(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const slides=$$('.slide'), total=slides.length; let current=1,lastAssessment=null,lastWheel=null,teacherPaceLocked=false;
const reviewQs=[
{n:1,type:'mcq',q:'Although both games are aimed at experienced players, Cyber Quest is ___ more demanding because its puzzles require considerably more strategic planning.',opts:['very','far','absolutely','completely'],a:'far',e:'far + comparative adjective shows a large difference in degree.'},
{n:2,type:'mcq',q:'The latest version is only ___ more expensive than the previous one, so the small increase in price is unlikely to discourage regular players.',opts:['highly','slightly','completely','by far'],a:'slightly',e:'slightly + comparative adjective shows a small difference.'},
{n:3,type:'mcq',q:'Game A is ___ as visually impressive as Game B, although its movement is a little less realistic.',opts:['almost','much','far','completely'],a:'almost',e:'almost as … as means the two things are very similar, but not completely equal.'},
{n:4,type:'mcq',q:'The beginner version is not nearly as challenging as the advanced edition. Which meaning is closest?',opts:['It is slightly harder.','They are equally difficult.','The advanced edition is considerably more challenging.','The advanced edition is marginally easier.'],a:'The advanced edition is considerably more challenging.',e:'not nearly as … as expresses a large difference between the two items.'},
{n:5,type:'mcq',q:'Of the four games reviewed, Mind Maze is ___ the most intellectually demanding because players receive almost no guidance.',opts:['much','by far','slightly','almost'],a:'by far',e:'by far commonly intensifies a superlative: by far the most …'},
{n:6,type:'text',q:'Correct the error: This multiplayer version is very more engaging than the original.',a:'This multiplayer version is much more engaging than the original.',alts:['This multiplayer version is far more engaging than the original.'],e:'Use much/far, not very, before a comparative adjective.'},
{n:7,type:'text',q:'Rewrite using “not nearly as”: The updated version is much easier to navigate than the original.',a:'The original is not nearly as easy to navigate as the updated version.',e:'The transformation reverses the comparison while preserving the large difference.'},
{n:8,type:'mcq',q:'Although Game A is ___ cheaper and has almost as many features as Game B, it is not nearly as sophisticated in terms of graphics.',opts:['very','considerably','absolutely','totally'],a:'considerably',e:'considerably + comparative adjective expresses a substantial difference.'}];
const reviews={
r1:{title:'Review 1',text:`The great thing about this game is that to get anywhere, you need to adopt its unique way of thinking – forget all normal rules. Reality is meaningless here, in a world where up can mean down, left becomes right, and everything feels remarkably weird. The puzzles can’t be solved unless you are willing to spend sufficient thinking time – and you need to keep an open mind! Part of the game’s charm lies in the almost complete absence of instructions, yet this can also be a drawback, leading to huge frustration. There are no set paths to wander down and you are very much guided by your own curiosity and imagination. And while you’re gathering your thoughts, you can enjoy the background music, which is truly original and builds well in scary moments. Patience is definitely required for this game, but there’s great satisfaction for those who rise to the challenge.`,verdict:'Expect the unexpected – and make full use of your brainpower! · £39.99'},
r2:{title:'Review 2',text:`This game’s all about finding power for your ray gun, which you get by capturing tiny cartoon figures. The ray’s pretty weak when you start – it needs electricity after all – so you only move small objects. This gives you enough power to turn on household appliances like fridges or vacuum cleaners, and locate the electrically charged critters hiding in them. You feel pretty hopeless to begin with, but ten minutes and several hundred hits later, you reach the point of feeling more like a superhero as the adventure develops. You overturn sofas, beds and other huge items, leaving rooms in a very messy state. And that’s nothing! In higher levels, you walk the streets, so powerful that you can lift cars, trucks and eventually entire buildings. It’s a shame that the gun resets to weak with each new level, but there are some impressive gameplay touches that stop you mindlessly breaking stuff – your grandma would approve!`,verdict:'A great sense of progression as you go from weak to strong – never thought electricity could be so much fun! · £28.75'},
r3:{title:'Review 3',text:`Did you know that car games have a poor relation? Yes, it’s their motorbike cousins! Somehow motorbike games never provide the same thrill as car games, but this version comes very close and is easily the best available. There are eight different bikes, nine long tracks and a choice of race styles: Grand Prix or the muddy scrambling type, which gets quite tricky. The intelligence and speed of your 23 computer opponents are high, and guarantee a game demanding enough for the most advanced racer. So get on your bikes and take control!`,verdict:'A super-slick bike racer that truly does not disappoint. · £27.50'},
r4:{title:'Review 4',text:`This game is not demanding, perhaps because it’s primarily aimed at kids under ten, though with only six levels and no multi-player mode, it’s likely to be a bit disappointing even for the youngest of players. The little guy jogs along endlessly at a slow rate, which gets extremely boring at times. Jumping works OK, with a nice double-jump facility for things that are out of reach. Graphically, the game looks good with its bright and colourful cartoony feel, and occasionally there’s some really nice background animation too. It’s just too bad there isn’t more content – games of this type are becoming more and more complex, but not this one! Even kids will get through most of it in an afternoon, as the puzzles and tasks are far too simple.`,verdict:'Simplistic gameplay suitable for a very young audience. · £17.99'}};
function esc(v){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function qcard(q){return `<div class="qcard" data-q="${q.n}" data-answer="${esc(q.a)}" data-evidence="${esc(q.e||'')}"><div class="qnum">${q.n}</div><p>${esc(q.q)}</p>${q.type==='mcq'?`<div class="qopts">${q.opts.map((o,i)=>`<label><input type="radio" name="q${q.n}" value="${esc(o)}"><span class="option-letter">${String.fromCharCode(65+i)}</span>${esc(o)}</label>`).join('')}</div>`:`<input class="text-answer" data-textq="${q.n}" placeholder="Type your answer">`}<div class="inline-evidence"></div></div>`}
$('#q1to4').innerHTML=reviewQs.slice(0,4).map(qcard).join(''); $('#q5to8').innerHTML=reviewQs.slice(4).map(qcard).join('');
const pros=[['Entertainment – fun and enjoyment in free time','good'],['Relaxation – reduce stress','good'],['Social connection – communicate and make friends','good'],['Improve skills – problem-solving, teamwork and quick thinking','good'],['Convenience – access games anywhere with an Internet connection','good'],['Addiction – gaming addiction','bad'],['Time-consuming – takes time from study, work or other activities','bad'],['Health problems – eye strain, lack of exercise and sleep problems','bad'],['Social isolation – less face-to-face interaction','bad'],['Money and dependency – overspending on in-game items / relying on gaming','bad']];
function shuffled(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function wireClassActions(root=document){$$('.class-actions',root).forEach(g=>{g.onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('button',g).forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected');g.parentElement.dataset.value=e.target.dataset.v}})}
function renderProsCons(){const good=shuffled(pros.filter(x=>x[1]==='good')),bad=shuffled(pros.filter(x=>x[1]==='bad')),mixed=[];let g=0,b=0,turn=Math.random()<.5?'good':'bad';while(g<good.length||b<bad.length){if(turn==='good'&&g<good.length)mixed.push(good[g++]);else if(turn==='bad'&&b<bad.length)mixed.push(bad[b++]);else if(g<good.length)mixed.push(good[g++]);else if(b<bad.length)mixed.push(bad[b++]);turn=turn==='good'?'bad':'good'}$('#prosConsSource').innerHTML=mixed.map(([x])=>`<li>${esc(x.split(' – ')[0])}</li>`).join('');$('#prosCons').innerHTML=mixed.map(([x,a])=>`<div class="class-item" data-answer="${a}"><b>${x}</b><div class="class-actions"><button data-v="good">Good thing</button><button data-v="bad">Disadvantage</button></div></div>`).join('');wireClassActions($('#prosCons'))}
renderProsCons();
const chains=[{idea:'Social connection',why:['Players communicate and cooperate with other people online.','Games always cost a lot of money.','All games have easy puzzles.'],wa:0,res:['This can help them practise teamwork and make friends.','This makes every game violent.','This removes the need to study.'],ra:0},{idea:'Addiction',why:['Some players spend excessive amounts of time gaming.','Every game has excellent graphics.','Games are always free.'],wa:0,res:['Study time and face-to-face interaction may decrease.','Players automatically become programmers.','The Internet becomes faster.'],ra:0}];
$('#ideaChains').innerHTML=chains.map((c,i)=>`<div class="chain-card"><b>${c.idea}</b><label>WHY?<select data-part="why">${['Choose…',...c.why].map((x,j)=>`<option value="${j-1}">${esc(x)}</option>`).join('')}</select></label><label>RESULT / EXAMPLE<select data-part="res">${['Choose…',...c.res].map((x,j)=>`<option value="${j-1}">${esc(x)}</option>`).join('')}</select></label></div>`).join('');
const features=['fast pace','easy to get into','lots of action','puzzles to solve','single- and multi-player modes','suitable for all ages','great background music','sophisticated graphics'];
$('#features').innerHTML=features.map((x,i)=>`<label><input type="checkbox" value="${esc(x)}"> ${String.fromCharCode(97+i)}. ${esc(x)}</label>`).join(''); $('#features').onchange=()=>{$('#featureCount').textContent=`${$$('input:checked',$('#features')).length} / 5 selected`};
const scanTips=[['Skimming','Get a general idea of what each review is about.'],['Scanning','Look for particular words or information without reading every line.'],['Price','Scan the verdict line at the foot of each review.'],['Stars / verdict','Scan the verdict quickly for evaluation and suitability clues.']];
$('#scanTips').innerHTML=scanTips.map(([a,b])=>`<div class="reveal-card"><b>${a}</b><p>${b}</p></div>`).join(''); $$('.reveal-card').forEach(x=>x.onclick=()=>x.classList.toggle('open'));
const evidenceDefs=[
 {n:1,key:'r4',sentence:'Simplistic gameplay suitable for a very young audience. · £17.99'},
 {n:2,key:'r3',sentence:'Somehow motorbike games never provide the same thrill as car games, but this version comes very close and is easily the best available.'},
 {n:3,key:'r4',sentence:'This game is not demanding, perhaps because it’s primarily aimed at kids under ten, though with only six levels and no multi-player mode, it’s likely to be a bit disappointing even for the youngest of players.'},
 {n:4,key:'r1',sentence:'And while you’re gathering your thoughts, you can enjoy the background music, which is truly original and builds well in scary moments.'}
];
function markSentence(text,sentence){if(!sentence)return esc(text);const i=text.indexOf(sentence);if(i<0)return esc(text);return esc(text.slice(0,i))+`<mark class="evidence-highlight">${esc(sentence)}</mark>`+esc(text.slice(i+sentence.length))}
function renderReview(target,key,highlight=''){const r=reviews[key];let body=markSentence(r.text,highlight);let verdict=esc(r.verdict);if(highlight&&r.verdict.includes(highlight))verdict=markSentence(r.verdict,highlight);$(target).innerHTML=`<h3>${r.title}</h3><p>${body}</p><div class="verdict">THE VERDICT · ${verdict}</div>`}
function setActiveTab(id,key){$$('button',$(id)).forEach(x=>x.classList.toggle('active',x.dataset.tab===key))}
function wireTabs(id,target){const box=$(id); $$('button',box).forEach(b=>b.onclick=()=>{$$('button',box).forEach(x=>x.classList.remove('active'));b.classList.add('active');renderReview(target,b.dataset.tab)}); renderReview(target,'r1')}
function wireEvidenceButtons(containerId,tabsId,target){const box=$(containerId);box.innerHTML=evidenceDefs.map(x=>`<button data-ev="${x.n}">Evidence ${x.n}</button>`).join('');$$('button',box).forEach(b=>b.onclick=()=>{const ev=evidenceDefs.find(x=>x.n===+b.dataset.ev);$$('button',box).forEach(x=>x.classList.toggle('active',x===b));setActiveTab(tabsId,ev.key);renderReview(target,ev.key,ev.sentence)})}
wireTabs('#reviewTabs','#reviewSource'); wireTabs('#evidenceTabs','#evidenceSource');wireEvidenceButtons('#reviewEvidenceButtons','#reviewTabs','#reviewSource');wireEvidenceButtons('#evidenceEvidenceButtons','#evidenceTabs','#evidenceSource');
const skimMap={r1:{type:'Puzzle / thinking game',good:'Unique / challenging',bad:'Frustrating / little guidance'},r2:{type:'Action / power game',good:'Strong progression / growing power',bad:'Gun resets to weak'},r3:{type:'Motorbike racing game',good:'Variety / challenging opponents',bad:'Can get quite tricky'},r4:{type:"Children's platform game",good:'Bright graphics / double jump',bad:'Too short / too simple'}};
function renderSkimActivity(key){renderReview('#skimSource',key);const m=skimMap[key];$('#gameType').dataset.answer=m.type;$('#gameType').value='';$('#gameType').classList.remove('answer-filled','answer-correct','answer-wrong');delete $('#gameType').dataset.revealed;$('#skimEval').innerHTML=[['Good point',[m.good,'Original soundtrack','Eight bikes','Bright graphics'],m.good],['Bad point',[m.bad,'Excellent instructions','Long gameplay','Advanced multiplayer'],m.bad]].map((x,i)=>rowSelect(x[0],x[1],x[2],`sk${i}`)).join('')}
const skimTabs=$('#skimTabs');$$('button',skimTabs).forEach(b=>b.onclick=()=>{$$('button',skimTabs).forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSkimActivity(b.dataset.tab)});renderSkimActivity('r1');
const scan=[['a. Which review is the cheapest?',['Review 1','Review 2','Review 3','Review 4'],'Review 4'],['b. Which review gives the strongest overall recommendation?',['Review 1','Review 2','Review 3','Review 4'],'Review 3'],['c. Which game seems least suitable for adults?',['Review 1','Review 2','Review 3','Review 4'],'Review 4'],['d. Which review praises the soundtrack most strongly?',['Review 1','Review 2','Review 3','Review 4'],'Review 1']];
function scanRow(question,opts,ans,name,label='Review'){return `<div class="row scan-row" data-answer="${esc(ans)}"><div class="scan-question">${esc(question)}</div><div class="scan-answer-line"><span>${label}</span><select name="${name}"><option value="">Choose…</option>${opts.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select></div></div>`}
$('#scanQuiz').innerHTML=scan.map((x,i)=>scanRow(x[0],x[1],x[2],`scan${i}`)).join('');
const evidenceQuestions=scan.map(x=>x[0]);
const evid=[
 ['£17.99 in The Verdict',evidenceQuestions,evidenceQuestions[0]],
 ['“easily the best available”',evidenceQuestions,evidenceQuestions[1]],
 ['aimed at kids under ten',evidenceQuestions,evidenceQuestions[2]],
 ["background music is 'truly original'",evidenceQuestions,evidenceQuestions[3]]
];
$('#evidenceQuiz').innerHTML=evid.map((x,i)=>scanRow(x[0],x[1],x[2],`ev${i}`,'Question')).join('');
const gb=[['Review 1 · Unique way of thinking','good'],['Review 1 · Almost no instructions; can be frustrating','bad'],['Review 2 · A great sense of progression','good'],['Review 2 · The gun resets to weak with each new level','bad'],['Review 3 · Eight different bikes and nine long tracks','good'],['Review 3 · Can get quite tricky','bad'],['Review 4 · Bright and colourful graphics','good'],['Review 4 · Only six levels and no multi-player mode','bad']];
$('#goodBad').innerHTML=gb.map(([x,a])=>`<div class="class-item" data-answer="${a}"><b>${x}</b><div class="class-actions"><button data-v="good">Good point</button><button data-v="bad">Bad point</button></div></div>`).join('');
const col=[['puzzles','solve'],['a crime','solve'],['a problem','solve'],['your time','spend'],['a fortune','spend'],['money','spend'],['the point (of)','reach'],['a conclusion','reach'],['a goal','reach'],['control','take'],['advantage of','take'],['an interest in','take']];
function collocRow(noun,verb,i){return `<div class="row colloc-row" data-answer="${verb}"><select name="co${i}"><option value="">Verb…</option>${['solve','spend','reach','take'].map(o=>`<option value="${o}">${o}</option>`).join('')}</select><span>${esc(noun)}</span></div>`}
$('#collocations').innerHTML=col.map((x,i)=>collocRow(x[0],x[1],i)).join('');
wireTabs('#collocTabs','#collocSource');
const forms=[['easily','easy'],['endlessly','endless'],['graphically','graphic'],['remarkably','remarkable'],['truly','true']]; $('#adverbForms').innerHTML=forms.map((x,i)=>`<div class="row" data-answer="${x[1]}"><span>${x[0]} →</span><input data-free="form${i}" placeholder="related adjective"></div>`).join('');
const meaning=[['hardly',['with a lot of effort','almost not / almost never','recently','after the expected time'],'almost not / almost never'],['hard',['with a lot of effort','almost not / almost never','recently','after the expected time'],'with a lot of effort'],['lately',['with a lot of effort','almost not / almost never','recently','after the expected time'],'recently'],['late',['with a lot of effort','almost not / almost never','recently','after the expected time'],'after the expected time']]; $('#adverbMeaning').innerHTML=meaning.map((x,i)=>rowSelect(x[0],x[1],x[2],`am${i}`)).join('');
const corpus=[['Unfortunatelly','Unfortunately'],['definitly','definitely'],['automaticly','automatically'],['immediatly','immediately'],['realy','really'],['extremly','extremely'],['especialy','especially'],['completly','completely']]; $('#corpusRounds').innerHTML=corpus.map((x,i)=>`<div class="row" data-answer="${x[1]}"><span>${i+1}. ${x[0]}</span><input placeholder="Correct spelling"></div>`).join('');
function rowSelect(label,opts,ans,name,evidence=''){return `<div class="row" data-answer="${esc(ans)}" data-evidence="${esc(evidence)}"><span>${label}</span><select name="${name}"><option value="">Choose…</option>${opts.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select><div class="inline-evidence"></div></div>`}
wireClassActions();
$$('.bridge-options').forEach(g=>g.onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('button',g).forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected');g.dataset.value=e.target.textContent.trim()});
$('#opinionPoll').onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('button',$('#opinionPoll')).forEach(b=>b.classList.remove('selected'));e.target.classList.add('selected')};
function show(n){current=Math.max(1,Math.min(total,n));slides.forEach(s=>s.classList.toggle('active',+s.dataset.slide===current));$('#counter').textContent=`${current} / ${total}`;$('#bar').style.width=`${current/total*100}%`;$('#prev').disabled=teacherPaceLocked||current===1;$('#next').disabled=teacherPaceLocked||current===total;lastAssessment=null;window.scrollTo(0,0)} $('#prev').onclick=()=>{if(!teacherPaceLocked)show(current-1)}; $('#next').onclick=()=>{if(!teacherPaceLocked)show(current+1)};
function normalize(s){return String(s||'').trim().toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g,' ').replace(/[.!?]+$/,'')}
function checkReviewRange(start,end){let correct=0,answered=0;for(const q of reviewQs.filter(x=>x.n>=start&&x.n<=end)){const card=$(`.qcard[data-q="${q.n}"]`);let val=q.type==='mcq'?($(`input[name="q${q.n}"]:checked`,card)?.value||''):($(`[data-textq="${q.n}"]`,card)?.value||'');if(val)answered++;const ok=normalize(val)===normalize(q.a)||(q.alts||[]).some(a=>normalize(val)===normalize(a));card.classList.toggle('is-correct',ok&&!!val);card.classList.toggle('is-wrong',!!val&&!ok);if(q.type==='mcq'){$$('.qopts label',card).forEach(l=>{l.classList.remove('selected-correct','selected-wrong');const inp=$('input',l);if(inp?.checked)l.classList.add(ok?'selected-correct':'selected-wrong')})}if(ok)correct++}return scoreObj(end-start+1,answered,correct)}
function addEvidence(el,text){if(!text)return;let box=$('.inline-evidence',el);if(!box){box=document.createElement('div');box.className='inline-evidence';el.appendChild(box)}box.textContent=`Evidence: ${text}`;box.classList.add('show')}
function fillAnswer(el){const ans=el.dataset.answer||'';const control=$('select,input',el);if(control){control.value=ans;control.classList.add('answer-filled')}if(el.classList.contains('class-item')){const btn=$$('.class-actions button',el).find(b=>b.dataset.v===ans);btn?.classList.add('answer-correct')}addEvidence(el,el.dataset.evidence||'');el.dataset.revealed='1';return true}
function scoreObj(totalC,answered,correct){return {totalCount:totalC,answeredCount:answered,correctCount:correct,wrongCount:answered-correct,unansweredCount:totalC-answered,score:totalC?correct/totalC*100:null}}
function genericCheck(){const s=$(`.slide[data-slide="${current}"]`);if(current===3)return checkReviewRange(1,4);if(current===4)return checkReviewRange(5,8);let totalC=0,answered=0,correct=0;
 if(current===5){const g=$('.bridge-options',s);totalC=1;const v=g.dataset.value||'';if(v)answered++;if(v===g.dataset.answer)correct++;$$('button',g).forEach(b=>{b.classList.toggle('is-correct',b.textContent.trim()===g.dataset.answer&&v);b.classList.toggle('is-wrong',b.classList.contains('selected')&&b.textContent.trim()!==g.dataset.answer)});if(v===g.dataset.answer)$('.feedback',s).classList.remove('hidden')}
 else if([7,14].includes(current)){$$('.class-item',s).forEach(x=>{totalC++;const v=x.dataset.value||'';if(v)answered++;const ok=v===x.dataset.answer;if(ok)correct++;x.classList.toggle('is-correct',ok&&!!v);x.classList.toggle('is-wrong',!!v&&!ok)})}
 else if(current===8){$$('.chain-card',s).forEach((x,i)=>{totalC+=2;const a=$('select[data-part="why"]',x).value,b=$('select[data-part="res"]',x).value;if(a!=='-1')answered++;if(b!=='-1')answered++;if(+a===chains[i].wa)correct++;if(+b===chains[i].ra)correct++})}
 else if([11,12,13,15,16,17].includes(current)){const rows=$$('.row',s);rows.forEach(x=>{totalC++;const el=$('select,input',x);const v=el?.value||'';if(v)answered++;const ok=normalize(v)===normalize(x.dataset.answer);if(ok)correct++;x.classList.toggle('is-correct',ok&&!!v);x.classList.toggle('is-wrong',!!v&&!ok)});if(current===13){const gt=$('#gameType');totalC++;const v=gt.value||'';if(v)answered++;const ok=normalize(v)===normalize(gt.dataset.answer);if(ok)correct++;gt.classList.toggle('answer-correct',ok&&!!v);gt.classList.toggle('answer-wrong',!!v&&!ok)}}
 else return null; return scoreObj(totalC,answered,correct)}
function check(){lastAssessment=genericCheck();return !!lastAssessment}
function reset(){const s=$(`.slide[data-slide="${current}"]`);$$('input',s).forEach(i=>{if(i.type==='radio'||i.type==='checkbox')i.checked=false;else i.value=''});$$('select',s).forEach(x=>x.value='');$$('textarea',s).forEach(x=>x.value='');$$('.selected,.is-correct,.is-wrong,.open,.answer-filled,.answer-correct,.answer-wrong,.selected-correct,.selected-wrong',s).forEach(x=>x.classList.remove('selected','is-correct','is-wrong','open','answer-filled','answer-correct','answer-wrong','selected-correct','selected-wrong'));$$('[data-value]',s).forEach(x=>delete x.dataset.value);$$('[data-revealed]',s).forEach(x=>delete x.dataset.revealed);$$('.inline-evidence',s).forEach(x=>{x.textContent='';x.classList.remove('show')});if(current===5)$('.feedback',s)?.classList.add('hidden');if(current===7)renderProsCons();if(current===11){const key=$('#reviewTabs button.active')?.dataset.tab||'r1';renderReview('#reviewSource',key)}if(current===12){const key=$('#evidenceTabs button.active')?.dataset.tab||'r1';renderReview('#evidenceSource',key)}if(current===18)$('#homeworkSuggestions')?.classList.add('hidden');$$('.evidence-strip button',s).forEach(b=>b.classList.remove('active'));lastAssessment=null;return true}
function reveal(){const s=$(`.slide[data-slide="${current}"]`);
if([3,4].includes(current)){const card=$$('.qcard',s).find(x=>!x.dataset.revealed);if(!card)return false;const q=reviewQs.find(x=>x.n===+card.dataset.q);if(q.type==='mcq'){const inp=$$(`input[name="q${q.n}"]`,card).find(i=>i.value===q.a);if(inp){inp.checked=true;inp.closest('label')?.classList.add('answer-correct')}}else{const inp=$(`[data-textq="${q.n}"]`,card);inp.value=q.a;inp.classList.add('answer-filled')}addEvidence(card,q.e);card.dataset.revealed='1';return true}
if(current===5){const g=$('.bridge-options',s),btn=$$('button',g).find(b=>b.textContent.trim()===g.dataset.answer);if(btn){btn.classList.add('answer-correct');g.dataset.value=g.dataset.answer;$('.feedback',s)?.classList.remove('hidden');return true}return false}
if([7,14].includes(current)){const item=$$('.class-item',s).find(x=>!x.dataset.revealed);if(!item)return false;const btn=$$('.class-actions button',item).find(b=>b.dataset.v===item.dataset.answer);btn?.classList.add('answer-correct');item.dataset.value=item.dataset.answer;item.dataset.revealed='1';return true}
if(current===8){const card=$$('.chain-card',s).find(x=>!x.dataset.revealed);if(!card)return false;const i=$$('.chain-card',s).indexOf(card);const a=$('select[data-part="why"]',card),b=$('select[data-part="res"]',card);a.value=String(chains[i].wa);b.value=String(chains[i].ra);a.classList.add('answer-filled');b.classList.add('answer-filled');card.dataset.revealed='1';return true}
if(current===13&&!$('#gameType').dataset.revealed){$('#gameType').value=$('#gameType').dataset.answer;$('#gameType').classList.add('answer-filled');$('#gameType').dataset.revealed='1';return true}
if(current===18){const box=$('#homeworkSuggestions');if(!box||!box.classList.contains('hidden'))return false;box.classList.remove('hidden');return true}
if([11,12,13,15,16,17].includes(current)){const row=$$('.row',s).find(x=>!x.dataset.revealed);if(row)return fillAnswer(row)}
return false}
function snapshot(){const s=$(`.slide[data-slide="${current}"]`);return {slide:current,inputs:$$('input,select,textarea',s).map((x,i)=>({name:x.name||x.dataset.free||x.dataset.textq||`field${i}`,type:x.type||x.tagName.toLowerCase(),value:(x.type==='checkbox'||x.type==='radio')?x.checked?x.value:'':x.value})).filter(x=>x.value!==''),selected:$$('.selected',s).map(x=>x.textContent.trim())}}
function submit(){const response=snapshot();if(!response.inputs.length&&!response.selected.length)return false;const payload={type:'e-leap:learning-event',event:{eventId:`u21-${Date.now()}`,eventType:'response.submitted',resourceId:'res-objective-first-b2-u02-l01',activityId:`u21-s${String(current).padStart(2,'0')}`,occurredAt:new Date().toISOString(),context:{role:new URLSearchParams(location.search).get('eleapRole')||'student'},payload:{response,grading:lastAssessment}}};try{parent.postMessage(payload,location.origin)}catch(_){}return true}
$('#localCheck').onclick=()=>check();$('#localReset').onclick=()=>reset();$('#localReveal').onclick=()=>reveal();
$('#spin').onclick=()=>{const n=Math.floor(Math.random()*8)+1;lastWheel=n;const spins=4+n/8;$('#wheel').style.transform=`rotate(${spins*360}deg)`;$('#wheelResult').textContent='Spinning…';setTimeout(()=>{$('#wheelResult').textContent=`Question ${n}`;show(n<=4?3:4);setTimeout(()=>{$(`.qcard[data-q="${n}"]`)?.classList.add('highlight')},50)},1650)};
function caps(){const auto=$(`.slide[data-slide="${current}"]`)?.dataset.auto==='true';return {check:auto,reset:true,reveal:[3,4,5,7,8,11,12,13,14,15,16,17,18].includes(current),submit:[6,9,18].includes(current)||auto,score:auto,assessable:auto}}
window.ELEAP_LESSON_HOST_API={getMode(){return document.documentElement.dataset.eleapMode||'student'},setMode(m){document.documentElement.dataset.eleapMode=m;return true},getActivityState(){return {activityId:`u21-s${String(current).padStart(2,'0')}`,response:snapshot(),assessment:lastAssessment,capabilities:caps()}},goToActivity(activityId){const m=String(activityId||'').match(/u21-s(\d+)/);if(!m)return false;show(Number(m[1]));return true},setNavigationLocked(locked){teacherPaceLocked=!!locked;show(current);return true},command(action){if(action==='check')return check();if(action==='reset')return reset();if(action==='reveal')return reveal();if(action==='submit')return submit();return false}};
const p=new URLSearchParams(location.search);if(p.get('eleapHosted')==='1'){document.documentElement.dataset.eleapHosted='1';document.documentElement.dataset.eleapRole=p.get('eleapRole')||'guest';document.documentElement.dataset.eleapMode=p.get('eleapMode')||'normal';try{parent.postMessage({type:'e-leap:request-runtime-context'},location.origin)}catch(_){}} window.addEventListener('message',e=>{if(e.origin!==location.origin)return;if(e.data?.type==='e-leap:runtime-context'){document.documentElement.dataset.eleapRole=e.data.context.role||'guest';document.documentElement.dataset.eleapMode=e.data.context.mode||'normal'}}); show(1);
})();
