import {platform,programs,systemModules} from './data/catalog.js';
import {objectivesB1} from './data/objectives-b1-unit1.js';
import {progressStore} from './services/progress.js';

const app=document.querySelector('#app');
let page='home';
let currentLesson=null;
let currentActivity=null;
let lessonMode='teacher';
let teacherSlide=0;
let teacherReveal=false;
let privateMediaMap={};
let privateMediaFiles=new Map();
let privateMediaLoaded=false;
const dataByProgram={'objectives-b1':objectivesB1};

function shell(content){
  app.innerHTML=`<div class="shell"><aside class="side"><div class="brand">${platform.name}<small>${platform.subtitle}</small></div><div class="nav">
  <button data-nav="home" class="${page==='home'?'active':''}">Dashboard</button><button data-nav="courses" class="${page==='courses'?'active':''}">Courses</button><button data-nav="skills" class="${page==='skills'?'active':''}">Skills Lab</button><button data-nav="exam" class="${page==='exam'?'active':''}">Exam Center</button><button data-nav="progress" class="${page==='progress'?'active':''}">My Progress</button><button data-nav="teacher" class="${page==='teacher'?'active':''}">Teacher</button>
  </div></aside><main class="main"><div class="topbar"><div><b>E-LEAP v0.7</b><div class="muted small">Classroom Delivery + Self-study trong cùng một lesson</div></div><span class="pill">Research-ready architecture</span></div>${content}<div class="footer-note">E-LEAP Prototype v0.7 · Một nguồn nội dung, hai cách sử dụng: GV dạy trên lớp và HV tự học.</div></main></div>`;
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{page=b.dataset.nav;currentLesson=null;currentActivity=null;render()});
}
function home(){const p=progressStore.load();return `<section class="hero"><div><h1>Học liệu, đánh giá và tiến bộ trong một platform</h1><p>E-LEAP dùng chung một nguồn bài giảng cho Classroom Delivery và Student Self-study. Objectives B1 được giữ lại; Objectives B2 · Objective First sẽ là course ưu tiên.</p></div><div class="metric"><span>Đã hoàn thành</span><strong>${p.completed.length}</strong><span>hoạt động trên thiết bị này</span></div></section><h2 class="section-title">Programs</h2><div class="grid">${programs.map(courseCard).join('')}</div><h2 class="section-title">Core modules</h2><div class="module-list">${systemModules.map(x=>`<div class="card module"><b>${x.title}</b><p>${x.desc}</p></div>`).join('')}</div>`}
function courseCard(c){return `<div class="card course" data-course="${c.id}"><span class="tag ${c.status==='planned'?'future':''}">${c.status==='active'?'Đang xây':'Sẵn chỗ để thêm'}</span><h3>${c.title}</h3><p><b>${c.audience}</b><br>${c.description}</p><div class="open-hint">Mở course →</div></div>`}
function courses(){return `<h1>Courses</h1><p class="muted">Mỗi giáo trình là một course trong cùng E-LEAP.</p><div class="grid">${programs.map(courseCard).join('')}</div>`}
function program(id){const d=dataByProgram[id];if(!d)return `<button class="btn ghost back" data-nav="courses">← Courses</button><div class="card"><h2>Module đã được chừa sẵn</h2><p>Khi có tài liệu, chỉ thêm dữ liệu course; không tạo website mới.</p></div>`;return `<button class="btn ghost back" data-nav="courses">← Courses</button><h1>${d.title} · ${d.classGroup}</h1>${d.units.map(u=>`<div class="card"><span class="tag">${u.totalPeriods} tiết</span><h2>${u.title}</h2><p class="muted">${u.sourceNote}</p><div class="lesson-list">${u.lessons.map((l,i)=>`<div class="card lesson"><div class="num">${i+1}</div><div><b>${l.title}</b><div class="muted small">${l.periods} tiết · ${l.teacherScreens?l.teacherScreens.length+' classroom screens · ':''}${l.sections.length} self-study sections</div></div><button class="btn secondary" data-lesson="${l.id}" data-program="${id}" data-unit="${u.id}">Mở bài</button></div>`).join('')}</div><button class="btn" data-quiz="${u.id}" data-program="${id}">Quick Check</button></div>`).join('')}`}

function modeSelector(){
  return `<div class="lesson-mode-selector"><div class="mode-selector-title"><b>Chọn cách sử dụng bài học</b><span class="muted small">Cùng một nội dung, 3 cách dùng</span></div><div class="mode-options">
    <button class="mode-option ${lessonMode==='teacher'?'active':''}" data-mode="teacher"><span class="mode-icon">👩‍🏫</span><span><b>Dạy trên lớp</b><small>GV điều khiển bài giảng, Reveal answer, Next/Previous</small></span></button>
    <button class="mode-option ${lessonMode==='student'?'active':''}" data-mode="student"><span class="mode-icon">📚</span><span><b>Tự học</b><small>HV học theo chặng, làm bài, tự chấm và lưu tiến độ</small></span></button>
    <button class="mode-option ${lessonMode==='presentation'?'active':''}" data-mode="presentation"><span class="mode-icon">🖥️</span><span><b>Trình chiếu</b><small>Phóng lớn bài giảng để chiếu trên lớp, ẩn phần điều hướng thừa</small></span></button>
  </div></div>`;
}
function richLine(x){
  const t=String(x||'');
  return t
    .replace(/\b(play|do|go|always|usually|often|sometimes|never|like \+ -ing|a kind of)\b/gi,'<strong class="keyword">$1</strong>')
    .replace(/“([^”]+)”/g,'<em class="quote">“$1”</em>');
}
function slideMediaFiles(s){
  const names=privateMediaMap[`slide${s.slide}`]||[];
  const uniq=[...new Set(names)];
  return uniq.map(name=>({name,file:privateMediaFiles.get(name)})).filter(x=>x.file);
}
function mediaPanel(s){
  if(!s.mediaKey&&!s.visualNote&&!privateMediaMap[`slide${s.slide}`])return '';
  const loaded=slideMediaFiles(s);
  if(loaded.length){
    const items=loaded.map(({name,file})=>{const url=URL.createObjectURL(file);const type=(file.type||'').toLowerCase();
      if(type.startsWith('video/'))return `<div class="slide-media"><video controls playsinline src="${url}"></video><div class="slide-media-name">${name}</div></div>`;
      if(type.startsWith('audio/'))return `<div class="slide-media"><audio controls src="${url}"></audio><div class="slide-media-name">${name}</div></div>`;
      if(type.startsWith('image/')||/\.(png|jpe?g|svg|webp)$/i.test(name))return `<div class="slide-media"><img src="${url}" alt="Media slide ${s.slide}"><div class="slide-media-name">${name}</div></div>`;
      return '';
    }).join('');
    return `<div class="media-player-grid">${items}</div>`;
  }
  const label=s.mediaType==='video'?'Video':s.mediaType==='audio'?'Audio':'Hình ảnh / media';
  return `<div class="protected-media"><div class="media-icon">${s.mediaType==='video'?'▶':s.mediaType==='audio'?'♫':'▧'}</div><div><b>${label}</b><p>${s.mediaCaption||s.visualNote||'Media từ PPT gốc.'}</p><span class="media-lock">🔒 Media chưa nạp trên thiết bị này.</span><div><button class="btn secondary" data-load-media>Nạp Media Pack riêng</button></div><div class="media-help">Chọn thư mục <b>e-leap-unit1-1-media-private</b>. File chỉ được đọc cục bộ trong phiên này, không upload lên GitHub.</div></div></div>`;
}
function teacherModeView(pid,uid,lid,l,isPresentation=false){
  const screens=l.teacherScreens||[];
  if(!screens.length)return `<div class="callout">Lesson này chưa có Classroom Delivery screens.</div>`;
  const s=screens[teacherSlide]||screens[0];
  const revealed=Number(sessionStorage.getItem('eleap-reveal-step')||0);
  const answers=s.answers||[];
  const answerBlock=answers.length&&teacherReveal?`<div class="teacher-answer animated-answer"><h3>Answer / Suggested response</h3>${answers.map((x,i)=>`<div class="answer-line reveal-item ${i<revealed?'shown':''}" style="--delay:${i*70}ms">${richLine(x)}</div>`).join('')}<div class="reveal-tools"><button class="btn secondary" data-reveal-next ${revealed>=answers.length?'disabled':''}>Hiện tiếp</button><button class="btn ghost" data-reveal-all>Hiện tất cả</button></div></div>`:'';
  const special=s.slide===9?`<div class="warmup-board"><div class="warmup-title">GUESS THE SPORT</div><div class="tile-grid">${Array.from({length:10},(_,i)=>`<button class="reveal-tile" data-tile>${i+1}</button>`).join('')}</div><p class="muted small">Nhấp từng ô để mô phỏng hiệu ứng lộ dần hình trong PPT.</p></div>`:'';
  return `<div class="teacher-stage ${isPresentation?'presentation-stage':''}">
    <div class="teacher-stage-head"><div><span class="tag">${isPresentation?'TRÌNH CHIẾU':'DẠY TRÊN LỚP'}</span><b> Màn hình ${teacherSlide+1}/${screens.length}</b></div><div class="toolbar media-loader">${privateMediaLoaded?'<span class="media-loaded">✓ Media Pack đã nạp</span>':'<button class="btn secondary" data-load-media>📁 Nạp Media Pack</button>'}${isPresentation?`<button class="btn ghost" data-mode="teacher">↙ Thoát trình chiếu</button>`:`<button class="btn ghost" data-mode="presentation">🖥️ Trình chiếu</button><button class="btn secondary" data-mode="student">📚 Tự học</button>`}</div></div><input id="private-media-input" type="file" webkitdirectory directory multiple hidden>
    <div class="teacher-screen slide-enter">
      <div class="slide-kicker">PPT source · Slide ${s.slide}</div><h2>${richLine(s.title)}</h2>
      ${(s.body||[]).map((x,i)=>`<p class="screen-line" style="--line:${i}">${richLine(x)}</p>`).join('')}
      ${special}
      ${s.prompt?`<div class="teacher-prompt"><b>Teacher / Student task</b><p>${richLine(s.prompt)}</p></div>`:''}
      ${mediaPanel(s)}
      ${answers.length?`<button class="btn reveal-btn" data-reveal>${teacherReveal?'Ẩn đáp án':'Reveal answers'}</button>`:''}
      ${answerBlock}
    </div>
    <div class="teacher-controls"><button class="btn ghost" data-prev-slide ${teacherSlide===0?'disabled':''}>← Trước</button><div class="slide-progress"><span style="width:${((teacherSlide+1)/screens.length)*100}%"></span></div><button class="btn" data-next-slide ${teacherSlide===screens.length-1?'disabled':''}>Tiếp →</button></div>
    <details class="slide-index"><summary>Mở danh sách ${screens.length} màn hình</summary><div class="screen-grid">${screens.map((x,i)=>`<button class="screen-jump ${i===teacherSlide?'active':''}" data-jump-slide="${i}">${x.slide}. ${x.title}</button>`).join('')}</div></details>
  </div>`;
}
function studentModeView(pid,uid,lid,l){const p=progressStore.load();return `<div class="mode-bar"><div><span class="tag">TỰ HỌC</span> Học theo chặng, tự làm và lưu tiến độ.</div><button class="btn secondary" data-mode="teacher">👩‍🏫 Dạy trên lớp</button></div><div class="layout2"><div>${l.sections.map((s,i)=>{const sid=`${lid}:${i}`;const done=p.completed.includes(sid);return `<div class="card activity lesson-step"><div class="step-index">${i+1}</div><div class="step-main"><span class="tag">${s.type.toUpperCase()}</span><h3>${s.title}</h3><p>${s.summary}</p><div class="toolbar activity-actions"><button class="btn" data-open-activity="${i}" data-program="${pid}" data-unit="${uid}" data-lesson-id="${lid}">Mở nội dung</button><button class="btn ${done?'secondary':'ghost'}" data-complete="${sid}">${done?'✓ Đã hoàn thành':'Đánh dấu hoàn thành'}</button></div></div></div>`}).join('')}</div><aside><div class="card sticky-card"><h3>Self-study map</h3><p>${l.sections.map((s,i)=>`${i+1}. ${s.title}`).join('<br>')}</p></div><div class="card"><h3>Workflow</h3><p>Learn → Practice → Submit → Auto-mark/Teacher review → Progress.</p></div></aside></div>`}
function lessonView(pid,uid,lid){const u=dataByProgram[pid].units.find(x=>x.id===uid);const l=u.lessons.find(x=>x.id===lid);const outcomes=l.outcomes?`<details class="outcomes-box"><summary>Learning outcomes</summary><div class="outcome-grid"><div class="card"><h3>Knowledge</h3><ul class="learning-list">${l.outcomes.knowledge.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="card"><h3>Skills</h3><ul class="learning-list">${l.outcomes.skills.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="card"><h3>Attitudes</h3><ul class="learning-list">${l.outcomes.attitudes.map(x=>`<li>${x}</li>`).join('')}</ul></div></div></details>`:'';const content=lessonMode==='student'?studentModeView(pid,uid,lid,l):teacherModeView(pid,uid,lid,l,lessonMode==='presentation');return `<button class="btn ghost back" data-course="${pid}">← ${u.title}</button><h1>${l.title}</h1><p class="muted">${u.title} · ${l.periods} tiết</p>${modeSelector()}${outcomes}${content}`}
function responseWorkspace(s,sid){
  const saved=localStorage.getItem('eleap-draft:'+sid)||'';
  const typing=['writing','assignment','practice','language','grammar','learn','review','listening'].includes(s.type);
  const recorder=['speaking','audio'].includes(s.type);
  const text=typing?`<div class="response-box"><div class="response-head"><b>Your response</b><span class="muted small">Tự động lưu trên thiết bị</span></div><textarea data-draft="${sid}" rows="7" placeholder="Type your answer here...">${saved}</textarea><div class="response-tools"><button class="btn secondary" data-save-draft="${sid}">Lưu câu trả lời</button><button class="btn ghost" data-precheck="${sid}">Automated pre-check</button><button class="btn ai-btn" data-ai-feedback="${sid}">✨ AI feedback</button></div><div class="draft-feedback" data-draft-feedback="${sid}"></div></div>`:'';
  const audio=recorder?`<div class="response-box recorder-box"><div class="response-head"><b>Record your answer</b><span class="muted small">Dùng microphone của điện thoại/máy tính</span></div><div class="record-controls"><button class="btn record-btn" data-record-start="${sid}">● Bắt đầu ghi âm</button><button class="btn ghost" data-record-stop="${sid}" disabled>■ Dừng</button><span class="record-status" data-record-status="${sid}">Chưa ghi âm</span></div><audio controls data-record-playback="${sid}" class="audio" hidden></audio><div class="response-tools"><button class="btn ai-btn" data-ai-feedback="${sid}">✨ AI feedback</button></div></div>`:'';
  return text+audio;
}
function activityView(pid,uid,lid,index){const u=dataByProgram[pid].units.find(x=>x.id===uid);const l=u.lessons.find(x=>x.id===lid);const s=l.sections[Number(index)];const sid=`${lid}:${index}`;const done=progressStore.load().completed.includes(sid);const checklist=s.checkList?`<div class="card"><h3>Listening / checking prompts</h3><ul class="learning-list">${s.checkList.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:'';const mini=s.miniQuiz?`<div class="card inline-quiz"><h3>Check now</h3><div data-mini-root="${sid}">${s.miniQuiz.map((q,qi)=>`<div class="mini-q" data-mini-q="${qi}"><b>${qi+1}. ${q.q}</b>${q.options.map((o,oi)=>`<label class="option"><input type="radio" name="mini-${sid}-${qi}" value="${oi}"> ${o}</label>`).join('')}<div class="mini-feedback"></div></div>`).join('')}<button class="btn" data-check-mini="${sid}" data-program="${pid}" data-unit="${uid}" data-lesson-id="${lid}" data-activity-index="${index}">Kiểm tra đáp án</button></div></div>`:'';return `<button class="btn ghost back" data-back-lesson="1">← ${l.title}</button><div class="activity-head"><span class="tag">${s.type.toUpperCase()}</span><h1>${s.title}</h1><p class="lead">${s.intro||s.summary}</p></div><div class="content-grid"><div class="card"><h3>Điểm cần nắm</h3><ul class="learning-list">${(s.keyPoints||[]).map(x=>`<li>${richLine(x)}</li>`).join('')}</ul></div><div class="card"><h3>Ví dụ / đáp án mẫu</h3>${(s.examples||[]).map(x=>`<div class="example-box">${richLine(x)}</div>`).join('')}</div></div>${checklist}${mini}<div class="card task-card"><h3>Try it / nhiệm vụ học viên</h3><p>${s.task||'Thực hành theo hướng dẫn của giáo viên.'}</p>${responseWorkspace(s,sid)}</div><div class="toolbar" style="margin-top:16px"><button class="btn ${done?'secondary':''}" data-complete="${sid}">${done?'✓ Đã hoàn thành':'Đánh dấu hoàn thành'}</button><button class="btn ghost" data-back-lesson="1">Quay lại Lesson</button></div>`}
function quizView(pid,uid){const u=dataByProgram[pid].units.find(x=>x.id===uid);return `<button class="btn ghost back" data-course="${pid}">← ${u.title}</button><div class="card"><h1>${u.quiz.title}</h1><p class="muted">Bài mẫu để kiểm tra engine chấm tự động.</p><form id="quiz">${u.quiz.questions.map((x,i)=>`<div class="quiz-q"><b>${i+1}. ${x.q}</b>${x.options.map((o,j)=>`<label class="option"><input type="radio" name="${x.id}" value="${j}"> ${o}</label>`).join('')}</div>`).join('')}<button class="btn" type="submit">Nộp bài</button></form><div id="quiz-result"></div></div>`}
function generic(title,desc){return `<h1>${title}</h1><div class="card"><p>${desc}</p><div class="callout small">Module này đã có vị trí trong kiến trúc. Sẽ kích hoạt dần mà không đổi URL/platform chính.</div></div>`}
function progress(){const p=progressStore.load();return `<h1>My Progress</h1><div class="grid"><div class="card"><h3>Activities completed</h3><p style="font-size:34px;font-weight:800">${p.completed.length}</p></div><div class="card"><h3>Quiz attempts</h3><p style="font-size:34px;font-weight:800">${p.attempts.length}</p></div></div><h2 class="section-title">Recent attempts</h2><div class="card">${p.attempts.length?p.attempts.map(a=>`<p><b>${a.title}</b> · ${a.score}/${a.total} · ${new Date(a.at).toLocaleString('vi-VN')}</p>`).join(''):'<p class="muted">Chưa có lần làm bài.</p>'}<button class="btn ghost" id="reset-progress">Xóa dữ liệu demo</button></div>`}
function teacher(){return `<h1>Teacher Dashboard</h1><div class="grid"><div class="card"><h3>Classroom Delivery</h3><p>Mở lesson ở chế độ trình chiếu, đi đúng flow bài giảng, Reveal answer khi cần.</p></div><div class="card"><h3>Assignments</h3><p>Chờ kết nối database.</p></div><div class="card"><h3>Review Queue</h3><p>Writing/Speaking submissions.</p></div><div class="card"><h3>Analytics & NCKH</h3><p>Điểm theo kỹ năng, lỗi chung, tiến bộ, time-on-task và dữ liệu ẩn danh.</p></div></div>`}
function render(){let content='';if(currentActivity)content=activityView(...currentActivity);else if(currentLesson)content=lessonView(...currentLesson);else if(page==='home')content=home();else if(page==='courses')content=courses();else if(page.startsWith('program:'))content=program(page.split(':')[1]);else if(page==='skills')content=generic('Skills Lab','Listening · Speaking · Reading · Writing, dùng chung cho nhiều course.');else if(page==='exam')content=generic('Exam Center','VSTEP 4 kỹ năng, progress test, mock test, timer và auto-mark.');else if(page==='progress')content=progress();else content=teacher();shell(content);bind()}
function bind(){
 document.querySelectorAll('[data-course]').forEach(el=>el.onclick=()=>{page='program:'+el.dataset.course;currentLesson=null;currentActivity=null;render()});
 document.querySelectorAll('[data-lesson]').forEach(el=>el.onclick=()=>{currentLesson=[el.dataset.program,el.dataset.unit,el.dataset.lesson];currentActivity=null;lessonMode='teacher';teacherSlide=0;teacherReveal=false;render()});
 document.querySelectorAll('[data-mode]').forEach(el=>el.onclick=async()=>{lessonMode=el.dataset.mode;currentActivity=null;document.body.classList.toggle('presentation-mode',lessonMode==='presentation');render();if(lessonMode==='presentation'){try{await document.documentElement.requestFullscreen?.()}catch(e){}}else if(document.fullscreenElement){try{await document.exitFullscreen?.()}catch(e){}}});
 document.querySelectorAll('[data-prev-slide]').forEach(el=>el.onclick=()=>{teacherSlide=Math.max(0,teacherSlide-1);teacherReveal=false;sessionStorage.setItem('eleap-reveal-step','0');render()});
 document.querySelectorAll('[data-next-slide]').forEach(el=>el.onclick=()=>{const [pid,uid,lid]=currentLesson;const l=dataByProgram[pid].units.find(x=>x.id===uid).lessons.find(x=>x.id===lid);teacherSlide=Math.min((l.teacherScreens||[]).length-1,teacherSlide+1);teacherReveal=false;sessionStorage.setItem('eleap-reveal-step','0');render()});
 document.querySelectorAll('[data-jump-slide]').forEach(el=>el.onclick=()=>{teacherSlide=Number(el.dataset.jumpSlide);teacherReveal=false;sessionStorage.setItem('eleap-reveal-step','0');render()});
 document.querySelectorAll('[data-reveal]').forEach(el=>el.onclick=()=>{teacherReveal=!teacherReveal;sessionStorage.setItem('eleap-reveal-step',teacherReveal?'0':'0');render()});
 document.querySelectorAll('[data-open-activity]').forEach(el=>el.onclick=()=>{currentActivity=[el.dataset.program,el.dataset.unit,el.dataset.lessonId,el.dataset.openActivity];render()});
 document.querySelectorAll('[data-back-lesson]').forEach(el=>el.onclick=()=>{currentActivity=null;render()});
 document.querySelectorAll('[data-complete]').forEach(el=>el.onclick=()=>{progressStore.mark(el.dataset.complete);render()});
 document.querySelectorAll('[data-check-mini]').forEach(el=>el.onclick=()=>{const pid=el.dataset.program,uid=el.dataset.unit,lid=el.dataset.lessonId,idx=Number(el.dataset.activityIndex);const sec=dataByProgram[pid].units.find(x=>x.id===uid).lessons.find(x=>x.id===lid).sections[idx];sec.miniQuiz.forEach((q,qi)=>{const chosen=document.querySelector(`input[name="mini-${lid}:${idx}-${qi}"]:checked`);const fb=document.querySelector(`[data-mini-q="${qi}"] .mini-feedback`);if(!chosen){fb.innerHTML='<span class="muted">Chưa chọn đáp án.</span>';return}const ok=Number(chosen.value)===q.answer;fb.innerHTML=`<div class="result ${ok?'ok':'bad'}">${ok?'✓ Đúng':'✗ Chưa đúng'} · ${q.explain}</div>`;});});
 document.querySelectorAll('[data-quiz]').forEach(el=>el.onclick=()=>{currentLesson=null;currentActivity=null;renderQuizRoute(el.dataset.program,el.dataset.quiz)});
 document.querySelectorAll('[data-reveal-next]').forEach(el=>el.onclick=()=>{const [pid,uid,lid]=currentLesson;const l=dataByProgram[pid].units.find(x=>x.id===uid).lessons.find(x=>x.id===lid);const count=(l.teacherScreens[teacherSlide].answers||[]).length;let n=Number(sessionStorage.getItem('eleap-reveal-step')||0);sessionStorage.setItem('eleap-reveal-step',String(Math.min(count,n+1)));render()});
 document.querySelectorAll('[data-reveal-all]').forEach(el=>el.onclick=()=>{const [pid,uid,lid]=currentLesson;const l=dataByProgram[pid].units.find(x=>x.id===uid).lessons.find(x=>x.id===lid);sessionStorage.setItem('eleap-reveal-step',String((l.teacherScreens[teacherSlide].answers||[]).length));render()});
 document.querySelectorAll('[data-tile]').forEach(el=>el.onclick=()=>el.classList.toggle('open'));
 document.querySelectorAll('[data-draft]').forEach(el=>el.oninput=()=>localStorage.setItem('eleap-draft:'+el.dataset.draft,el.value));
 document.querySelectorAll('[data-save-draft]').forEach(el=>el.onclick=()=>{const ta=document.querySelector(`[data-draft="${el.dataset.saveDraft}"]`);if(ta)localStorage.setItem('eleap-draft:'+el.dataset.saveDraft,ta.value);const fb=document.querySelector(`[data-draft-feedback="${el.dataset.saveDraft}"]`);if(fb)fb.innerHTML='<div class="result ok">✓ Đã lưu trên thiết bị này.</div>';});
 document.querySelectorAll('[data-precheck]').forEach(el=>el.onclick=()=>{const ta=document.querySelector(`[data-draft="${el.dataset.precheck}"]`);const txt=(ta?.value||'').trim();const words=txt?txt.split(/\s+/).length:0;const targets=(txt.match(/\b(always|usually|often|sometimes|never|play|do|go)\b/gi)||[]).length;const fb=document.querySelector(`[data-draft-feedback="${el.dataset.precheck}"]`);if(fb)fb.innerHTML=`<div class="result ${words>=20?'ok':'bad'}">Pre-check: ${words} words · ${targets} target-language items detected. ${words<20?'Hãy phát triển câu trả lời thêm.':'Độ dài ban đầu ổn.'}</div>`;});
 document.querySelectorAll('[data-ai-feedback]').forEach(el=>el.onclick=()=>{const fb=document.querySelector(`[data-draft-feedback="${el.dataset.aiFeedback}"]`)||el.closest('.response-box')?.querySelector('.draft-feedback');const msg='<div class="ai-notice"><b>✨ AI feedback đã có vị trí trong hệ thống.</b><br>Bản GitHub public chưa kết nối AI để tránh lộ API key và dữ liệu học viên. Khi nối backend riêng, nút này sẽ gửi bài/recording để nhận feedback theo rubric.</div>';if(fb)fb.innerHTML=msg;else alert('AI feedback sẽ được kích hoạt sau khi nối backend riêng.');});
 let mediaRecorder=null,recordChunks=[];
 document.querySelectorAll('[data-record-start]').forEach(el=>el.onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};mediaRecorder.onstop=()=>{const blob=new Blob(recordChunks,{type:mediaRecorder.mimeType||'audio/webm'});const url=URL.createObjectURL(blob);const a=document.querySelector(`[data-record-playback="${el.dataset.recordStart}"]`);a.src=url;a.hidden=false;stream.getTracks().forEach(t=>t.stop());document.querySelector(`[data-record-status="${el.dataset.recordStart}"]`).textContent='Đã ghi xong · nghe lại bên dưới';};mediaRecorder.start();el.disabled=true;document.querySelector(`[data-record-stop="${el.dataset.recordStart}"]`).disabled=false;document.querySelector(`[data-record-status="${el.dataset.recordStart}"]`).textContent='Đang ghi âm…';}catch(e){alert('Trình duyệt chưa được cấp quyền microphone.');}});
 document.querySelectorAll('[data-record-stop]').forEach(el=>el.onclick=()=>{if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();el.disabled=true;});
 document.querySelectorAll('[data-load-media]').forEach(el=>el.onclick=()=>document.querySelector('#private-media-input')?.click());
 const mediaInput=document.querySelector('#private-media-input');if(mediaInput)mediaInput.onchange=async e=>{try{const files=[...e.target.files];const mapFile=files.find(f=>f.name==='media-map.json');if(!mapFile){alert('Không thấy media-map.json. Hãy chọn đúng thư mục e-leap-unit1-1-media-private.');return;}privateMediaMap=JSON.parse(await mapFile.text());privateMediaFiles=new Map(files.map(f=>[f.name,f]));privateMediaLoaded=true;render();}catch(err){console.error(err);alert('Chưa đọc được Media Pack.');}};
 const r=document.querySelector('#reset-progress');if(r)r.onclick=()=>{progressStore.reset();render()};
}
function renderQuizRoute(pid,uid){shell(quizView(pid,uid));document.querySelectorAll('[data-course]').forEach(el=>el.onclick=()=>{page='program:'+el.dataset.course;currentLesson=null;currentActivity=null;render()});const form=document.querySelector('#quiz');const u=dataByProgram[pid].units.find(x=>x.id===uid);form.onsubmit=e=>{e.preventDefault();let score=0;const details=[];u.quiz.questions.forEach(q=>{const v=form.elements[q.id].value;const ok=Number(v)===q.answer;if(ok)score++;details.push({q:q.q,ok,explain:q.explain})});progressStore.addAttempt({title:u.quiz.title,score,total:u.quiz.questions.length,at:Date.now()});document.querySelector('#quiz-result').innerHTML=`<div class="result ${score===u.quiz.questions.length?'ok':'bad'}">${score}/${u.quiz.questions.length} đúng</div>${details.map(d=>`<p class="small">${d.ok?'✅':'❌'} ${d.explain}</p>`).join('')}`}}
render();
