import {platform,programs,systemModules} from './data/catalog.js';
import {objectivesB1} from './data/objectives-b1-unit1.js';
import {progressStore} from './services/progress.js';

const app=document.querySelector('#app');
let page='home';
let currentLesson=null;
let currentActivity=null;
let lessonMode='teacher';
let teacherSlide=0;
let teacherReveal=false;
const dataByProgram={'objectives-b1':objectivesB1};

function shell(content){
  app.innerHTML=`<div class="shell"><aside class="side"><div class="brand">${platform.name}<small>${platform.subtitle}</small></div><div class="nav">
  <button data-nav="home" class="${page==='home'?'active':''}">Dashboard</button><button data-nav="courses" class="${page==='courses'?'active':''}">Courses</button><button data-nav="skills" class="${page==='skills'?'active':''}">Skills Lab</button><button data-nav="exam" class="${page==='exam'?'active':''}">Exam Center</button><button data-nav="progress" class="${page==='progress'?'active':''}">My Progress</button><button data-nav="teacher" class="${page==='teacher'?'active':''}">Teacher</button>
  </div></aside><main class="main"><div class="topbar"><div><b>E-LEAP v0.4</b><div class="muted small">Classroom Delivery + Self-study trong cùng một lesson</div></div><span class="pill">Research-ready architecture</span></div>${content}<div class="footer-note">E-LEAP Prototype v0.4 · Một nguồn nội dung, hai cách sử dụng: GV dạy trên lớp và HV tự học.</div></main></div>`;
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{page=b.dataset.nav;currentLesson=null;currentActivity=null;render()});
}
function home(){const p=progressStore.load();return `<section class="hero"><div><h1>Học liệu, đánh giá và tiến bộ trong một platform</h1><p>E-LEAP dùng chung một nguồn bài giảng cho Classroom Delivery và Student Self-study. Objectives B1 được giữ lại; Objectives B2 · Objective First sẽ là course ưu tiên.</p></div><div class="metric"><span>Đã hoàn thành</span><strong>${p.completed.length}</strong><span>hoạt động trên thiết bị này</span></div></section><h2 class="section-title">Programs</h2><div class="grid">${programs.map(courseCard).join('')}</div><h2 class="section-title">Core modules</h2><div class="module-list">${systemModules.map(x=>`<div class="card module"><b>${x.title}</b><p>${x.desc}</p></div>`).join('')}</div>`}
function courseCard(c){return `<div class="card course" data-course="${c.id}"><span class="tag ${c.status==='planned'?'future':''}">${c.status==='active'?'Đang xây':'Sẵn chỗ để thêm'}</span><h3>${c.title}</h3><p><b>${c.audience}</b><br>${c.description}</p><div class="open-hint">Mở course →</div></div>`}
function courses(){return `<h1>Courses</h1><p class="muted">Mỗi giáo trình là một course trong cùng E-LEAP.</p><div class="grid">${programs.map(courseCard).join('')}</div>`}
function program(id){const d=dataByProgram[id];if(!d)return `<button class="btn ghost back" data-nav="courses">← Courses</button><div class="card"><h2>Module đã được chừa sẵn</h2><p>Khi có tài liệu, chỉ thêm dữ liệu course; không tạo website mới.</p></div>`;return `<button class="btn ghost back" data-nav="courses">← Courses</button><h1>${d.title} · ${d.classGroup}</h1>${d.units.map(u=>`<div class="card"><span class="tag">${u.totalPeriods} tiết</span><h2>${u.title}</h2><p class="muted">${u.sourceNote}</p><div class="lesson-list">${u.lessons.map((l,i)=>`<div class="card lesson"><div class="num">${i+1}</div><div><b>${l.title}</b><div class="muted small">${l.periods} tiết · ${l.teacherScreens?l.teacherScreens.length+' classroom screens · ':''}${l.sections.length} self-study sections</div></div><button class="btn secondary" data-lesson="${l.id}" data-program="${id}" data-unit="${u.id}">Mở bài</button></div>`).join('')}</div><button class="btn" data-quiz="${u.id}" data-program="${id}">Quick Check</button></div>`).join('')}`}

function teacherModeView(pid,uid,lid,l){
  const screens=l.teacherScreens||[];
  if(!screens.length)return `<div class="callout">Lesson này chưa có Classroom Delivery screens.</div>`;
  const s=screens[teacherSlide]||screens[0];
  const answerBlock=s.answers&&teacherReveal?`<div class="teacher-answer"><h3>Answer / Suggested response</h3>${s.answers.map(x=>`<div class="answer-line">${x}</div>`).join('')}</div>`:'';
  return `<div class="teacher-stage">
    <div class="teacher-stage-head"><div><span class="tag">CLASSROOM DELIVERY</span><b> Screen ${teacherSlide+1}/${screens.length}</b></div><div class="toolbar"><button class="btn ghost" data-fullscreen>⛶ Toàn màn hình</button><button class="btn secondary" data-mode="student">Self-study view</button></div></div>
    <div class="teacher-screen">
      <div class="slide-kicker">PPT source · Slide ${s.slide}</div><h2>${s.title}</h2>
      ${(s.body||[]).map(x=>`<p class="screen-line">${x}</p>`).join('')}
      ${s.prompt?`<div class="teacher-prompt"><b>Teacher / Student task</b><p>${s.prompt}</p></div>`:''}
      ${s.visualNote?`<div class="media-note">${s.visualNote}</div>`:''}
      ${s.answers?`<button class="btn reveal-btn" data-reveal>${teacherReveal?'Ẩn đáp án':'Reveal answer'}</button>`:''}
      ${answerBlock}
    </div>
    <div class="teacher-controls"><button class="btn ghost" data-prev-slide ${teacherSlide===0?'disabled':''}>← Previous</button><div class="slide-progress"><span style="width:${((teacherSlide+1)/screens.length)*100}%"></span></div><button class="btn" data-next-slide ${teacherSlide===screens.length-1?'disabled':''}>Next →</button></div>
    <details class="slide-index"><summary>Mở danh sách 33 màn hình</summary><div class="screen-grid">${screens.map((x,i)=>`<button class="screen-jump ${i===teacherSlide?'active':''}" data-jump-slide="${i}">${x.slide}. ${x.title}</button>`).join('')}</div></details>
  </div>`;
}
function studentModeView(pid,uid,lid,l){const p=progressStore.load();return `<div class="mode-bar"><div><span class="tag">SELF-STUDY</span> Học theo chặng, tự làm và lưu tiến độ.</div><button class="btn secondary" data-mode="teacher">Classroom Delivery</button></div><div class="layout2"><div>${l.sections.map((s,i)=>{const sid=`${lid}:${i}`;const done=p.completed.includes(sid);return `<div class="card activity lesson-step"><div class="step-index">${i+1}</div><div class="step-main"><span class="tag">${s.type.toUpperCase()}</span><h3>${s.title}</h3><p>${s.summary}</p><div class="toolbar activity-actions"><button class="btn" data-open-activity="${i}" data-program="${pid}" data-unit="${uid}" data-lesson-id="${lid}">Mở nội dung</button><button class="btn ${done?'secondary':'ghost'}" data-complete="${sid}">${done?'✓ Đã hoàn thành':'Đánh dấu hoàn thành'}</button></div></div></div>`}).join('')}</div><aside><div class="card sticky-card"><h3>Self-study map</h3><p>${l.sections.map((s,i)=>`${i+1}. ${s.title}`).join('<br>')}</p></div><div class="card"><h3>Workflow</h3><p>Learn → Practice → Submit → Auto-mark/Teacher review → Progress.</p></div></aside></div>`}
function lessonView(pid,uid,lid){const u=dataByProgram[pid].units.find(x=>x.id===uid);const l=u.lessons.find(x=>x.id===lid);const outcomes=l.outcomes?`<details class="outcomes-box"><summary>Learning outcomes</summary><div class="outcome-grid"><div class="card"><h3>Knowledge</h3><ul class="learning-list">${l.outcomes.knowledge.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="card"><h3>Skills</h3><ul class="learning-list">${l.outcomes.skills.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="card"><h3>Attitudes</h3><ul class="learning-list">${l.outcomes.attitudes.map(x=>`<li>${x}</li>`).join('')}</ul></div></div></details>`:'';return `<button class="btn ghost back" data-course="${pid}">← ${u.title}</button><h1>${l.title}</h1><p class="muted">${u.title} · ${l.periods} tiết</p>${outcomes}${lessonMode==='teacher'?teacherModeView(pid,uid,lid,l):studentModeView(pid,uid,lid,l)}`}
function activityView(pid,uid,lid,index){const u=dataByProgram[pid].units.find(x=>x.id===uid);const l=u.lessons.find(x=>x.id===lid);const s=l.sections[Number(index)];const sid=`${lid}:${index}`;const done=progressStore.load().completed.includes(sid);const checklist=s.checkList?`<div class="card"><h3>Listening / checking prompts</h3><ul class="learning-list">${s.checkList.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:'';const mini=s.miniQuiz?`<div class="card inline-quiz"><h3>Check now</h3><div data-mini-root="${sid}">${s.miniQuiz.map((q,qi)=>`<div class="mini-q" data-mini-q="${qi}"><b>${qi+1}. ${q.q}</b>${q.options.map((o,oi)=>`<label class="option"><input type="radio" name="mini-${sid}-${qi}" value="${oi}"> ${o}</label>`).join('')}<div class="mini-feedback"></div></div>`).join('')}<button class="btn" data-check-mini="${sid}" data-program="${pid}" data-unit="${uid}" data-lesson-id="${lid}" data-activity-index="${index}">Kiểm tra đáp án</button></div></div>`:'';return `<button class="btn ghost back" data-back-lesson="1">← ${l.title}</button><div class="activity-head"><span class="tag">${s.type.toUpperCase()}</span><h1>${s.title}</h1><p class="lead">${s.intro||s.summary}</p></div><div class="content-grid"><div class="card"><h3>Điểm cần nắm</h3><ul class="learning-list">${(s.keyPoints||[]).map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="card"><h3>Ví dụ / đáp án mẫu</h3>${(s.examples||[]).map(x=>`<div class="example-box">${x}</div>`).join('')}</div></div>${checklist}${mini}<div class="card task-card"><h3>Try it / nhiệm vụ học viên</h3><p>${s.task||'Thực hành theo hướng dẫn của giáo viên.'}</p></div><div class="toolbar" style="margin-top:16px"><button class="btn ${done?'secondary':''}" data-complete="${sid}">${done?'✓ Đã hoàn thành':'Đánh dấu hoàn thành'}</button><button class="btn ghost" data-back-lesson="1">Quay lại Lesson</button></div>`}
function quizView(pid,uid){const u=dataByProgram[pid].units.find(x=>x.id===uid);return `<button class="btn ghost back" data-course="${pid}">← ${u.title}</button><div class="card"><h1>${u.quiz.title}</h1><p class="muted">Bài mẫu để kiểm tra engine chấm tự động.</p><form id="quiz">${u.quiz.questions.map((x,i)=>`<div class="quiz-q"><b>${i+1}. ${x.q}</b>${x.options.map((o,j)=>`<label class="option"><input type="radio" name="${x.id}" value="${j}"> ${o}</label>`).join('')}</div>`).join('')}<button class="btn" type="submit">Nộp bài</button></form><div id="quiz-result"></div></div>`}
function generic(title,desc){return `<h1>${title}</h1><div class="card"><p>${desc}</p><div class="callout small">Module này đã có vị trí trong kiến trúc. Sẽ kích hoạt dần mà không đổi URL/platform chính.</div></div>`}
function progress(){const p=progressStore.load();return `<h1>My Progress</h1><div class="grid"><div class="card"><h3>Activities completed</h3><p style="font-size:34px;font-weight:800">${p.completed.length}</p></div><div class="card"><h3>Quiz attempts</h3><p style="font-size:34px;font-weight:800">${p.attempts.length}</p></div></div><h2 class="section-title">Recent attempts</h2><div class="card">${p.attempts.length?p.attempts.map(a=>`<p><b>${a.title}</b> · ${a.score}/${a.total} · ${new Date(a.at).toLocaleString('vi-VN')}</p>`).join(''):'<p class="muted">Chưa có lần làm bài.</p>'}<button class="btn ghost" id="reset-progress">Xóa dữ liệu demo</button></div>`}
function teacher(){return `<h1>Teacher Dashboard</h1><div class="grid"><div class="card"><h3>Classroom Delivery</h3><p>Mở lesson ở chế độ trình chiếu, đi đúng flow bài giảng, Reveal answer khi cần.</p></div><div class="card"><h3>Assignments</h3><p>Chờ kết nối database.</p></div><div class="card"><h3>Review Queue</h3><p>Writing/Speaking submissions.</p></div><div class="card"><h3>Analytics & NCKH</h3><p>Điểm theo kỹ năng, lỗi chung, tiến bộ, time-on-task và dữ liệu ẩn danh.</p></div></div>`}
function render(){let content='';if(currentActivity)content=activityView(...currentActivity);else if(currentLesson)content=lessonView(...currentLesson);else if(page==='home')content=home();else if(page==='courses')content=courses();else if(page.startsWith('program:'))content=program(page.split(':')[1]);else if(page==='skills')content=generic('Skills Lab','Listening · Speaking · Reading · Writing, dùng chung cho nhiều course.');else if(page==='exam')content=generic('Exam Center','VSTEP 4 kỹ năng, progress test, mock test, timer và auto-mark.');else if(page==='progress')content=progress();else content=teacher();shell(content);bind()}
function bind(){
 document.querySelectorAll('[data-course]').forEach(el=>el.onclick=()=>{page='program:'+el.dataset.course;currentLesson=null;currentActivity=null;render()});
 document.querySelectorAll('[data-lesson]').forEach(el=>el.onclick=()=>{currentLesson=[el.dataset.program,el.dataset.unit,el.dataset.lesson];currentActivity=null;lessonMode='teacher';teacherSlide=0;teacherReveal=false;render()});
 document.querySelectorAll('[data-mode]').forEach(el=>el.onclick=()=>{lessonMode=el.dataset.mode;currentActivity=null;render()});
 document.querySelectorAll('[data-prev-slide]').forEach(el=>el.onclick=()=>{teacherSlide=Math.max(0,teacherSlide-1);teacherReveal=false;render()});
 document.querySelectorAll('[data-next-slide]').forEach(el=>el.onclick=()=>{const [pid,uid,lid]=currentLesson;const l=dataByProgram[pid].units.find(x=>x.id===uid).lessons.find(x=>x.id===lid);teacherSlide=Math.min((l.teacherScreens||[]).length-1,teacherSlide+1);teacherReveal=false;render()});
 document.querySelectorAll('[data-jump-slide]').forEach(el=>el.onclick=()=>{teacherSlide=Number(el.dataset.jumpSlide);teacherReveal=false;render()});
 document.querySelectorAll('[data-reveal]').forEach(el=>el.onclick=()=>{teacherReveal=!teacherReveal;render()});
 document.querySelectorAll('[data-fullscreen]').forEach(el=>el.onclick=()=>{document.documentElement.requestFullscreen?.()});
 document.querySelectorAll('[data-open-activity]').forEach(el=>el.onclick=()=>{currentActivity=[el.dataset.program,el.dataset.unit,el.dataset.lessonId,el.dataset.openActivity];render()});
 document.querySelectorAll('[data-back-lesson]').forEach(el=>el.onclick=()=>{currentActivity=null;render()});
 document.querySelectorAll('[data-complete]').forEach(el=>el.onclick=()=>{progressStore.mark(el.dataset.complete);render()});
 document.querySelectorAll('[data-check-mini]').forEach(el=>el.onclick=()=>{const pid=el.dataset.program,uid=el.dataset.unit,lid=el.dataset.lessonId,idx=Number(el.dataset.activityIndex);const sec=dataByProgram[pid].units.find(x=>x.id===uid).lessons.find(x=>x.id===lid).sections[idx];sec.miniQuiz.forEach((q,qi)=>{const chosen=document.querySelector(`input[name="mini-${lid}:${idx}-${qi}"]:checked`);const fb=document.querySelector(`[data-mini-q="${qi}"] .mini-feedback`);if(!chosen){fb.innerHTML='<span class="muted">Chưa chọn đáp án.</span>';return}const ok=Number(chosen.value)===q.answer;fb.innerHTML=`<div class="result ${ok?'ok':'bad'}">${ok?'✓ Đúng':'✗ Chưa đúng'} · ${q.explain}</div>`;});});
 document.querySelectorAll('[data-quiz]').forEach(el=>el.onclick=()=>{currentLesson=null;currentActivity=null;renderQuizRoute(el.dataset.program,el.dataset.quiz)});
 const r=document.querySelector('#reset-progress');if(r)r.onclick=()=>{progressStore.reset();render()};
}
function renderQuizRoute(pid,uid){shell(quizView(pid,uid));document.querySelectorAll('[data-course]').forEach(el=>el.onclick=()=>{page='program:'+el.dataset.course;currentLesson=null;currentActivity=null;render()});const form=document.querySelector('#quiz');const u=dataByProgram[pid].units.find(x=>x.id===uid);form.onsubmit=e=>{e.preventDefault();let score=0;const details=[];u.quiz.questions.forEach(q=>{const v=form.elements[q.id].value;const ok=Number(v)===q.answer;if(ok)score++;details.push({q:q.q,ok,explain:q.explain})});progressStore.addAttempt({title:u.quiz.title,score,total:u.quiz.questions.length,at:Date.now()});document.querySelector('#quiz-result').innerHTML=`<div class="result ${score===u.quiz.questions.length?'ok':'bad'}">${score}/${u.quiz.questions.length} đúng</div>${details.map(d=>`<p class="small">${d.ok?'✅':'❌'} ${d.explain}</p>`).join('')}`}}
render();
