import {platform,programs,systemModules} from './data/catalog.js';
import {objectivesB1} from './data/objectives-b1-unit1.js';
import {progressStore} from './services/progress.js';

const app=document.querySelector('#app');
let page='home';
let currentLesson=null;
const dataByProgram={'objectives-b1':objectivesB1};

function shell(content){
  app.innerHTML=`<div class="shell"><aside class="side"><div class="brand">${platform.name}<small>${platform.subtitle}</small></div><div class="nav">
  <button data-nav="home" class="${page==='home'?'active':''}">Dashboard</button><button data-nav="courses" class="${page==='courses'?'active':''}">Courses</button><button data-nav="skills" class="${page==='skills'?'active':''}">Skills Lab</button><button data-nav="exam" class="${page==='exam'?'active':''}">Exam Center</button><button data-nav="progress" class="${page==='progress'?'active':''}">My Progress</button><button data-nav="teacher" class="${page==='teacher'?'active':''}">Teacher</button>
  </div></aside><main class="main"><div class="topbar"><div><b>${platform.version}</b><div class="muted small">Prototype kiến trúc mở rộng – chưa nối tài khoản/database thật</div></div><span class="pill">Free-first architecture</span></div>${content}<div class="footer-note">Prototype v0.1 · Dữ liệu hiện lưu trên thiết bị. Bước sau sẽ thay adapter bằng Supabase mà không đổi cấu trúc course content.</div></main></div>`;
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{page=b.dataset.nav;currentLesson=null;render()});
}
function home(){const p=progressStore.load();return `<section class="hero"><div><h1>Học liệu, lớp học và tiến bộ trong một nơi</h1><p>Platform được thiết kế để thêm giáo trình mới mà không tạo website mới. Objectives B1 là course đầu tiên; Life, HP5, HP6 và các course khác sẽ được thêm như dữ liệu/module.</p></div><div class="metric"><span>Đã hoàn thành</span><strong>${p.completed.length}</strong><span>hoạt động trên thiết bị này</span></div></section><h2 class="section-title">Programs</h2><div class="grid">${programs.map(courseCard).join('')}</div><h2 class="section-title">Core modules</h2><div class="module-list">${systemModules.map(x=>`<div class="card module"><b>${x.title}</b><p>${x.desc}</p></div>`).join('')}</div>`}
function courseCard(c){return `<div class="card course" data-course="${c.id}"><span class="tag ${c.status==='planned'?'future':''}">${c.status==='active'?'Đang xây':'Sẵn chỗ để thêm'}</span><h3>${c.title}</h3><p><b>${c.audience}</b><br>${c.description}</p></div>`}
function courses(){return `<h1>Courses</h1><p class="muted">Mỗi giáo trình là một program/course trong cùng platform.</p><div class="grid">${programs.map(courseCard).join('')}</div>`}
function program(id){const d=dataByProgram[id];if(!d)return `<button class="btn ghost back" data-nav="courses">← Courses</button><div class="card"><h2>Module đã được chừa sẵn</h2><p>Khi có tài liệu, chỉ thêm dữ liệu course; không tạo website mới.</p></div>`;const units=d.units;return `<button class="btn ghost back" data-nav="courses">← Courses</button><h1>${d.title} · ${d.classGroup}</h1>${units.map(u=>`<div class="card"><span class="tag">${u.totalPeriods} tiết</span><h2>${u.title}</h2><p class="muted">${u.sourceNote}</p><div class="lesson-list">${u.lessons.map((l,i)=>`<div class="card lesson"><div class="num">${i+1}</div><div><b>${l.title}</b><div class="muted small">${l.periods} tiết · ${l.sections.length} phần</div></div><button class="btn secondary" data-lesson="${l.id}" data-program="${id}" data-unit="${u.id}">Mở bài</button></div>`).join('')}</div><button class="btn" data-quiz="${u.id}" data-program="${id}">Quick Check</button></div>`).join('')}`}
function lessonView(pid,uid,lid){const u=dataByProgram[pid].units.find(x=>x.id===uid);const l=u.lessons.find(x=>x.id===lid);const p=progressStore.load();return `<button class="btn ghost back" data-course="${pid}">← ${u.title}</button><h1>${l.title}</h1><p class="muted">${u.title} · ${l.periods} tiết</p><div class="layout2"><div>${l.sections.map((s,i)=>{const sid=`${lid}:${i}`;const done=p.completed.includes(sid);return `<div class="card activity"><span class="tag">${s.type.toUpperCase()}</span><h3>${s.title}</h3><p>${s.summary}</p>${s.tracks? s.tracks.map(t=>`<audio class="audio" controls src="${t}"></audio>`).join(''):''}<button class="btn ${done?'secondary':''}" data-complete="${sid}">${done?'✓ Đã hoàn thành':'Đánh dấu hoàn thành'}</button></div>`}).join('')}</div><aside><div class="card"><h3>Self-study workflow</h3><p>Learn → Practice → Submit → Auto-mark/Teacher review → Progress.</p></div><div class="card"><h3>Submission modes</h3><p>Giai đoạn sau: nhập văn bản · chụp ảnh bài viết tay · upload PDF · ghi âm Speaking.</p></div></aside></div>`}
function quizView(pid,uid){const u=dataByProgram[pid].units.find(x=>x.id===uid);return `<button class="btn ghost back" data-course="${pid}">← ${u.title}</button><div class="card"><h1>${u.quiz.title}</h1><p class="muted">Bài mẫu để kiểm tra engine chấm tự động.</p><form id="quiz">${u.quiz.questions.map((x,i)=>`<div class="quiz-q"><b>${i+1}. ${x.q}</b>${x.options.map((o,j)=>`<label class="option"><input type="radio" name="${x.id}" value="${j}"> ${o}</label>`).join('')}</div>`).join('')}<button class="btn" type="submit">Nộp bài</button></form><div id="quiz-result"></div></div>`}
function generic(title,desc){return `<h1>${title}</h1><div class="card"><p>${desc}</p><div class="callout small">Module này đã có vị trí trong kiến trúc. Sẽ kích hoạt dần mà không đổi URL/platform chính.</div></div>`}
function progress(){const p=progressStore.load();return `<h1>My Progress</h1><div class="grid"><div class="card"><h3>Activities completed</h3><p style="font-size:34px;font-weight:800">${p.completed.length}</p></div><div class="card"><h3>Quiz attempts</h3><p style="font-size:34px;font-weight:800">${p.attempts.length}</p></div></div><h2 class="section-title">Recent attempts</h2><div class="card">${p.attempts.length?p.attempts.map(a=>`<p><b>${a.title}</b> · ${a.score}/${a.total} · ${new Date(a.at).toLocaleString('vi-VN')}</p>`).join(''):'<p class="muted">Chưa có lần làm bài.</p>'}<button class="btn ghost" id="reset-progress">Xóa dữ liệu demo</button></div>`}
function teacher(){return `<h1>Teacher Dashboard</h1><div class="grid"><div class="card"><h3>Classes</h3><p>CK1 (prototype)</p></div><div class="card"><h3>Assignments</h3><p>Chờ kết nối database.</p></div><div class="card"><h3>Review Queue</h3><p>Writing/Speaking submissions.</p></div><div class="card"><h3>Analytics</h3><p>Điểm theo kỹ năng, lỗi chung, tiến bộ.</p></div></div><div class="callout" style="margin-top:16px"><b>Nguyên tắc bảo mật:</b> bài thi chính thức sẽ chấm phía server; không để answer key nhạy cảm trong mã trình duyệt.</div>`}
function render(){let content='';if(currentLesson)content=lessonView(...currentLesson);else if(page==='home')content=home();else if(page==='courses')content=courses();else if(page.startsWith('program:'))content=program(page.split(':')[1]);else if(page==='skills')content=generic('Skills Lab','Listening · Speaking · Reading · Writing, dùng chung cho nhiều course.');else if(page==='exam')content=generic('Exam Center','VSTEP 4 kỹ năng, progress test, mock test, timer và auto-mark.');else if(page==='progress')content=progress();else content=teacher();shell(content);bind()}
function bind(){document.querySelectorAll('[data-course]').forEach(el=>el.onclick=()=>{page='program:'+el.dataset.course;currentLesson=null;render()});document.querySelectorAll('[data-lesson]').forEach(el=>el.onclick=()=>{currentLesson=[el.dataset.program,el.dataset.unit,el.dataset.lesson];render()});document.querySelectorAll('[data-complete]').forEach(el=>el.onclick=()=>{progressStore.mark(el.dataset.complete);render()});document.querySelectorAll('[data-quiz]').forEach(el=>el.onclick=()=>{currentLesson=['QUIZ',el.dataset.program,el.dataset.quiz];renderQuizRoute(el.dataset.program,el.dataset.quiz)});const r=document.querySelector('#reset-progress');if(r)r.onclick=()=>{progressStore.reset();render()}}
function renderQuizRoute(pid,uid){shell(quizView(pid,uid));document.querySelectorAll('[data-course]').forEach(el=>el.onclick=()=>{page='program:'+el.dataset.course;currentLesson=null;render()});const form=document.querySelector('#quiz');const u=dataByProgram[pid].units.find(x=>x.id===uid);form.onsubmit=e=>{e.preventDefault();let score=0;const details=[];u.quiz.questions.forEach(q=>{const v=form.elements[q.id].value;const ok=Number(v)===q.answer;if(ok)score++;details.push({q:q.q,ok,explain:q.explain})});progressStore.addAttempt({title:u.quiz.title,score,total:u.quiz.questions.length,at:Date.now()});document.querySelector('#quiz-result').innerHTML=`<div class="result ${score===u.quiz.questions.length?'ok':'bad'}">${score}/${u.quiz.questions.length} đúng</div>${details.map(d=>`<p class="small">${d.ok?'✅':'❌'} ${d.explain}</p>`).join('')}`}}
render();
